[[breaking-changes]]
== Breaking changes
coming[9.0.0]

We strive to maintain backward compatibility between minor versions (8.x to 8.y,
for example) so that you can upgrade without changing any configuration files.
On occasion, we are forced to break compatibility within a given major release
to ensure correctness of operation.

This section covers the changes that you need to be aware of when migrating to
Logstash 9.0.0 and later.

NOTE: Migrating directly between non-consecutive major versions (7.x to
9.x) is not recommended. 
We suggest that you upgrade to the last release in the 8.x series before you upgrade to 9.0.
// ToDo: Replace `last release in the 8.x series` in the previous statement with `{prev-major-last}`.
// Hardcoding it for now to avoid confusion. 

Check out our <<releasenotes>> for additional release information.

// Include statement to pull in 9.0 breaking changes file
// Add content for 9.0 breaking changes to `breaking-changes-90.asciidoc`, not here. 

include::breaking-changes-90.asciidoc[]

[discrete]
=== Breaking changes in earlier releases

See these topics for breaking changes in earlier releases:

* <<breaking-8.0>>
* <<breaking-7.0>>
* <<breaking-6.0>>

include::breaking-changes-80.asciidoc[]
include::breaking-changes-70.asciidoc[]
include::breaking-changes-60.asciidoc[]


