[[breaking-changes]]
== Breaking changes

**Breaking changes in 5.0**
The command `bin/plugin` has been renamed to `bin/logstash-plugin`. `bin/plugin <plugin>`` which is the current 
way of install packs/plugins is problematic because it pollutes the global namespace if it is put in the path. 
This command can now install both plugins and "Packs" - a single zip that contains 0 or 1 plugin for each system 
in the Elastic stack.

**Environment Variables Support in Configuration**
You can set environment variable references into Logstash plugins configuration using `${var}` or `$var` syntax.
Previously if you had used `${var}` or `$var` as a value in configuration, 5.0 will try to resolve it assuming 
it is an environment variable

[float]
== Kafka Input and Output Plugins

Kafka version 0.9 brings in new security features (SSL, client based auth, access control), 
improved consumer and producer API, and much more. For bringing in these features, Logstash 
had to use the new 0.9 version of the consumer which is not compatible with previous versions of the broker.
To use these new features, users have to first upgrade Kafka Brokers from 0.8.x to 0.9 and then use the 
input plugins. Please note that several configurations have changed in the Logstash configuration.

Configuration Changes:
* <<plugins-inputs-kafka,Kafka Input Plugin>>
* <<plugins-outputs-kafka,Kafka Output Plugin>>