[[breaking-changes]]

== Breaking Changes Across PQ Versions

If you are upgrading between Logstash versions and use the persistent queue, we strongly recommend draining or deleting
your persistent queue prior to the upgrade due to data incompatibilities. We are currently working on resolving these issues in our 6.3.0 release, but extra steps will need to be taken until then.

Drain the persistent queue be starting Logstash with the `queue.drain` setting enabled, followed by signalling Logstash to shutdown, then waiting for it to shutdown cleanly. This may take some time if you have a large queue backlog.

This will not be the case when moving between versions greater than or equal to 6.3.0.


== Breaking Changes in 6.0.0

This section discusses the changes that you need to be aware of when migrating to Logstash 6.0.0 from the previous major releases.

[float]
=== Changes in Logstash Core

These changes can impact any instance of Logstash and are plugin agnostic, but only if you are using the features that are impacted.

[float]
==== Application Settings

* The setting `config.reload.interval` has been changed to use time value strings such as `5m`, `10s` etc.
  Previously, users had to convert this to a millisecond time value themselves.

[float]
==== RPM/Deb package changes

* For `rpm` and `deb` release artifacts, config files that match the `*.conf` glob pattern must be in the conf.d folder,
  or the files will not be loaded.

[float]
==== Command Line Interface behavior

* The `-e` and `-f` CLI options are now mutually exclusive. This also applies to the corresponding long form options `config.string` and
  `path.config`. This means any configurations  provided via `-e` will no longer be appended to the configurations provided via `-f`.
* Configurations provided with `-f` or `config.path` will not be appended with `stdin` input and `stdout` output automatically.

[float]
==== List of plugins bundled with Logstash

The following plugins were removed from the 5.0 default bundle based on usage data. You can still install these plugins manually:

* logstash-codec-oldlogstashjson
* logstash-input-couchdb_changes
* logstash-input-irc
* logstash-input-log4j
* logstash-input-lumberjack
* logstash-filter-uuid
* logstash-output-xmpp
* logstash-output-irc
* logstash-output-statsd
