[[breaking-changes]]
== Breaking changes

This section discusses the changes that you need to be aware of when migrating your application to Logstash {version}.

[float]
=== Plugin Manager Renamed

`bin/plugin` has been renamed to `bin/logstash-plugin`. This change was to mainly prevent `PATH` being polluted when 
other components of the Elastic stack are installed on the same instance. Also, this provides a foundation 
for future change which will allow Elastic Stack packs to be installed via this script.

[float]
=== Kafka Input/Output Configuration Changes

This release added support for the new 0.9 consumer/producer API which supports security features introduced by Kafka. 
A few Configuration options were renamed to make it consistent with Kafka consumer and producer settings. 
Also, this plugin version will not work with Kafka 0.8 broker.

Please see the following specific plugin documentation for new configuration options:

* https://www.elastic.co/guide/en/logstash/{branch}/plugins-inputs-kafka.html[Kafka Input]
* https://www.elastic.co/guide/en/logstash/{branch}/plugins-outputs-kafka.html[Kafka Output]

[float]
=== Ruby Filter and Custom Plugin Developers

With the migration to the Java Event (https://github.com/elastic/logstash/issues/4191[Issue 4191]), we have changed 
how you can access internal data. The Event object no longer returns a reference to the data. Instead, it returns a
copy. This might change how you do manipulation of your data, especially when working with nested hashes.
When working with nested hashes, it’s recommended that you use the `fieldref` syntax instead of using multiple brackets.

**Examples:**

[source, js]
----------------------------------
filter { 
  ruby {
    codec => "event['uuid'] = event['uuid'].gsub(/b/, '')" # instead of using event['uuid'].gsub!(/b/, '')
  }
}
----------------------------------

[source, js]
----------------------------------
filter { 
  ruby {
    codec => "event['[product][price]'] = 10 # instead of using event['product']['price'] = 10
  }
}
----------------------------------

