[[breaking-changes]]
== Breaking changes

This section discusses the changes that you need to be aware of when migrating to Logstash 6.0.0 from the previous major releases of Logstash.

[float]
==== Application Settings

* The setting `config.reload.interval` has been changed to use time value strings such as `5m`, `10s` etc.
  Previously, users had to convert this to a millisecond time value themselves. 

[float]
==== RPM/Deb package changes

* For `rpm` and `deb` release artifacts, Logstash only globs config files matching `*.conf` pattern in the `conf.d` folder. 
  Any config files which don't follow this pattern will not be loaded.
  
[float]
==== Command Line Interface behavior

* The `-e` and `-f` CLI options are now mutually exclusive. This also applies to the corresponding long form options `config.string` and 
  `path.config`. This means config provided via `-e` will no longer be appended to the config provided via `-f`.
* Configuration provided with `-e` or `config.string` will not be appended with `stdin` input and `stdout` output automatically.

==== List of plugins bundled with Logstash

The following plugins were removed from 5.0 default bundle based on usage data collected by us. These plugins can still be installed 
manually for use:

* logstash-codec-oldlogstashjson
* logstash-input-couchdb_changes
* logstash-input-irc
* logstash-input-log4j
* logstash-input-lumberjack
* logstash-filter-uuid
* logstash-output-xmpp
* logstash-output-irc
* logstash-output-statsd
