[[filebeat-modules]]

== Working with Filebeat Modules

Filebeat comes packaged with pre-built  {filebeat-ref}/filebeat-modules.html[modules]
that contain the configurations needed to collect, parse, enrich, and visualize
data from various log file formats. Each Filebeat module consists of one or more
filesets that contain ingest node pipelines, Elasticsearch templates, Filebeat
prospector configurations, and Kibana dashboards.

Filebeat modules are a great way to get started, but you might find that ingest
pipelines don't offer the processing power that you require. If that's the case,
you'll need to use Logstash.

[float]
[[graduating-to-Logstash]]
=== Using Logstash instead of Ingest Node

Logstash provides an <<ingest-converter,ingest pipeline conversion tool>>
to help you migrate ingest pipeline definitions to Logstash configs. However,
the tool does not currently support all the processors that are available for
ingest node.

You can follow the steps in this section to build and run Logstash
configurations that parse the data collected by Filebeat modules. Then you'll be
able to use the same dashboards available with Filebeat to visualize your data
in Kibana.

[float]
==== Create and start the Logstash pipeline

. Create a Logstash pipeline configuration that reads from the Beats input and
parses the events.
+
See <<logstash-config-for-filebeat-modules>> for detailed examples.

. Start Logstash, passing in the pipeline configuration file that parses the
log. For example:
+
[source,shell]
----------------------------------------------------------------------
bin/logstash -f mypipeline.conf
----------------------------------------------------------------------
+
You'll see the following message when Logstash is running and listening for
input from Beats: 
+
[source,shell]
----------------------------------------------------------------------
[2017-10-13T00:01:15,413][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"127.0.0.1:5044"}
[2017-10-13T00:01:15,443][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"main"}
----------------------------------------------------------------------


The Logstash pipeline is now ready to receive events from Filebeat. Next, you
set up and run Filebeat.

[float]
==== Set up and run Filebeat

. If you haven't already set up the Filebeat index template and sample Kibana
dashboards, run the Filebeat `setup` command to do that now: 
+
[source,shell]
----------------------------------------------------------------------
./filebeat -e setup
----------------------------------------------------------------------
+
The `-e` flag is optional and sends output to standard error instead of syslog.
+
A connection to Elasticsearch and Kibana is required for this one-time setup
step because Filebeat needs to create the index template in Elasticsearch and
load the sample dashboards into Kibana. 
+
After the template and dashboards are loaded, you'll see the message `INFO
Kibana dashboards successfully loaded. Loaded dashboards`.

. Configure Filebeat to send log lines to Logstash. To do this, in the
+filebeat.yml+ config file, disable the Elasticsearch output, and enable the
Logstash output. For example:
+
[source,yaml]
-----
#output.elasticsearch:
  #hosts: ["localhost:9200"]
output.logstash:
  hosts: ["localhost:5044"]
-----

. Run the `modules enable` command to enable the modules that you want to run.
For example:
+
[source,shell]
----------------------------------------------------------------------
./filebeat modules enable nginx
----------------------------------------------------------------------
+
You can further configure the module by editing the config file under the
Filebeat `modules.d` directory. For example, if the log files are not in the
location expected by the module, you can set the `var.paths` option.

. Start Filebeat. For example, to start Filebeat in the foreground, use:
+
[source,shell]
----------------------------------------------------------------------
./filebeat -e
----------------------------------------------------------------------
+
NOTE: Depending on how you've installed Filebeat, you might see errors
related to file ownership or permissions when you try to run Filebeat modules.
See {beats-ref}/config-file-permissions.html[Config File Ownership and Permissions]
in the _Beats Platform Reference_ if you encounter errors related to file
ownership or permissions.
+
See {filebeat-ref}/filebeat-starting.html[Starting Filebeat] for more info.

[float]
==== Visualize the data

To visualize the data in Kibana, launch the Kibana web interface by pointing
your browser to port 5601. For example,
http://127.0.0.1:5601[http://127.0.0.1:5601]. 

[[logstash-config-for-filebeat-modules]]
=== Configuration Examples

The examples in this section show you how to build Logstash pipelines that parse
data sent collected by Filebeat modules:

* <<parsing-apache2>>
* <<parsing-mysql>>
* <<parsing-nginx>>
* <<parsing-system>>

[[parsing-apache2]]
==== Apache 2 Logs

The Logstash pipeline configuration in this example shows how to ship and parse
access and error logs collected by the
{filebeat-ref}/filebeat-module-apache2.html[`apache2` Filebeat module].

[source,json]
----------------------------------------------------------------------------
include::filebeat_modules/apache2/pipeline.conf[]
----------------------------------------------------------------------------


[[parsing-mysql]]
==== MySQL Logs

The Logstash pipeline configuration in this example shows how to ship and parse
error and slowlog logs collected by the
{filebeat-ref}/filebeat-module-mysql.html[`mysql` Filebeat module].

[source,json]
----------------------------------------------------------------------------
include::filebeat_modules/mysql/pipeline.conf[]
----------------------------------------------------------------------------


[[parsing-nginx]]
==== Nginx Logs

The Logstash pipeline configuration in this example shows how to ship and parse
access and error logs collected by the
{filebeat-ref}/filebeat-module-nginx.html[`nginx` Filebeat module].

[source,json]
----------------------------------------------------------------------------
include::filebeat_modules/nginx/pipeline.conf[]
----------------------------------------------------------------------------


[[parsing-system]]
==== System Logs

The Logstash pipeline configuration in this example shows how to ship and parse
system logs collected by the
{filebeat-ref}/filebeat-module-system.html[`system` Filebeat module].

[source,json]
----------------------------------------------------------------------------
include::filebeat_modules/system/pipeline.conf[]
----------------------------------------------------------------------------

