[[jvm-options-file]]
=== Setting JVM options

You should rarely need to change Java Virtual Machine (JVM) options. If you do,
the most likely change is setting the heap-size. The remainder of
this document explains in detail how to set JVM options.

The preferred method of setting JVM options (including system properties and JVM
flags) is via the `jvm.options` configuration file. The default location of this
file is `config/jvm.options` (when installing from the tar or zip distributions)
and `/etc/logstash/jvm.options` (when installing from the Debian or RPM
packages).

This file contains a line-delimited list of JVM arguments following
a special syntax:

* lines consisting of whitespace only are ignored
* lines beginning with `#` are treated as comments and are ignored
+
[source,text]
-------------------------------------
# this is a comment
-------------------------------------

* lines beginning with a `-` are treated as a JVM option that applies
  independent of the version of the JVM
+
[source,text]
-------------------------------------
-Xmx2g
-------------------------------------

* lines beginning with a number followed by a `:` followed by a `-` are treated
  as a JVM option that applies only if the version of the JVM matches the number
+
[source,text]
-------------------------------------
8:-Xmx2g
-------------------------------------

* lines beginning with a number followed by a `-` followed by a `:` are treated
  as a JVM option that applies only if the version of the JVM is greater than or
  equal to the number
+
[source,text]
-------------------------------------
8-:-Xmx2g
-------------------------------------

* lines beginning with a number followed by a `-` followed by a number followed
  by a `:` are treated as a JVM option that applies only if the version of the
  JVM falls in the range of the two numbers
+
[source,text]
-------------------------------------
8-9:-Xmx2g
-------------------------------------

* all other lines are rejected

You can add custom JVM flags to this file and check this configuration into your
version control system.

An alternative mechanism for setting Java Virtual Machine options is via the
`LS_JAVA_OPTS` environment variable. For instance:

[source,sh]
---------------------------------
export LS_JAVA_OPTS="$LS_JAVA_OPTS -Djava.io.tmpdir=/path/to/temp/dir"
---------------------------------

Additionally, some other Java programs support the `JAVA_OPTS` environment
variable. This is *not* a mechanism built into the JVM but instead a convention
in the ecosystem. However, we do not support this environment variable, instead
supporting setting JVM options via the `jvm.options` file or the environment
variable `LS_JAVA_OPTS` as above.