[[plugin-listing]]
=== Listing your plugin

The {logstash-ref}[Logstash Reference] is the first place {ls} users look for
plugins and documentation. If your plugin meets the quality and acceptance
guidelines, we can list it in the guide.

The plugin source and readme will continue to live in your repo, and we will
direct users there. 

[discrete]
[[plugin-acceptance]]
==== Acceptance guidelines

* **Consistency** Your plugin must be consistent in quality and naming conventions
used by other plugins. The plugin name must be unique and in this format:
`logstash-plugintype-pluginname`. If the plugin name is more than one word,
separate words with underscores. Example: _logstash-output-elastic_app_search_
* **Code Review** Your plugin must be reviewed by members of the community for
coherence, quality, readability, stability and security.
* **Tests** Your plugin must contain tests to be accepted. These tests are also
subject to code review for scope and completeness.  It's ok if you don't know
how to write tests -- we will guide you. We are working on publishing a guide to
creating tests for Logstash which will make it easier.  In the meantime, you can
refer to http://betterspecs.org/ for examples.

If you would like to have your plugin included, create a new
https://github.com/elasticsearch/logstash/issues[issue] in
the Logstash repository. 

TODO:  Should we request that they apply labels for faster service?
[Doc][PluginListing], for example.
