[[plugin-listing]]
=== Listing your plugin

The {logstash-ref}[Logstash Reference] is the first place {ls} users look for
plugins and documentation. If your plugin meets the quality and acceptance
guidelines, we can list it in the guide.

The plugin source and readme will continue to live in your repo, and we will
direct users there. 

[discrete]
[[plugin-acceptance]]
==== Acceptance guidelines

* **Consistency.** Your plugin must be consistent in quality and naming conventions
used by other plugins. The plugin name must be unique and in this format:
`logstash-plugintype-pluginname`. If the plugin name is more than one word,
separate words with underscores. Example: _logstash-output-elastic_app_search_
* **Documentation.** Documentation is a required component of your plugin.
When we list your plugin, we point to your documentation--a readme.md,
docs/index.asciidoc, or both--in your plugin repo.
* **Code Review.** Your plugin must be reviewed by members of the community for
coherence, quality, readability, stability and security.
* **Tests.** Your plugin must contain tests to be accepted. You can
refer to http://betterspecs.org/ for examples. 
** Step 1. Enable travis on your account
** Step 2. Import our standard travis.yml
https://github.com/logstash-plugins/.ci/blob/1.x/travis/travis.yml, as shown in the
https://github.com/logstash-plugins/logstash-filter-fingerprint/blob/master/.travis.yml[fingerprint
filter example].
** Step 3. Have specs in the spec folder.

If you would like to have your plugin included in the {logstash-ref}[Logstash
Reference], create a new https://github.com/elasticsearch/logstash/issues[issue]
in the Logstash repository. 

TODO:  Should we request that they apply labels for faster service?
[Doc][PluginListing], for example.
