[[ls-to-ls]]
=== Logstash-to-Logstash communication

{ls}-to-{ls} communication is available if you need to have one {ls} instance communicate with another {ls} instance. 
You may need this configuration if the data path crosses network or firewall boundaries, for example. 

Logstash-to-Logstash communication can add complexity to your environment.
If your use case doesn't need it, then we suggest that you don't implement it.

NOTE: If you are looking for information on connecting multiple pipelines within
one Logstash instance, see <<pipeline-to-pipeline>>.

* <<ls-to-ls-lumberjack>> has been our standard approach for {ls}-to-{ls}, and may still be the best option for more robust use cases (such as scenarios requiring load balancing or round-trip acknowledgments). 
* <<ls-to-ls-http>> is the approach we're moving toward.  
For now, consider using the <<plugins-outputs-http,http output>> to <<plugins-inputs-http,http input>> for {ls}-to-{ls} communication if the current limitations don't apply to your use case. 
We are investigating adding purpose-built plugins to make configuration easier and to fill out the feature set to remove limitations. 


include::ls-ls-http.asciidoc[]
include::ls-ls-lumberjack.asciidoc[]
