[[connecting-to-cloud]]
=== Sending data to Elasticsearch Service

Our hosted Elasticsearch Service is available on AWS, GCP, and Azure.
{ess-trial}[You can try the Elasticsearch Service for free].

Logstash comes with two settings that simplify sending data to
https://cloud.elastic.co/[Elastic Cloud]: Cloud ID and Cloud Auth. 

==== Cloud ID

The Cloud ID, which can be found in the Elastic Cloud web console, is used by
Logstash to build the Elasticsearch and Kibana hosts settings.
It is a base64 encoded text value of about 120 characters made up of upper and
lower case letters and numbers.
If you have several Cloud IDs, you can add a label, which is ignored
internally, to help you tell them apart. To add a label you should prefix your
Cloud ID with a label and a `:` separator in this format "<label>:<cloud-id>"

Cloud ID overwrites these settings:
----
var.elasticsearch.hosts
var.kibana.host
----

==== Cloud Auth
This is optional. Construct this value by following this format "<username>:<password>".
Use your Cloud username for the first part. Use your Cloud password for the second part,
which is given once in the Cloud UI when you create a cluster.
As your Cloud password is changeable, if you change it in the Cloud UI remember to change it here too.

Cloud Auth when specified overwrites these settings:
----
var.elasticsearch.username
var.elasticsearch.password
var.kibana.username
var.kibana.password
----

==== Using Cloud ID and Cloud Auth with plugins

The Elasticsearch input, output, and filter plugins support cloud.id and
cloud.auth in their configurations. 

* <<plugins-inputs-elasticsearch-cloud_id,Elasticsearch input plugin>>
* <<plugins-filters-elasticsearch-cloud_id,Elasticsearch filter plugin>>
* <<plugins-outputs-elasticsearch-cloud_id,Elasticsearch output plugin>>

==== Sending data to Elasticsearch Service from modules

Cloud ID and Cloud Auth can be specified in the `logstash.yml` <<logstash-settings-file,settings file>>.
They should be added separately from any module configuration settings you may have added before.

["source","yaml",subs="attributes"]
----
# example with a label
cloud.id: "staging:dXMtZWFzdC0xLmF3cy5mb3VuZC5pbyRub3RhcmVhbCRpZGVudGlmaWVy"
cloud.auth: "elastic:{pwd}"
----

["source","yaml",subs="attributes"]
----
# example without a label
cloud.id: "dXMtZWFzdC0xLmF3cy5mb3VuZC5pbyRub3RhcmVhbCRpZGVudGlmaWVy"
cloud.auth: "elastic:{pwd}"
----

These settings can be also specified at the command line, like this:

["source","sh",subs="attributes,callouts"]
----
bin/logstash --modules netflow -M "netflow.var.input.udp.port=3555" --cloud.id <your-cloud-id> --cloud.auth <your-cloud-auth>
----


