[[logstash-to-elasticsearch-serverless]]
=== Sending data to {es-serverless}

When you use Elasticsearch on Elastic Cloud Serverless you don’t need to worry about managing the infrastructure that keeps Elasticsearch distributed and available. These resources are automated on the serverless platform and are designed to scale up and down with your workload.


.{ls} to {serverless-full}
****
You'll use the {ls} link:https://www.elastic.co/guide/en/logstash/8.19/plugins-outputs-elasticsearch.html[{es} output plugin] to send data to {serverless-full}.
Note these differences between {es-serverless} and both {ech} and self-managed {es}:

* Use link:https://www.elastic.co/guide/en/logstash/8.19/ls-security.html#ls-api-keys[API keys] to access {serverless-full} from {ls} as it does not support native user authentication.
  Any user-based security settings in your {ls} link:https://www.elastic.co/guide/en/logstash/8.19/plugins-outputs-elasticsearch.html[{es} output plugin] configuration are ignored and may cause errors.
* {serverless-full} uses **data streams** and link:https://www.elastic.co/guide/en/elasticsearch/reference/8.19/data-stream-lifecycle.html[{dlm} ({dlm-init})] instead of {ilm} ({ilm-init}). Any {ilm-init} settings in your link:https://www.elastic.co/guide/en/logstash/8.19/plugins-outputs-elasticsearch.html[{es} output plugin] configuration are ignored and may cause errors.
* **{ls} monitoring** is available through the link:https://github.com/elastic/integrations/blob/main/packages/logstash/docs/README.md[{ls} Integration] in link:https://www.elastic.co/guide/en/observability/8.19/index.html[Elastic Observability] on {serverless-full}.

*Known issue for Logstash to Elasticsearch Serverless.* +
The logstash-output-elasticsearch `hosts` setting defaults to port :9200. +
Set the value to port :443 instead.
****

[[connecting-to-elasticsearch-serverless]]
==== Communication between {ls} and {es-serverless} 

{es-serverless} simplifies safe, secure communication between {ls} and {es}.
To send data to a {serverless-short} project, configure the {ls} {es} output plugin to connect using the project's **{es} endpoint URL** and an **API key**.

[source,ruby]
output {elasticsearch { hosts => "ELASTICSEARCH_ENDPOINT_URL" api_key => "<api key>" } }

The value of the link:https://www.elastic.co/guide/en/logstash/8.19/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-api_key[`api_key` option] is in the format `id:api_key`, where `id` and `api_key` are the values returned by the link:https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-security-create-api-key[Create API key API].

[[endpoint-serverless]]
===== {es} endpoint URL

1. Log in to https://cloud.elastic.co/[Elastic Cloud].
2. Find your **{es} endpoint URL**:

* Select **Manage** next to your project. Then find the {{es}} endpoint under **Application endpoints, cluster and component IDs**. 
* Alternatively, open your project, select the help icon, then select **Connection details**.

[[api-key-serverless]]
===== API key 

Create an **API key** with the appropriate privileges. 
Refer to {kibana-ref}/search-space-connection-details.html#create-an-api-key-cloud-self-managed[Create API key] for detailed steps. 
For information on the required privileges, refer to <<ls-api-keys>>.

When you create an API key for {ls}, select *Logstash* from the *API key format* dropdown.
This option formats the API key in the correct `id:api_key` format required by {ls}.

NOTE: The link:https://www.elastic.co/guide/en/logstash/8.19/plugins-inputs-elasticsearch.html#plugins-inputs-elasticsearch-api_key[{es} input],
link:https://www.elastic.co/guide/en/logstash/8.19/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-api_key[{es} output], and
link:https://www.elastic.co/guide/en/logstash/8.19/plugins-filters-elasticsearch.html#plugins-filters-elasticsearch-api_key[{es} filter] plugins, as well as the
link:https://www.elastic.co/guide/en/logstash/8.19/plugins-filters-elastic_integration.html#plugins-filters-elastic_integration-api_key[Elastic_integration filter] plugin, all support the `api_key` option in their configurations.

[cpm-serverless]
===== Using {ls} Central Pipeline Management with {es-serverless} 

To set up Central Pipeline management in {es-serverless}, update the `logstash.yml` config file to provide the API key and set the value for `xpack.management.elasticsearch.hosts` to your Elasticsearch endpoint URL.

[source,ruby]
xpack.management.elasticsearch.hosts: "ELASTICSEARCH_ENDPOINT_URL"  <1>
xpack.management.elasticsearch.api_key: "<api_key>"  <2>

<1> Use the `hosts` option with the Elasticsearch endpoint URL to connect to Elasticsearch Serverless
<2> API key formatted for Logstash:  `id:api_key`
