[[releasenotes]]
== Release Notes

This section summarizes the changes in the following releases:

* <<logstash-6-0-0-rc2,Logstash 6.0.0-rc2>>
* <<logstash-6-0-0-rc1,Logstash 6.0.0-rc1>>
* <<logstash-6-0-0-beta2,Logstash 6.0.0-beta2>>
* <<logstash-6-0-0-beta1,Logstash 6.0.0-beta1>>
* <<logstash-6-0-0-alpha2,Logstash 6.0.0-alpha2>>
* <<logstash-6-0-0-alpha1,Logstash 6.0.0-alpha1>>

ifdef::include-xpack[]
See also:

* <<release-notes-xls>>
endif::include-xpack[]

[[logstash-6-0-0-rc2]]
=== Logstash 6.0.0-rc2 Release Notes

* https://github.com/elastic/logstash/commit/840439722d8ef4737c7e8101c59652ced191bbea[Improved performance]
* https://github.com/elastic/logstash/commit/546951fa889902d8ec56f8a7cec1dc41a21088ff[Modules: Set default credentials for Kibana if es info is present]
* More small consistency fixes for Windows 
* Fix bug where the Elasticsearch output would not correctly log errors but rather log an exception in the error handler, thus hiding the actual error message.

[[logstash-6-0-0-rc1]]
=== Logstash 6.0.0-rc1 Release Notes

* https://github.com/elastic/logstash/pull/8318[Added all commercially supported plugins to bundled plugins]
* existing `JAVA_OPTS` env var is now ignored for consistency with Elasticsearch
* JAVA_TOOL_OPTIONS env var is cleared for consistency with Elasticsearch
* Now only LS_JAVA_OPTS env var is supported to append options to parsed options from the jvm.options file.
* dropped support of the LS_JVM_OPTS env var
* dropped support of the USE_RUBY and USE_DRIP environment variables
* Fixed  https://github.com/elastic/logstash/pull/8226[password support] in modules
* A variety of small consistency / testing fixes for the Windows platform
* Misc stability fixes

[[logstash-6-0-0-beta2]]
=== Logstash 6.0.0-beta2 Release Notes

* Added `cloud.id` and `cloud.auth` support for modules to provide an easy way to integrate with Elastic Cloud service.
* Added an explicit `--setup` phase for modules which is used to install dashboards and Elasticsearch template.
* Enabled DLQ support for multipipelines

[[logstash-6-0-0-beta1]]
=== Logstash 6.0.0-beta1 Release Notes

* Added new `logstash.yml` setting: `config.support_escapes`. When enabled, Logstash will interpret escape sequences in
  strings in the pipeline configuration.
* Breaking: The setting `config.reload.interval` has been changed to use time value strings such as `5m`, `10s`, etc for
  convenience. Previously, users had to convert this to a second time value themselves.
* Breaking: The list of plugins bundled with Logstash 6.0.0-beta1 release has changed. Please consult the breaking changes document
  for a complete list.
* Added an {xpack} feature to manage Logstash configurations centrally in Elasticsearch. We've also added a UI to manage
  configurations directly in Kibana without having to restart Logstash.
* Users can now visualize the Logstash configuration pipeline as part of the {xpack} monitoring feature.
* We now report an error if config file referenced in the `pipelines.yml` is missing.

[[logstash-6-0-0-alpha2]]
=== Logstash 6.0.0-alpha2 Release Notes

* Breaking: Currently, when Logstash is installed and set up via package managers, it loads all files found
  in `/etc/logstash/conf.d` as configuration. This can be problematic if there are non-configuration files in this
  folder. Starting from alpha2, Logstash will only glob files ending with `.conf` extension in `/etc/logstash/conf.d` ({lsissue}6979)[Issue 6979)]).
* Added support for running multiple pipelines in the same Logstash instance. Running multiple pipelines
  allow users to isolate data flow, provide separate runtime pipeline parameters and helps simplify complex
  configurations.
* A new `pipelines.yml` configuration file has been added to define pipelines.

[[logstash-6-0-0-alpha1]]
=== Logstash 6.0.0-alpha1 Release Notes

* Introducing a new internal representation for the existing Logstash configuration that forms the
  foundation of many new features. This is not a breaking change, and existing configs will work as is.

[float]

==== Filter Plugins

*`GeoIP`*: You can now use MaxMind's commercial database to get enriched Geo information. ASN data can be
  obtained via the GeoIP2-ISP database.
