[[releasenotes]]
== Release Notes

coming[8.0.0]

This section summarizes the changes in the following releases:


//* <<logstash-8-0-0-alpha2,Logstash 8.0.0-alpha2>>
* <<logstash-8-0-0-alpha1,Logstash 8.0.0-alpha1>>

Logstash 8.0.0 Release Notes

coming[8.0.0]
////
[[logstash-8-0-0-alpha2]]
=== Logstash 8.0.0-alpha2 Release Notes

Placeholder for alpha2 release notes


[[logstash-8-0-0-alpha1]]
=== Logstash 8.0.0-alpha1 Release Notes

==== New features and enhancements

==== Plugin releases




---------- GENERATED CONTENT STARTS HERE ------------

=== Commits only in master
68f3cf3d9 - ecs_compatibility: revert breaking change; keep `disabled` as default for 8.0.0 (#13080) (2 days ago) <Ry Biesemeyer>
0b08838d2 - bump devutils dependency to 2.x (#12857) (6 weeks ago) <João Duarte>
1f670e62b - turn off data streams in internal monitoring collection (#12941) (8 weeks ago) <João Duarte>
3e0c61a4f - fix DLQ integration tests (#12871) (3 months ago) <João Duarte>
90a4f55a1 - Fix ES HOW integration tests on `master` (#12872) (3 months ago) <Andrea Selva>
d19d8c679 - Support for UTF-16 and other multi-byte-character logfiles (#9702) (3 months ago) <Erwin Dondorp>
bac5e89dd - Remove json ~>1 pinning (#12851) (3 months ago) <João Duarte>
4eeaa4af9 - Fix integration test to allow wildcard deletion in elasticsearch (#12806) (4 months ago) <kaisecheng>
7b855820e - Adds option to pass custom data to the benchmark CLI (#12437) (4 months ago) <IvoGoman>
9a63ec270 - Add some javadocs comments to the classes Removes never used class org.logstash.execution.queue.LegacyMemoryQueueWriter (7 months ago) <andsel>
d176e608b - Enable javadoc lint only for files that contains javadoc comments, avoid warning for missing javadoc comments on everything else (7 months ago) <andsel>
4bc9dad69 - Remove ruby execution engine (#12517) (7 months ago) <kaisecheng>
69451e501 - clean up field-reference-parser (#12466) (8 months ago) <kaisecheng>
b47cdc33e - add ssl verification_mode to env2yaml (11 months ago) <Drew Boswell>
7df8a660e - Drop dependency:bundler task (#12017) (1 year, 1 month ago) <João Duarte>
d8b50deff - update bundler to 2.x (#11994) (1 year, 1 month ago) <João Duarte>
* 386c263a7 - Fix: rounded to 1 second in nanos to avoid random NaN error (1 year, 2 months ago) <andsel>
* 6a727ca16 - [BUILD]Fix: chaining of GRADLE_OPTS (#11878) (1 year, 2 months ago) <Andrea Selva>
* fb8108e63 - Fix: missed 'set' to assign environment variable and log it (#11869) (1 year, 2 months ago) <Andrea Selva>
62454c667 - Remove obsolete setting from Elasticsearch integration test (#11873) (1 year, 3 months ago) <Rob Bavey>
fa2fb6cfa - Fix: condition to check environment variable was inverted (#11865) (1 year, 3 months ago) <Andrea Selva>
d35677aef - Fail fast when integration test fixtures cannot be setup. (#11855) (1 year, 3 months ago) <Rob Bavey>
d522a7cb3 - bring back unicode trimmer for LogStash::Util (#11712) (1 year, 4 months ago) <João Duarte>
fc0ced570 - Fixed time format that introduced flaky tests depending on time (1 year, 5 months ago) <andsel>
3695580b9 - Adaptations to internal collector to send data directly to monitoring cluster Close 11573 (1 year, 5 months ago) <andsel>
* 80a91f9a7 - fix java filter unit test link (1 year, 6 months ago) <Fabien Baligand>
c9b09bb36 - Remove NodeStats#mem_payload (#9051) (1 year, 7 months ago) <Ioana Tagirta>
71eed80d3 - Fixes to JMH launch after upgrade to Gradle 5 (1 year, 7 months ago) <andsel>
e807a9e03 - Update gradle wrapper to 5.6.4 (#11389) (1 year, 8 months ago) <João Duarte>
aad25d9bb - Drop _xpack namespace for ES security and license endpoints (1 year, 8 months ago) <andsel>
4f902b435 - Remove unused code (#11231) (1 year, 9 months ago) <João Duarte>
f5f2173c6 - Enhanced API testing (#10972) (1 year, 11 months ago) <Mike Place>

====== Doc
51b359b01 - Add a template on how to create an issue when requesting to list a plugin in docs (#12944) (7 weeks ago) <Andres Rodriguez>
da3157c01 - Doc: Expand definition and fix typo (#12936) (8 weeks ago) <Karen Metts>
2caea1367 - [doc] Add example to cross-plugin-concepts (#12672) (3 months ago) <Andres Rodriguez>
35c0f0694 - Update keystore.asciidoc (6 months ago) <Inbar Shimshon>
6d9ff9c88 - Change text to use Elastic Cloud (#12404) (8 months ago) <Andres Rodriguez>
7cccf7ddc - [Doc] Remove field reference parser (#12478) (8 months ago) <kaisecheng>
5c4dd3c25 - [doc] Add clarifying note to Logstash repo install (9 months ago) <Andres Rodriguez>
96328aec3 - Doc: Clarify use of queue max bytes setting (#12340) (9 months ago) <Karen Metts> FORWARDPORT
a839868b1 - Doc:Rename internal collection to legacy collection (1 year, 3 months ago) <Karen Metts>
fc20e9b91 - Fix sv agreement (#11667) (1 year, 5 months ago) <Karen Metts>
28345e8ca - Improve warning about UDP/TCP not having app level acks (1 year, 11 months ago) <João Duarte>
64c288954 - Docs: Fix formatting in table (#11016) (1 year, 11 months ago) <Nik Everett>
235755ce7 - Docs: Add more missing subs for asciidoctor (#10991) (2 years ago) <Nik Everett>
a1d2ba3b3 - [Docs] Asciidoctor support (#10730) (2 years, 3 months ago) <Nik Everett>
1d5f9e0bc - Clean up release notes and add placeholders for master (#10670) (2 years, 3 months ago) <Karen Metts>

=== Logstash Commits between master and 7.13.4

Computed with "git log --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit --date=relative v7.13.4..master"


=== Logstash Plugin Release Changelogs ===
Computed from "git diff v7.13.4..master *.release"
Changed plugin versions:
logstash-core-plugin-api: 2.1.16 -> 2.1.16
logstash-codec-avro: 3.2.4 -> 3.2.4
logstash-codec-cef: 6.2.2 -> 6.2.2
logstash-codec-collectd: 3.0.8 -> 3.0.8
logstash-codec-dots: 3.0.6 -> 3.0.6
logstash-codec-edn: 3.0.6 -> 3.0.6
logstash-codec-edn_lines: 3.0.6 -> 3.0.6
logstash-codec-es_bulk: 3.0.8 -> 3.0.8
logstash-codec-fluent: 3.3.0 -> 3.3.0
logstash-codec-graphite: 3.0.5 -> 3.0.5
logstash-codec-json: 3.0.5 -> 3.0.5
logstash-codec-json_lines: 3.0.6 -> 3.0.6
logstash-codec-line: 3.0.8 -> 3.0.8
logstash-codec-msgpack: 3.0.7 -> 3.0.7
logstash-codec-multiline: 3.0.11 -> 3.0.11
logstash-codec-netflow: 4.2.1 -> 4.2.1
logstash-codec-plain: 3.0.6 -> 3.0.6
logstash-codec-rubydebug: 3.1.0 -> 3.1.0
logstash-filter-aggregate: 2.9.2 -> 2.9.2
logstash-filter-anonymize: 3.0.6 -> 3.0.6
logstash-filter-cidr: 3.1.3 -> 3.1.3
logstash-filter-clone: 4.1.1 -> 4.1.1
logstash-filter-csv: 3.0.10 -> 3.0.10
logstash-filter-date: 3.1.9 -> 3.1.9
logstash-filter-de_dot: 1.0.4 -> 1.0.4
logstash-filter-dissect: 1.2.0 -> 1.2.0
logstash-filter-dns: 3.1.4 -> 3.1.4
logstash-filter-drop: 3.0.5 -> 3.0.5
logstash-filter-elasticsearch: 3.9.3 -> 3.9.3
logstash-filter-fingerprint: 3.2.4 -> 3.2.4
logstash-filter-geoip: 7.1.3 -> 7.1.3
logstash-filter-grok: 4.4.0 -> 4.4.0
logstash-filter-http: 1.0.2 -> 1.0.2
logstash-filter-json: 3.1.0 -> 3.1.0
logstash-filter-kv: 4.4.1 -> 4.4.1
logstash-filter-memcached: 1.1.0 -> 1.1.0
logstash-filter-metrics: 4.0.7 -> 4.0.7
logstash-filter-mutate: 3.5.2 -> 3.5.2
logstash-filter-prune: 3.0.4 -> 3.0.4
logstash-filter-ruby: 3.1.7 -> 3.1.7
logstash-filter-sleep: 3.0.7 -> 3.0.7
logstash-filter-split: 3.1.8 -> 3.1.8
logstash-filter-syslog_pri: 3.1.0 -> 3.1.0
logstash-filter-throttle: 4.0.4 -> 4.0.4
logstash-filter-translate: 3.2.3 -> 3.2.3
logstash-filter-truncate: 1.0.4 -> 1.0.4
logstash-filter-urldecode: 3.0.6 -> 3.0.6
logstash-filter-useragent: 3.2.4 -> 3.2.4
logstash-filter-uuid: 3.0.5 -> 3.0.5
logstash-filter-xml: 4.1.2 -> 4.1.2
logstash-input-azure_event_hubs: 1.2.3 -> 1.2.3
logstash-input-beats: 6.1.5 -> 6.1.5
logstash-input-couchdb_changes: 3.1.6 -> 3.1.6
logstash-input-dead_letter_queue: 1.1.5 -> 1.1.5
logstash-input-elasticsearch: 4.9.1 -> 4.9.1
logstash-input-exec: 3.3.3 -> 3.3.3
logstash-input-file: 4.2.4 -> 4.2.4
logstash-input-ganglia: 3.1.4 -> 3.1.4
logstash-input-gelf: 3.3.0 -> 3.3.0
logstash-input-generator: 3.0.6 -> 3.0.6
logstash-input-graphite: 3.0.6 -> 3.0.6
logstash-input-heartbeat: 3.0.7 -> 3.0.7
logstash-input-http: 3.3.7 -> 3.3.7
logstash-input-http_poller: 5.0.2 -> 5.0.2
logstash-input-imap: 3.1.0 -> 3.1.0
logstash-input-jms: 3.1.2 -> 3.1.2
logstash-input-pipe: 3.0.7 -> 3.0.7
logstash-input-redis: 3.6.1 -> 3.6.1
logstash-input-s3: 3.6.0 -> 3.6.0
logstash-input-snmp: 1.2.7 -> 1.2.7
logstash-input-snmptrap: 3.0.6 -> 3.0.6
logstash-input-sqs: 3.1.3 -> 3.1.3
logstash-input-stdin: 3.3.0 -> 3.3.0
logstash-input-syslog: 3.5.0 -> 3.5.0
logstash-input-tcp: 6.0.10 -> 6.0.10
logstash-input-twitter: 4.0.3 -> 4.0.3
logstash-input-udp: 3.4.1 -> 3.4.1
logstash-input-unix: 3.0.7 -> 3.0.7
logstash-integration-jdbc: 5.0.7 -> 5.0.7
logstash-integration-kafka: 10.7.6 -> 10.7.6
logstash-integration-rabbitmq: 7.2.0 -> 7.2.0
logstash-mixin-aws: 4.4.1 -> 4.4.1
logstash-mixin-deprecation_logger_support: 1.0.0 -> 1.0.0
logstash-mixin-ecs_compatibility_support: 1.1.0 -> 1.1.0
logstash-mixin-http_client: 7.0.0 -> 7.0.0
logstash-mixin-validator_support: 1.0.1 -> 1.0.1
logstash-output-cloudwatch: 3.0.9 -> 3.0.9
logstash-output-csv: 3.0.8 -> 3.0.8
logstash-output-elastic_app_search: 1.1.1 -> 1.1.1
logstash-output-elasticsearch: 11.0.2 -> 11.0.2
logstash-output-email: 4.1.1 -> 4.1.1
logstash-output-file: 4.3.0 -> 4.3.0
logstash-output-graphite: 3.1.6 -> 3.1.6
logstash-output-http: 5.2.5 -> 5.2.5
logstash-output-lumberjack: 3.1.8 -> 3.1.8
logstash-output-nagios: 3.0.6 -> 3.0.6
logstash-output-null: 3.0.5 -> 3.0.5
logstash-output-pipe: 3.0.6 -> 3.0.6
logstash-output-redis: 5.0.0 -> 5.0.0
logstash-output-s3: 4.3.4 -> 4.3.4
logstash-output-sns: 4.0.7 -> 4.0.7
logstash-output-sqs: 6.0.0 -> 6.0.0
logstash-output-stdout: 3.1.4 -> 3.1.4
logstash-output-tcp: 6.0.0 -> 6.0.0
logstash-output-udp: 3.1.0 -> 3.1.0
logstash-output-webhdfs: 3.0.6 -> 3.0.6
logstash-patterns-core: 4.3.1 -> 4.3.1
---------- GENERATED CONTENT ENDS HERE ------------

==== Plugins

*Plugin Core - 2.1.16*

404: Not Found

*Avro Codec - 3.2.4*

*Cef Codec - 6.2.2*

*Collectd Codec - 3.0.8*

*Dots Codec - 3.0.6*

*Edn Codec - 3.0.6*

*Edn_lines Codec - 3.0.6*

*Es_bulk Codec - 3.0.8*

*Fluent Codec - 3.3.0*

*Graphite Codec - 3.0.5*

*Json Codec - 3.0.5*

*Json_lines Codec - 3.0.6*

*Line Codec - 3.0.8*

*Msgpack Codec - 3.0.7*

*Multiline Codec - 3.0.11*

*Netflow Codec - 4.2.1*

*Plain Codec - 3.0.6*

*Rubydebug Codec - 3.1.0*

*Aggregate Filter - 2.9.2*

*Anonymize Filter - 3.0.6*

*Cidr Filter - 3.1.3*

*Clone Filter - 4.1.1*

*Csv Filter - 3.0.10*

*Date Filter - 3.1.9*

*De_dot Filter - 1.0.4*

*Dissect Filter - 1.2.0*

*Dns Filter - 3.1.4*

*Drop Filter - 3.0.5*

*Elasticsearch Filter - 3.9.3*

*Fingerprint Filter - 3.2.4*

*Geoip Filter - 7.1.3*

*Grok Filter - 4.4.0*

*Http Filter - 1.0.2*

* Fixed minor documentation issues https://github.com/logstash-plugins/logstash-filter-http/pull/9[#9]

* Minor documentation fixes

* Beta version of HTTP filter plugin based on @lucashenning's [REST filter](https://github.com/lucashenning/logstash-filter-rest).

*Json Filter - 3.1.0*

*Kv Filter - 4.4.1*

*Memcached Filter - 1.1.0*

*Metrics Filter - 4.0.7*

*Mutate Filter - 3.5.2*

*Prune Filter - 3.0.4*

# 3.0.4
* Fixed regex to prevent Exception in sprintf call https://github.com/logstash-plugins/logstash-filter-prune/pull/25[#25]
* Changed testing to docker https://github.com/logstash-plugins/logstash-filter-prune/pull/27[#27]
* Added clarification in docs around whitelist_values
* Changed tests from insist to expect

* Update gemspec summary

* Fix some documentation issues

* internal: Bumped up logstash-core-plugin-api dependency to allow installation with Logstash 5.
* doc: Clarify that pruning of subfields is unsupported.

* doc: Documentation improvements.

* doc: Documentation improvements.

* internal,deps: Depend on logstash-core-plugin-api instead of logstash-core, removing the need to mass update plugins on major releases of logstash

* internal,deps: New dependency requirements for logstash-core for the 5.0 release

* internal: Plugins were updated to follow the new shutdown semantic, this mainly allows Logstash to instruct input plugins to terminate gracefully,
   instead of using Thread.raise on the plugins' threads. Ref: https://github.com/elastic/logstash/pull/3895
* internal,deps: Dependency on logstash-core update to 2.0

*Ruby Filter - 3.1.7*

*Sleep Filter - 3.0.7*

*Split Filter - 3.1.8*

*Syslog_pri Filter - 3.1.0*

*Throttle Filter - 4.0.4*

*Translate Filter - 3.2.3*

*Truncate Filter - 1.0.4*

*Urldecode Filter - 3.0.6*

*Useragent Filter - 3.2.4*

*Uuid Filter - 3.0.5*

*Xml Filter - 4.1.2*

*Azure_event_hubs Input - 1.2.3*

*Beats Input - 6.1.5*

*Couchdb_changes Input - 3.1.6*

*Dead_letter_queue Input - 1.1.5*

*Elasticsearch Input - 4.9.1*

*Exec Input - 3.3.3*

*File Input - 4.2.4*

*Ganglia Input - 3.1.4*

*Gelf Input - 3.3.0*

*Generator Input - 3.0.6*

*Graphite Input - 3.0.6*

*Heartbeat Input - 3.0.7*

*Http Input - 3.3.7*

*Http_poller Input - 5.0.2*

*Imap Input - 3.1.0*

*Jms Input - 3.1.2*

*Pipe Input - 3.0.7*

*Redis Input - 3.6.1*

*S3 Input - 3.6.0*

*Snmp Input - 1.2.7*

*Snmptrap Input - 3.0.6*

*Sqs Input - 3.1.3*

*Stdin Input - 3.3.0*

*Syslog Input - 3.5.0*

*Tcp Input - 6.0.10*

*Twitter Input - 4.0.3*

*Udp Input - 3.4.1*

*Unix Input - 3.0.7*

*Jdbc Integration - 5.0.7*

*Kafka Integration - 10.7.6*

*Rabbitmq Integration - 7.2.0*

*Aws Mixin - 4.4.1*

*Deprecation_logger_support Mixin - 1.0.0*

404: Not Found

*Ecs_compatibility_support Mixin - 1.1.0*

# 1.0.0

* Support Mixin for ensuring a plugin has an `ecs_compatibility` method that is configurable from an `ecs_compatibility` option that accepts the literal `disabled` or a v-prefixed integer representing a major ECS version (e.g., `v1`), using the implementation from Logstash core if available.

*Http_client Mixin - 7.0.0*

*Validator_support Mixin - 1.0.1*

# v1.0.0

* Introduces plugin parameter validation adapters, including initial backport for `:field_reference` validator.

*Cloudwatch Output - 3.0.9*

*Csv Output - 3.0.8*

*Elastic_app_search Output - 1.1.1*

*Elasticsearch Output - 11.0.2*

*Email Output - 4.1.1*

*File Output - 4.3.0*

*Graphite Output - 3.1.6*

*Http Output - 5.2.5*

*Lumberjack Output - 3.1.8*

*Nagios Output - 3.0.6*

*Null Output - 3.0.5*

*Pipe Output - 3.0.6*

*Redis Output - 5.0.0*

*S3 Output - 4.3.4*

*Sns Output - 4.0.7*

*Sqs Output - 6.0.0*

*Stdout Output - 3.1.4*

*Tcp Output - 6.0.0*

*Udp Output - 3.1.0*

*Webhdfs Output - 3.0.6*

*Core Patterns - 4.3.1*

////