[[releasenotes]]
== Release Notes

This section summarizes the changes in the following releases:

* <<logstash-5-4-2,Logstash 5.4.2>>
* <<logstash-5-4-1,Logstash 5.4.1>>
* <<logstash-5-4-0,Logstash 5.4.0>>

[[logstash-5-4-2]]
=== Logstash 5.4.2 Release Notes

* We now handle connection refused errors when installing a plugin ({lsissue}6529[Issue 6529]).
* Fixed an issue where environment variables specified in Elasticsearch Output host configuration 
  wasn't resolved correctly ({lsissue}6696[Issue 6696]).
* Fixed a concurrency issue in the persistent queues feature ({lsissue}7382[Issue 7382]).

[float]
==== Input Plugins

*`HTTP Poller`*:

* Added a top level user/password config option that apply to all URLs by default.
* Added support for eager authorization. The Logstash client will now send credentials in its first request 
  rather than waiting for a 401 challenge.
  
[float]
==== Output Plugins

*`Elasticsearch`*:

* Fixed an error where a 429 response code would cause this output to crash.
* This output now waits for all inflight requests to complete before stopping.

[float]
==== Filter Plugins

*`GeoIP`*: 

* Added support for commercial databases from Maxmind.
* Added ASN data support via GeoIP2-ISP database.

*`User Agent`*:

* Improved performance by 2.5x by moving core parser logic from Ruby to Java.

*`Grok`*:

* Fixed an issue where subdirectories in a pattern folder was causing Logstash to crash.


[[logstash-5-4-1]]
=== Logstash 5.4.1 Release Notes

* Fixed an issue on Windows where Logstash was unable to locate the default log4j2.properties file ({lsissue}6352[Issue 6352]).

[float]
==== Input Plugins

*`Beats`*:

* Fixed an issue where Logstash would incorrectly close the connection from beats due to a timeout (https://github.com/logstash-plugins/logstash-input-beats/issues/185[Issue 185]).

*`JDBC`*:

* This plugin now automatically reconnects on connection issues (https://github.com/logstash-plugins/logstash-input-jdbc/issues/45[Issue 45]).

*`HTTP Poller`*:

* Added option to specify top-level user/password options that apply to all URLs by default.
* Added eager auth functionality. This means the client will send any credentials in its first request rather than waiting for a 401 challenge.

*`Log4j`*:

* This input now rejects any non-log4j log objects sent as input.

*`RabbitMQ`*:

* Updated the underlying RabbitMQ Java lib to v3.0.0.

*`S3`*:

* Fixed an issue where Logstash would crash when attempting to ingest a JSON file with a message attribute that was not a string (https://github.com/logstash-plugins/logstash-input-s3/issues/109[Issue 109]).

*`Elasticsearch`*:

* Fixed scrolling to use JSON bodies in the requests.

==== Filter Plugins

*`Date`*:

* This plugin now ignores canceled events. Previously, these events were unnecessarily processed.

*`Fingerprint`*:

* Improved error messages that could happen during startup.

*`Grok`*:

* Fixed an issue where a subdirectory under the `patterns` directory could cause Logstash to crash at startup (https://github.com/logstash-plugins/logstash-filter-grok/issues/110[Issue 110]).
* Added ability to define custom patterns within a `grok` filter by using the `pattern_definitions` config option.

*`URL Decode`*:

* Fixed an issue where Logstash would crash when processing Unicode input with this filter.

==== Output Plugins

*`S3`*:

* Fixed the `restore_from_crash` option to use the same upload options as the normal uploader (https://github.com/logstash-plugins/logstash-output-s3/issues/140[Issue 140]).
* Updated the `canned_acl` option to allow `public-read`, `public-read-write` and `authenticated-read` as possible values.

*`RabbitMQ`*:

* Updated the underlying RabbitMQ Java lib to v3.0.0.

*`Elasticsearch`*:

* Added support for customizing the sniffing path with the `sniffing_path` and `absolute_sniffing_path` config options.

*`Kafka`*:

* Fixed a bug when Logstash would fail to start up when `SASL_SSL` and `PLAIN` (no Kerberos) options were specified.

[[logstash-5-4-0]]
=== Logstash 5.4.0 Release Notes

* The persistent queues feature is generally available (GA) now. The beta tag has been removed.
* The `dissect` filter is now bundled in the Logstash artifact.
* Updated the `line` and `multiline` codecs to be threadsafe when used with inputs.
* Logstash's plugin manager now works when an HTTP proxy is used ({lsissue}6619[Issue 6619], {lsissue}6528[Issue 6528]).
* On Windows deployments, we now search for the java executable in `%PATH%` which works well for 
  the latest JDK 8 updates.
* Fixed an issue where the JVM max heap size stats were reported incorrectly in the stats API ({lsissue}6608[Issue 6608]).
* Fixed an issue where Logstash would crash when using conditionals on a nested JSON field ({lsissue}6522[Issue 6522]).
