[[releasenotes]]
== Release Notes

This section summarizes the changes in the following releases:

* <<logstash-8-2-0,Logstash 8.2.0>>
* <<logstash-8-1-0,Logstash 8.1.0>>
* <<logstash-8-0-1,Logstash 8.0.1>>
* <<logstash-8-0-0,Logstash 8.0.0>>
* <<logstash-8-0-0-rc2,Logstash 8.0.0-rc2>>
* <<logstash-8-0-0-rc1,Logstash 8.0.0-rc1>>
* <<logstash-8-0-0-beta1,Logstash 8.0.0-beta1>>
* <<logstash-8-0-0-alpha2,Logstash 8.0.0-alpha2>>
* <<logstash-8-0-0-alpha1,Logstash 8.0.0-alpha1>>

[[logstash-8-2-0]]
=== Logstash 8.2.0 Release Notes

---------- GENERATED CONTENT STARTS HERE ------------
=== Logstash Pull Requests with label v8.2.0

* [DOC] precedence between environment variables and yml in docker https://github.com/elastic/logstash/pull/12198[#12198]
* Update failing policy in Central Management fetcher and license checker if hit ES down node https://github.com/elastic/logstash/pull/13689[#13689]
* Release notes for 8.1.0 https://github.com/elastic/logstash/pull/13828[#13828]
* Doc: Refine content for generated CA in LS-ES security section https://github.com/elastic/logstash/pull/13834[#13834]
* Add plugin uninstall release note https://github.com/elastic/logstash/pull/13867[#13867]
* Print bundled jdk's version in launch scripts when `LS_JAVA_HOME` is provided https://github.com/elastic/logstash/pull/13880[#13880]
* Update Jackson databind in ingest-converter tool https://github.com/elastic/logstash/pull/13900[#13900]
* Backport PR #13828 to main: Release notes for 8.1.0 https://github.com/elastic/logstash/pull/13911[#13911]
* Backport PR #13867 to main: Add plugin uninstall release note https://github.com/elastic/logstash/pull/13912[#13912]
* Removal of sys-v init.d scripts https://github.com/elastic/logstash/pull/13922[#13922]
* Fix/flaky error tests in missed retries to central management https://github.com/elastic/logstash/pull/13941[#13941]
* ensure puma is at least 5.6.4 https://github.com/elastic/logstash/pull/13944[#13944]
* [doc] Remove references to sysv and upstart scripts when running logstash as a service. https://github.com/elastic/logstash/pull/13953[#13953]
* Backport PR #13922 to 8.2: Removal of sys-v init.d scripts https://github.com/elastic/logstash/pull/13954[#13954]
* Backport PR #13953 to 8.2: [doc] Remove references to sysv and upstart scripts when running logstash as a service. https://github.com/elastic/logstash/pull/13955[#13955]
* [doc] Add Logstash to Logstash HTTP example configuration. https://github.com/elastic/logstash/pull/13973[#13973]
* Fix window CI for PQ size checking https://github.com/elastic/logstash/pull/13981[#13981]
* Backport PR #13981 to 8.2: Fix window CI for PQ size checking https://github.com/elastic/logstash/pull/13987[#13987]
* Doc: Restructure source files for pipeline configuration https://github.com/elastic/logstash/pull/13990[#13990]
* Backport PR #13973 to 8.2: [doc] Add Logstash to Logstash HTTP example configuration. https://github.com/elastic/logstash/pull/13999[#13999]
* Backport PR #13834 to 8.2: Doc: Refine content for generated CA in LS-ES security section https://github.com/elastic/logstash/pull/14012[#14012]
* Backport PR #13990 to 8.2: Doc: Restructure source files for pipeline configuration https://github.com/elastic/logstash/pull/14015[#14015]
* Fix Bundled JDK docs to reflect JDK 11 https://github.com/elastic/logstash/pull/14021[#14021]
* Backport PR #14021 to 8.2: Fix Bundled JDK docs to reflect JDK 11 https://github.com/elastic/logstash/pull/14022[#14022]

=== Logstash Commits between 8.2 and 8.1.3

Computed with "git log --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit --date=relative v8.1.3..8.2"

78a9c377f - (HEAD -> 8.2, origin/8.2) Fix Bundled JDK docs to reflect JDK 11 (#14021) (#14022) (13 hours ago) <github-actions[bot]>
b0e6da487 - Doc: Restructure source files for pipeline configuration 8.2 (#14015) (4 days ago) <github-actions[bot]>
61067e3ab - Doc: Refine content for generated CA in LS-ES security section 8.2 (#14012) (4 days ago) <github-actions[bot]>
b98230eb8 - [doc] Add Logstash to Logstash HTTP example configuration. (#13999) (8 days ago) <github-actions[bot]>
e38e7b761 - Fix window CI for PQ size checking (#13981) (#13987) (2 weeks ago) <github-actions[bot]>
a323af499 - bump lock file for 8.2 (#13963) (4 weeks ago) <github-actions[bot]>
fc8b03d55 - [doc] Remove references to sysv and upstart scripts when running logstash as a service. (#13953) (#13955) (4 weeks ago) <github-actions[bot]>
2464055ea - Removal of sys-v init.d scripts (#13922) (#13954) (4 weeks ago) <github-actions[bot]>
067abb808 - Update minor plugin versions in gemfile lock (#13951) (4 weeks ago) <github-actions[bot]>
9bb352e47 - add lockfile from 8.1 (4 weeks ago) <João Duarte>
682f07b70 - [DOC] precedence between environment variables and yml in docker (#12198) (4 weeks ago) <João Duarte>
d2739a875 - Updates the LogstashService launcher to use the JDK specified (#13946) (4 weeks ago) <Andrea Selva>
00e28b1d9 - [Test] Adds explicit unexpected JVM messages test, and simplifies regex in offline_spec (#13892) (4 weeks ago) <Rob Bavey>
43c657634 - Improve safety of stats retrieval from queue (#13942) (4 weeks ago) <Rob Bavey>
916ddf2c8 - Fix/flaky error tests in missed retries to central management (#13941) (4 weeks ago) <Andrea Selva>
b545f55f3 - CI: disable testing against 8.1.1 for 8.x (#13938) (4 weeks ago) <Karol Bucek>
c64ef889d - Doc: Logstash-to-Logstash communication  (#13926) (5 weeks ago) <Karen Metts>
b4c54ab68 - [Java17] Add `--add-export` settings to restore JDK17 compatibility (#13825) (5 weeks ago) <Rob Bavey>
71772074a - PQ size check for multiple pipelines (#13877) (5 weeks ago) <kaisecheng>
1a5030bd6 - add backoff to checkpoint write (#13902) (5 weeks ago) <kaisecheng>
e45fa8ae2 - Update branch choices in version bump workflow (5 weeks ago) <João Duarte>
c544ecb38 - Update failing policy in Central Management fetcher and license checker if hit ES down node (#13689) (5 weeks ago) <Andrea Selva>
01fd474dc - Fixes centos-7 package init scripts (5 weeks ago) <Andres Rodriguez>
d64248f62 - Bump releases.json (#13921) (5 weeks ago) <Rob Bavey>
de062add2 - Add plugin uninstall release note (#13867) (#13912) (6 weeks ago) <github-actions[bot]>
2a586b982 - Release notes for 8.1.0 (#13828) (#13911) (6 weeks ago) <github-actions[bot]>
1195b3842 - fix default argument handling in rake artifact task (#13904) (6 weeks ago) <João Duarte>
8de70172a - Enable content write permission for pr backporter workflow (#13898) (6 weeks ago) <João Duarte>
fbcbb7084 - Print bundled jdk's version in launch scripts when `LS_JAVA_HOME` is provided (#13880) (6 weeks ago) <Andrea Selva>
32675c1a8 - Update Jackson databind in ingest-converter tool (#13900) (6 weeks ago) <Andrea Selva>
27dc80f7e - Fix version bumper workflow target repo and user allow listing (6 weeks ago) <João Duarte>
85eed0851 - Update and rename main.yml to version_bumps.yml (6 weeks ago) <João Duarte>
ef69112b7 - Create main.yml (6 weeks ago) <João Duarte>
a8bd90c22 - Quotes java executable path in case it contains spaces (#13881) (6 weeks ago) <Andrea Selva>
8c79a0067 - Updates license checker after inclusion of et-orbi, fugit and raabro. (#13891) (6 weeks ago) <Andrea Selva>
38fbe5aa0 - Remove pleaserun (via bin/system-install) usage (#12415) (7 weeks ago) <Andres Rodriguez>
d71553e5d - [Doc] update queue.max_bytes and queue.page_capacity (#13833) (7 weeks ago) <kaisecheng>
8edce8217 - Doc: Clarify monitoring settings (#13871) (7 weeks ago) <Karen Metts>
a05936418 - Update CI versions after 8.1.0 (#13830) (7 weeks ago) <Andrea Selva>
0887d7609 - Update pr backporter workflow (#13807) (7 weeks ago) <João Duarte>
edfbabf2f - speed up artifact file listing (#13862) (7 weeks ago) <João Duarte>
008449249 - Fix Logstash cli tools to use the selected JDK under Windows (#13839) (7 weeks ago) <Andrea Selva>
68bacedf4 - Doc: Improve formatting and readability for pipeline ordering (#13084) (7 weeks ago) <Karen Metts>
0369ba208 - artifacts: omit openssl_pkcs8_pure specs from built artifacts (#13715) (8 weeks ago) <Ry Biesemeyer>
e9455ca81 - pipeline-info: increase safety of transforming stats (#13345) (8 weeks ago) <Ry Biesemeyer>
4e226927f - Doc: Correct name for java_home env variable (#13827) (8 weeks ago) <Karen Metts>
f10059ec7 - tools: allow version bump to use local lockfile as baseline (#13686) (8 weeks ago) <Ry Biesemeyer>
a6c0e75b5 - api: avoid 5xx when stats/events not yet populated (#13424) (8 weeks ago) <Ry Biesemeyer>
8bec0e658 - i18n: alias logstash.runner.configuration.* under logstash.agent.configuration (#13244) (8 weeks ago) <Ry Biesemeyer>
022072c43 - geoip-db: support `http_proxy` environment variable (#13410) (8 weeks ago) <Ry Biesemeyer>
11f64f92f - CI: update 8.x resolution after 8.0.1 release (#13831) (8 weeks ago) <Karol Bucek>
c3d2f5750 - Build: avoid doing a redundant bundle install (#13820) (8 weeks ago) <Karol Bucek>
75f72ee78 - Remove CI definition file. (#13822) (8 weeks ago) <Andrea Selva>
21de1c1da - expose shutdown request state of pipeline (#13811) (8 weeks ago) <kaisecheng>
47efdebf3 - update ci release file 7.17.1 (#13818) (8 weeks ago) <kaisecheng>
44fce4091 - action: add docs preview link when docs change. (#13752) (9 weeks ago) <Ry Biesemeyer>
5f43d16df - Refactor: drop useless rubygems patch (#13790) (9 weeks ago) <Karol Bucek>
67fd99b5b - Feat: conservative plugin (dependency) updates by default (#13794) (9 weeks ago) <Karol Bucek>
5cee5ab45 - Fix backport pr workflow conditional trigger (10 weeks ago) <João Duarte>
c07568d81 - Doc: Set up redirects for deleted pages (#13772) (10 weeks ago) <Karen Metts>
ac455ca13 - Set git identity in PR backport action (10 weeks ago) <João Duarte>
db9318137 - Ensure pr backport actions fetches all git history (10 weeks ago) <João Duarte>
75a343e7d - Fix backport PR action trigger condition (10 weeks ago) <João Duarte>
b92ab7bf6 - Add workflow to create backport PRs based off of PR comments (10 weeks ago) <João Duarte>
eec3f22bb - bump jdk to 11.0.14.1+1 (#13687) (10 weeks ago) <João Duarte>
4f32c4fd4 - Refactor: revisit logstash bootstraping bits (#13791) (10 weeks ago) <Karol Bucek>
f1b17be5d - Add reference to java 17 to README.md (#13765) (10 weeks ago) <Rob Bavey>
fbeb63179 - Chore: fetch merge commit automatically with backport dev tool (#13485) (10 weeks ago) <Karol Bucek>
07068ae04 - Deps: pin sinatra due (2.2.0) incompatibilities (#13784) (10 weeks ago) <Karol Bucek>
90a85e1cd - Doc:Update qa readme with BUILD_JAVA_HOME setting info (#11985) (10 weeks ago) <Karen Metts>
b4e213b31 - fix pqrepair log4j setting (#13726) (2 months ago) <kaisecheng>
aceb682f1 - Unpin bundler, fix gem installer tests (#13762) (2 months ago) <Rob Bavey>
e38b25ced - handle fully acked 0 byte PQ pages (#13692) (3 months ago) <kaisecheng>
21adc90dd - Update ci/logstash_releases.json after 8.0.0 release (#13758) (3 months ago) <Andrea Selva>
6313da290 - Doc Forwardport 8.0 release notes to main (#13750) (3 months ago) <Karen Metts>
a15c9771c - Pin bundler to 2.3.6 to fix builder (#13753) (3 months ago) <Rob Bavey>
e9e7838d8 - Docs remove homebrew (#13747) (3 months ago) <Ry Biesemeyer>
04d99b938 - Doc: Update upgrade info for 8.0 in main (#13705) (3 months ago) <Karen Metts>
330b28eb9 - [Test] Fix acceptance tests to deal with Java 8 removal (#13728) (3 months ago) <Rob Bavey>
30b9ad884 - Update the Upgrading Using a Direct Download guide section. (#13684) (3 months ago) <Andrea Selva>
999b6750d - Doc: Remove links to beats 7.x content (#13736) (3 months ago) <Karen Metts>
81dcdc6de - Doc: Replace short link with full link (#13735) (3 months ago) <Karen Metts>
d8f4784d6 - Publish CPU percentage also non Unix systems (#13727) (3 months ago) <Andrea Selva>
7748182a9 - pqcheck pqrepair handle .tmp checkpoint (#13721) (3 months ago) <kaisecheng>
60af28a0f - update google java format dependency (#13700) (3 months ago) <João Duarte>
11e509401 - Update logstash-releases.json after 8.0.0-rc2 (#13722) (3 months ago) <Andrea Selva>
3edef1e48 - Doc: Expand breaking changes (#13693) (3 months ago) <Karen Metts>
df0aee71e - bump version to 8.2.0 (#13720) (3 months ago) <Andres Rodriguez>
7e582e3db - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
6ab6c18ae - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
33419c672 - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
775c353ec - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
259bf4837 - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
dfa3a3c7e - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
ed2891529 - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
22f6e0e28 - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
714db7641 - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
a501da6cf - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
08b9525e2 - Update add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>
05b8ec8cd - Create add_to_projects_beta.yml (3 months ago) <Andres Rodriguez>

=== Logstash Plugin Release Changelogs ===
Computed from "git diff v8.1.3..8.2 *.release"
Changed plugin versions:
logstash-filter-http: 1.3.0 -> 1.4.0
logstash-filter-kv: 4.6.0 -> 4.7.0
logstash-input-beats: 6.2.6 -> 6.3.0
logstash-input-elasticsearch: 4.12.2 -> 4.12.3
logstash-input-http: 3.4.5 -> 3.5.0
logstash-input-http_poller: 5.2.1 -> 5.3.0
logstash-input-sqs: 3.2.0 -> 3.3.0
logstash-integration-kafka: 10.9.0 -> 10.10.0
logstash-mixin-http_client: 7.1.0 -> 7.2.0
logstash-output-http: 5.3.0 -> 5.5.0
---------- GENERATED CONTENT ENDS HERE ------------

==== Plugins

*Http Filter - 1.4.0*

* Feat: added ssl_supported_protocols option https://github.com/logstash-plugins/logstash-filter-http/pull/38[#38]
 

*Kv Filter - 4.7.0*

* Allow attaching multiple tags on failure. The `tag_on_failure` option now also supports an array of strings https://github.com/logstash-plugins/logstash-filter-kv/issues/92[#92]

*Beats Input - 6.3.0*

* Added support for TLSv1.3. https://github.com/logstash-plugins/logstash-input-beats/pull/447[#447]

*Elasticsearch Input - 4.12.3*

* Fix: update Elasticsearch Ruby client to correctly customize 'user-agent' headerhttps://github.com/logstash-plugins/logstash-input-elasticsearch/pull/171[#171]

*Http Input - 3.5.0*

* Feat: TLSv1.3 support https://github.com/logstash-plugins/logstash-input-http/pull/146[#146]

*Http_poller Input - 5.3.0*

* Feat: added ssl_supported_protocols option https://github.com/logstash-plugins/logstash-input-http_poller/pull/133[#133]

*Sqs Input - 3.3.0*

* Feature: Add `additional_settings` option to fine-grain configuration of AWS client https://github.com/logstash-plugins/logstash-input-sqs/pull/61[#61]

*Kafka Integration - 10.10.0*

* Added config setting to enable 'zstd' compression in the Kafka output https://github.com/logstash-plugins/logstash-integration-kafka/pull/112[#112]

*Http_client Mixin - 7.2.0*

* Feat: add `ssl_supported_protocols` option https://github.com/logstash-plugins/logstash-mixin-http_client/pull/40[#40] 

*Http Output - 5.5.0*

* Feat: added `ssl_supported_protocols` option https://github.com/logstash-plugins/logstash-output-http/pull/131[#131]

* Fix retry indefinitely in termination process. This feature requires Logstash 8.1 https://github.com/logstash-plugins/logstash-output-http/pull/129[#129]
* Docs: Add retry policy description https://github.com/logstash-plugins/logstash-output-http/pull/130[#130]

* Introduce retryable unknown exceptions for "connection reset by peer" and "timeout" https://github.com/logstash-plugins/logstash-output-http/pull/127[#127]


[[logstash-8-1-0]]
=== Logstash 8.1.0 Release Notes

[[known-issue-8-1-0]]
==== Known issue

Uninstalling a plugin using `bin/logtash-plugin uninstall` may
result in an error:

```
Gem::LoadError: You have already activated jruby-openssl 0.12.2, but your Gemfile requires jruby-openssl 0.12.1. Prepending `bundle exec` to your command may solve this.
```

Logstash should still run, and other plugin operations, such as `update` and `install`, should work as expected.

NOTE: The `bin/logstash-plugin list` command may fail with the same error after a failed uninstallation.

**Resolution**

A successful plugin `update` will resolve this issue, and allow subsequent `uninstall` and `list` operations to
work without issue.

The `filter-dissect` plugin has recent changes available for update. 
Running `bin/logstash-plugin update logstash-filter-dissect` should mitigate this issue.


==== Logstash core 

No user-facing changes in Logstash core.

==== Plugins

*Http Filter - 1.3.0*

* Feat: support ssl_verification_mode option https://github.com/logstash-plugins/logstash-filter-http/pull/37[#37]

*Kv Filter - 4.6.0*

* Added `allow_empty_values` option https://github.com/logstash-plugins/logstash-filter-kv/pull/72[#72]

*Http_poller Input - 5.2.0*

* Feat: support ssl_verification_mode option https://github.com/logstash-plugins/logstash-input-http_poller/pull/131[#131]

*Sqs Input - 3.2.0*

* Feature: Add `queue_owner_aws_account_id` parameter for cross-account queues https://github.com/logstash-plugins/logstash-input-sqs/pull/60[#60]

*Elastic_enterprise_search Integration - 2.2.1*

* Fix, change implementation of connectivity check method to be compatible with version `v8.0+` of Workplace Search https://github.com/logstash-plugins/logstash-integration-elastic_enterprise_search/pull/16[#16] 

* Feature, switch the connection library to elastic-enterprise-search https://github.com/logstash-plugins/logstash-integration-elastic_enterprise_search/pull/3[#3]
* [DOC] Added required parameters to Workplace Search example snippet and describe little better what's expected in url parameter https://github.com/logstash-plugins/logstash-integration-elastic_enterprise_search/pull/11[#11]

*Http_client Mixin - 7.1.0*

* Feat: add `ssl_verification_mode` https://github.com/logstash-plugins/logstash-mixin-http_client/pull/39[#39] 

*Http Output - 5.3.0*

* Feat: support ssl_verification_mode option https://github.com/logstash-plugins/logstash-output-http/pull/126[#126]

[[logstash-8-0-1]]
=== Logstash 8.0.1 Release Notes

[[notable-8.0.1]]
==== Notable issues fixed

* Fixed monitoring incompatibility on Windows where the CPU metric was not available.
https://github.com/elastic/logstash/pull/13727[#13727]

* Recently, users running `bin/logstash-plugin` to install or update plugins stumbled upon an issue that would prevent
Logstash from starting due a third-party dependency update. The dependency was pinned to an older version.
https://github.com/elastic/logstash/issues/13777[#13777]

* Logstash startup and the `pqrepair`/`pqcheck` tools have been improved to handle corrupted files in case of an
unexpected shutdown. https://github.com/elastic/logstash/pull/13692[#13692] https://github.com/elastic/logstash/pull/13721[#13721]

==== Plugins

*Dissect Filter - 1.2.5*

* Fix bad padding `->` suffix with delimiter https://github.com/logstash-plugins/logstash-filter-dissect/pull/84[#84]

*Elasticsearch Filter - 3.11.1*

*  Fix: hosts => "es_host:port" regression https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/156[#156]

*Beats Input - 6.2.6*

* Update guidance regarding the private key format and encoding https://github.com/logstash-plugins/logstash-input-beats/pull/445[#445]

*Dead_letter_queue Input - 1.1.10*

* Fix, avoid Logstash crash on shutdown if DLQ files weren't created https://github.com/logstash-plugins/logstash-input-dead_letter_queue/pull/33[#33]
* Fix `@metadata` get overwritten by reestablishing metadata that stored in DLQ https://github.com/logstash-plugins/logstash-input-dead_letter_queue/pull/34[#34]

*Tcp Input - 6.2.7*

* Build: skip shadowing jar dependencies https://github.com/logstash-plugins/logstash-input-tcp/pull/187[#187]
** plugin no longer shadows dependencies into its *logstash-input-tcp.jar*
** log4j-api is now a provided dependency and is no longer packaged with the plugin

*Jdbc Integration - 5.2.3*

* Performance: avoid contention on scheduler execution https://github.com/logstash-plugins/logstash-integration-jdbc/pull/103[#103]

*Tcp Output - 6.0.1*

* Fixed logging fail retry to stdout https://github.com/logstash-plugins/logstash-output-tcp/pull/43[#43]
* Fixed to use `reconnect_interval` when establish a connection

[[logstash-8-0-0]]
=== Logstash 8.0.0 Release Notes

The following list are changes in 8.0.0 as compared to 7.17.0, and combines release notes from the 8.0.0-alpha1, -alpha2, -beta1, -rc1 and -rc2 releases.

[[breaking-8.0.0]]
==== Breaking changes
* Many plugins can now be run in a mode that avoids implicit conflict with the Elastic Common Schema (ECS).
  This mode is controlled individually with each plugin’s ecs_compatibility option, which defaults to the value of the Logstash pipeline.ecs_compatibility setting.
  In Logstash 8, this compatibility mode will be on-by-default for all pipelines.
  If you wish to lock in a pipeline’s behavior from Logstash 7.x before upgrading to Logstash 8,
  you can set `pipeline.ecs_compatibility: disabled` to its definition in `pipelines.yml` (or globally in `logstash.yml`).
* Starting from Logstash 8.0, the minimum required version of Java to run Logstash is Java 11.
  By default, Logstash will run with the bundled JDK, which has been verified to work with each specific version of Logstash,
  and generally provides the best performance and reliability.
* Support for using `JAVA_HOME` to override the path to the JDK that Logstash runs with has been removed for this release.
  In the `8.x` release, users should set the value of `LS_JAVA_HOME` to the path of their preferred JDK if they
  wish to use a version other than the bundled JDK. The value of `JAVA_HOME` will be ignored.
* The Java Execution Engine has been the default engine since Logstash 7.0, and works with plugins written in either Ruby or Java.
  Removal of the Ruby Execution Engine will not affect the ability to run existing pipelines. https://github.com/elastic/logstash/pull/12517[#12517]
* We have added support for UTF-16 and other multi-byte-character when reading log files. https://github.com/elastic/logstash/pull/9702[#9702]
* Setting `config.field_reference.parser` has been removed.
  The Field Reference parser interprets references to fields in your pipelines and plugins.
  Its behavior was configurable in 6.x, and since 7.0 allowed only a single option: `strict`.
  8.0 no longer recognizes the setting, but maintains the same behavior as the `strict` setting.
  {ls} rejects ambiguous and illegal inputs as standard behavior. https://github.com/elastic/logstash/pull/12466[#12466]

For a more detailed view of these changes please check <<breaking-8.0>>.

[[features-8.0.0]]
==== New features and enhancements
* As processing times speed up, millisecond granularity is not always enough. Inbound data increasingly has sub-millisecond granularity timestamps.
  The pull request https://github.com/elastic/logstash/pull/12797[#12797] allows the internal mechanisms of
  Logstash that hold moment-in-time data - such as the Logstash Event, the Persistent Queue, the Dead Letter Queue and JSON encoding/decoding - to have nanosecond granularity.
* We have added another flag to the Benchmark CLI to allow passing a data file with previously captured data to the custom test case.
  This feature allows users to run the Benchmark CLI in a custom test case with a custom config and a custom dataset. https://github.com/elastic/logstash/pull/12437[#12437]

==== Plugins

Logstash 8.0.0 includes the same versions of all bundled plugins as Logstash 7.17.0.
If you upgrade to 7.17 before upgrading to 8.0 (as recommended), you won't see any changes to plugin versions.

*Clone Filter - 4.2.0*

* Added support for ECS v8 as alias for ECS v1 https://github.com/logstash-plugins/logstash-filter-clone/pull/27[#27]

*Geoip Filter - 7.2.11*

* Improved compatibility with the Elastic Common Schema https://github.com/logstash-plugins/logstash-filter-geoip/pull/206[#206]
** Added support for ECS's composite `region_iso_code` (`US-WA`), which _replaces_ the non-ECS `region_code` (`WA`) as a default field with City databases.
To get the stand-alone `region_code` in ECS mode, you must include it in the `fields` directive
** [DOC] Improve ECS-related documentation
* [DOC] Air-gapped environment requires both ASN and City databases https://github.com/logstash-plugins/logstash-filter-geoip/pull/204[#204]

*Http Filter - 1.2.1*

* Fix: do not set content-type if provided by user https://github.com/logstash-plugins/logstash-filter-http/pull/36[#36]
* Feat: improve ECS compatibility https://github.com/logstash-plugins/logstash-filter-http/pull/35[#35]
* Add support for PUT requests https://github.com/logstash-plugins/logstash-filter-http/pull/34[#34]

*Ruby Filter - 3.1.8*

* [DOC] Added doc to describe the option `tag_with_exception_message`https://github.com/logstash-plugins/logstash-filter-ruby/pull/62[#62]
* Fix SyntaxError handling so other pipelines can shut down gracefully https://github.com/logstash-plugins/logstash-filter-ruby/pull/64[#64]

*Useragent Filter - 3.3.3*

* Docs: mention added fields in 3.3 with a note https://github.com/logstash-plugins/logstash-filter-useragent/pull/78[#78]

*Exec Input - 3.4.0*

* Feat: adjust fields for ECS compatibility https://github.com/logstash-plugins/logstash-input-exec/pull/28[#28]
* Plugin will no longer override fields if they exist in the decoded payload (It no longer sets the `host` field if decoded from the command's output)

*Gelf Input - 3.3.1*

* Fix: safely coerce the value of `_@timestamp` to avoid crashing the plugin https://github.com/logstash-plugins/logstash-input-gelf/pull/67[#67]

*Generator Input - 3.1.0*

* Feat: adjusted fields for ECS compatibility https://github.com/logstash-plugins/logstash-input-generator/pull/22[#22]
* Fix: do not override the host field if it's present in the generator line (after decoding)
* Fix: codec flushing when closing input

*Imap Input - 3.2.0*

* Feat: ECS compatibility https://github.com/logstash-plugins/logstash-input-imap/pull/55[#55]
* added (optional) `headers_target` configuration option
* added (optional) `attachments_target` configuration option
* Fix: plugin should not close `$stdin`, while being stopped

*Jms Input - 3.2.1*

* Fix: improve compatibility with MessageConsumer implementations https://github.com/logstash-plugins/logstash-input-jms/pull/51[#51],
such as IBM MQ.
* Test: Fix test failures due to ECS compatibility default changes in `8.x` of logstash https://github.com/logstash-plugins/logstash-input-jms/pull/53[#53]
* Feat: event_factory support + targets to aid ECS https://github.com/logstash-plugins/logstash-input-jms/pull/49[#49]
* Fix: when configured to add JMS headers to the event, headers whose value is not set no longer result in nil entries on the event
* Fix: when adding the `jms_reply_to` header to an event, a string representation is set instead of an opaque object.

*Pipe Input - 3.1.0*

*  Feat: adjust fields for ECS compatibility https://github.com/logstash-plugins/logstash-input-pipe/pull/19[#19]

*S3 Input - 3.8.3*

* Fix missing `metadata` and `type` of the last event https://github.com/logstash-plugins/logstash-input-s3/pull/223[#223]
* Refactor: read sincedb time once per bucket listing https://github.com/logstash-plugins/logstash-input-s3/pull/233[#233]

*Snmp Input - 1.3.1*

* Refactor: handle no response(s) wout error logging https://github.com/logstash-plugins/logstash-input-snmp/pull/105[#105]
* Feat: ECS compliance + optional target https://github.com/logstash-plugins/logstash-input-snmp/pull/99[#99]
* Internal: update to Gradle 7 https://github.com/logstash-plugins/logstash-input-snmp/pull/102[#102]

*Snmptrap Input - 3.1.0*

* Feat: ecs_compatiblity support + (optional) target https://github.com/logstash-plugins/logstash-input-snmptrap/pull/37[#37]

*Syslog Input - 3.6.0*

* Add support for ECS v8 as alias to v1 implementation https://github.com/logstash-plugins/logstash-input-syslog/pull/68[#68]

*Twitter Input - 4.1.0*

* Feat: optional target + ecs_compatibility https://github.com/logstash-plugins/logstash-input-twitter/pull/72[#72]

*Unix Input - 3.1.1*

* Fix: unable to stop plugin (on LS 6.x) https://github.com/logstash-plugins/logstash-input-unix/pull/29[#29]
* Refactor: plugin internals got reviewed for `data_timeout => ...` to work reliably
* Feat: adjust fields for ECS compatibility https://github.com/logstash-plugins/logstash-input-unix/pull/28[#28]

*Jdbc Integration - 5.2.2*

* Feat: name scheduler threads + redirect error logging https://github.com/logstash-plugins/logstash-integration-jdbc/pull/102[#102]
* Refactor: isolate paginated normal statement algorithm in a separate handler https://github.com/logstash-plugins/logstash-integration-jdbc/pull/101[#101]
* Added `jdbc_paging_mode` option to choose if use `explicit` pagination in statements and avoid the initial count
query or use `auto` to delegate to the underlying library https://github.com/logstash-plugins/logstash-integration-jdbc/pull/95[#95]
* Several improvements to Java driver loading
** Refactor: to explicit Java (driver) class name loading https://github.com/logstash-plugins/logstash-integration-jdbc/pull/96[#96].
The change is expected to provide a more robust fix for the driver loading issue https://github.com/logstash-plugins/logstash-integration-jdbc/issues/83[#83].

    NOTE: A fatal driver error will no longer keep reloading the pipeline and now leads to a system exit.

** Fix: regression due returning the Java driver class https://github.com/logstash-plugins/logstash-integration-jdbc/pull/98[#98]

*Kafka Integration - 10.9.0*

* Refactor: leverage codec when using schema registry
Previously using `schema_registry_url` parsed the payload as JSON even if `codec => 'plain'` was explicitly set, this is no longer the case.
https://github.com/logstash-plugins/logstash-integration-kafka/pull/106[#106]

*Cloudwatch Output - 3.0.10*

* Fix: an old undefined method error which would surface with load (as queue fills up)
* Deps: unpin rufus scheduler https://github.com/logstash-plugins/logstash-output-cloudwatch/pull/20[#20]

*Elasticsearch Output - 11.4.1*

* Feat: upgrade manticore (http-client) library https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1063[#1063]
** the underlying changes include latest HttpClient (4.5.13)
** resolves an old issue with `ssl_certificate_verification => false` still doing some verification logic
* Updates ECS templates https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1062[#1062]
** Updates v1 templates to 1.12.1 for use with Elasticsearch 7.x and 8.x
** Updates BETA preview of ECS v8 templates for Elasticsearch 7.x and 8.x
* Feat: add support for 'traces' data stream type https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1057[#1057]
* Refactor: review manticore error handling/logging, logging originating cause in case of connection related error when debug level is enabled.
Java causes on connection related exceptions will now be extra logged when plugin is logging at debug level
https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1029[#1029]
* ECS-related fixes https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1046[#1046]
** Data Streams requirement on ECS is properly enforced when running on Logstash 8, and warned about when running on Logstash 7.
** ECS Compatibility v8 can now be selected

*Core Patterns - 4.3.2*

- Fix: typo in `BIN9_QUERYLOG` pattern (in ECS mode) https://github.com/logstash-plugins/logstash-patterns-core/pull/307[#307]


[[logstash-8-0-0-rc2]]
=== Logstash 8.0.0-rc2 Release Notes

[[notable-8.0.0-rc2]]
==== Notable issues fixed
* Fixed long-standing issue in which the `events.out` count incorrectly included events that had been dropped with the drop filter.
Now the total out event count includes only events that reach the out stage. https://github.com/elastic/logstash/pull/13593[#13593]
* Reduced scope and impact of a memory leak that can be caused by using UUIDs or other high-cardinality field names https://github.com/elastic/logstash/pull/13642[#13642]
* Fixed an issue with the Azure input plugin that caused Logstash to crash when the input was used in a pipeline. https://github.com/elastic/logstash/pull/13603[#13603]

==== Plugin releases
Plugins align with release 7.17.0


[[logstash-8-0-0-rc1]]
=== Logstash 8.0.0-rc1 Release Notes

==== Breaking changes

[[rn-ecs-compatibility]]
===== ECS compatibility
Many plugins can now be run in a mode that avoids implicit conflict with the Elastic Common Schema (ECS). This mode is controlled individually with each plugin’s ecs_compatibility option, which defaults to the value of the Logstash pipeline.ecs_compatibility setting. In Logstash 8, this compatibility mode will be on-by-default for all pipelines.

If you wish to lock in a pipeline’s behavior from Logstash 7.x before upgrading to Logstash 8, you can set pipeline.ecs_compatibility: disabled to its definition in pipelines.yml (or globally in logstash.yml).

==== New features and enhancements

Logstash Docker images are now based on Ubuntu 20.04.

==== Plugin releases
Plugins align with release 7.16.2


[[logstash-8-0-0-beta1]]
=== Logstash 8.0.0-beta1 Release Notes

==== Breaking changes

[[rn-java-11-minimum]]
===== Java 11 minimum
Starting from Logstash 8.0, the minimum required version of Java to run Logstash is Java 11. By default, Logstash will
run with the bundled JDK, which has been verified to work with each specific version of Logstash, and generally
provides the best performance and reliability.

See <<breaking-changes>> for a preview of additional breaking changes coming your way. 

==== New features and enhancements

[[rn-nanosecond-precision]]
===== Nanosecond precision
As processing times speed up, millisecond granularity is not always enough. Inbound data increasingly has sub-millisecond granularity timestamps.
The pull request https://github.com/elastic/logstash/pull/12797[#12797] allows the internal mechanisms of Logstash that hold moment-in-time data - such as the Logstash Event, the Persistent Queue, the Dead Letter Queue and JSON encoding/decoding - to have nanosecond granularity.

Timestamp precision is limited to the JVM and Platform's available granularity, which in many cases is microseconds.

This change also grants users access to https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns[Java time's improved formatters], which include support fort ISO quarters, week-of-month, and a variety of timezone/offset-related format substitutions. For example:

[source,json]
--------------------------------------------------------------------------------
filter {
  mutate {
    add_field => {"nanos" => "Nanos: %{{n}}" }
  }
}
--------------------------------------------------------------------------------

Results in the following event:

[source,json]
--------------------------------------------------------------------------------
{
    "@timestamp" => 2021-10-31T22:32:34.747968Z,
          "host" => "logstash.lan",
         "nanos" => "Nanos: 747968000",
       "message" => "test",
          "type" => "stdin",
      "@version" => "1"
}
--------------------------------------------------------------------------------

==== Plugin releases
Plugins align with release 7.15.1


[[logstash-8-0-0-alpha2]]
=== Logstash 8.0.0-alpha2 Release Notes

==== Breaking changes

[[java-home-breaking-change]]
===== Removed support for JAVA_HOME
Support for using `JAVA_HOME` to override the path to the JDK that Logstash runs with has been removed for this release.
In the `8.x` release, users should set the value of `LS_JAVA_HOME` to the path of their preferred JDK if they
wish to use a version other than the bundled JDK. The value of `JAVA_HOME` will be ignored.

==== Plugin releases
Plugins align with release 7.15.0

[[logstash-8-0-0-alpha1]]
=== Logstash 8.0.0-alpha1 Release Notes

==== Breaking changes

[[ruby-engine]]
===== Ruby Execution Engine removed
The Java Execution Engine has been the default engine since Logstash 7.0, and works with plugins written in either Ruby or Java.
Removal of the Ruby Execution Engine will not affect the ability to run existing pipelines. https://github.com/elastic/logstash/pull/12517[#12517]

[[utf-16]]
===== Support for UTF-16
We have added support for UTF-16 and other multi-byte-character when reading log files. https://github.com/elastic/logstash/pull/9702[#9702]

[[field-ref-parser]]
===== Field Reference parser removed
The Field Reference parser interprets references to fields in your pipelines and
plugins. It was configurable in 7.x, with the default set to strict to reject
inputs that are ambiguous or illegal. Configurability is removed in 8.0. Now
{ls} rejects ambiguous and illegal inputs as standard behavior. https://github.com/elastic/logstash/pull/12466[#12466]

==== New features and enhancements

**Option to pass custom data to the benchmark CLI**

We have added another flag to the Benchmark CLI to allow passing a data file with previously captured data to the custom test case.
This feature allows users to run the Benchmark CLI in a custom test case with a custom config and a custom dataset. https://github.com/elastic/logstash/pull/12437[#12437]

==== Plugin releases
Plugins align with release 7.14.0