[[releasenotes]]
== Release Notes

* <<logstash-9-0-0-beta1,Logstash 9.0.0-beta1>>

[[logstash-9-0-0-beta1]]
=== Logstash 9.0.0-beta1 Release Notes

==== Breaking changes
* Default buffer type to 'heap' for 9.0 https://github.com/elastic/logstash/pull/16500[#16500]

==== New features and enhancements
* Health report api https://github.com/elastic/logstash/pull/16520[#16520]
* Plugin manager: add `--level=[major|minor|patch]` (default: `minor`) (#16899) (8 days ago) <Ry Biesemeyer>

==== Plugin releases

---------- GENERATED CONTENT STARTS HERE ------------
=== Logstash Pull Requests with label v9.0.0

* Release notes for 8.15.2 https://github.com/elastic/logstash/pull/16471[#16471]
* Backport PR #16471 to main: Release notes for 8.15.2 https://github.com/elastic/logstash/pull/16486[#16486]
* Fix jdk21 warnings https://github.com/elastic/logstash/pull/16496[#16496]
* Keeps global settings aligned across entities used in the test for StatsEventFactory https://github.com/elastic/logstash/pull/16540[#16540]
* Anchor the `-java` match pattern at the end of the string https://github.com/elastic/logstash/pull/16626[#16626]
* For custom java plugins, set the platform = 'java' https://github.com/elastic/logstash/pull/16628[#16628]
* PipelineBusV2 deadlock proofing https://github.com/elastic/logstash/pull/16671[#16671]
* Fix BufferedTokenizer to properly resume after a buffer full condition respecting the encoding of the input string https://github.com/elastic/logstash/pull/16968[#16968]

=== Logstash Commits between 9.0 and 8.17.1

97cadfa45 - Backport PR #16968 to 9.0: Fix BufferedTokenizer to properly resume after a buffer full condition respecting the encoding of the input string (#16968) (#17018) (9 hours ago) <github-actions[bot]>
3d66b67ba - Update major plugin versions in gemfile lock (#16996) (6 days ago) <github-actions[bot]>
51ab5d85d - Upgrade jdk to 21.0.6+7 (#16932) (6 days ago) <João Duarte>
7378b85f4 - Adding elastic_integration upgrade guidelines. (#16979) (7 days ago) <Mashhur>
2be481211 - add openssl command to wolfi image (#16966) (9 days ago) <kaisecheng>
c8a656687 - fix user and password detection from environment's uri (#16955) (9 days ago) <João Duarte>
03b11e982 - Reimplement LogStash::String setting in Java (#16576) (12 days ago) <Andrea Selva>
dc740b46c - [doc] fix the necessary privileges of central pipeline management (#16902) (13 days ago) <kaisecheng>
52b7fb0ae - fix jars installer for new maven and pin psych to 5.2.2 (#16919) (2 weeks ago) <João Duarte>
92d721014 - Doc: WPS integration (#16910) (3 weeks ago) <Karen Metts>
cd729b768 - Add %{{TIME_NOW}} pattern for sprintf (#16906) (3 weeks ago) <kaisecheng>
348f1627a - remove pipeline bus v1 (#16895) (4 weeks ago) <Ry Biesemeyer>
ae8ad28aa - Add beats and elastic-agent SSL changes to 9.0 breaking change doc. (#16742) (4 weeks ago) <Mashhur>
db34116c4 - Doc: Environment variables cannot be in config.string comments. (#16689) (4 weeks ago) <Mashhur>
a21510103 - Validate the size limit in BufferedTokenizer. (#16882) (4 weeks ago) <Mashhur>
d978e07f2 - Logstash API spec - first pass (#16546) (4 weeks ago) <Karen Metts>
47d04d06b - Initialize flow metrics if pipeline metric.collect params is enabled. (#16881) (4 weeks ago) <Mashhur>
16392908e - jackson stream read constraints: code-based defaults (#16854) (4 weeks ago) <Ry Biesemeyer>
dae7fd93d - remove enterprise search from default distribution (#16818) (4 weeks ago) <kaisecheng>
274c212d9 - Ensure plugin config marked :deprecated logs to deprecation logger (#16833) (4 weeks ago) <Cas Donoghue>
e2b322e8c - Doc: Message Logstash module deprecations and removal (#16840) (4 weeks ago) <Karen Metts>
ef36df6b8 - Respect environment variables in jvm.options (#16834) (5 weeks ago) <kaisecheng>
de6a6c5b0 - Add pipeline metrics to Node Stats API (#16839) (5 weeks ago) <kaisecheng>
531f79503 - Ssl standardization breaking changes docs (#16844) (5 weeks ago) <Cas Donoghue>
cc608eb88 - Apply Jackson stream read constraints defaults at runtime (#16832) (5 weeks ago) <Cas Donoghue>
01c8e8bb5 - Avoid lock when ecs_compatibility is explicitly specified (#16786) (7 weeks ago) <Ry Biesemeyer>
ae75636e1 - update ironbank image to ubi9/9.5 (#16819) (7 weeks ago) <kaisecheng>
05789744d - Remove the Arcsight module and the modules framework (#16794) (7 weeks ago) <kaisecheng>
03ddf1289 - [doc] use UBI8 as base image (#16812) (7 weeks ago) <kaisecheng>
e1f4e772d - Doc: Update security docs to replace obsolete cacert setting (#16798) (7 weeks ago) <Karen Metts>
e36cacedc - ensure inputSize state value is reset during buftok.flush (#16760) (8 weeks ago) <João Duarte>
202d07cbb - ensure jackson overrides are available to static initializers (#16719) (9 weeks ago) <Ry Biesemeyer>
ab1976952 - Pin `date` dependency to `3.3.3` (#16755) (9 weeks ago) <Rob Bavey>
e3265d93e - Pin `jar-dependencies` to `0.4.1` (#16747) (9 weeks ago) <Rob Bavey>
d913e2ae3 - Docs: Troubleshooting update for JDK bug handling cgroups v1 (#16721) (2 months ago) <mmahacek>
615545027 - Doc: Roll 6.3 breaking changes under 6.0 series (#16706) (3 months ago) <Karen Metts>
eb7e1253e - Revert "Bugfix for BufferedTokenizer to completely consume lines in case of lines bigger then sizeLimit (#16482)" (#16715) (3 months ago) <Cas Donoghue>
0dd64a9d6 - PipelineBusV2 deadlock proofing (#16671) (#16682) (3 months ago) <github-actions[bot]>
d4fb06e49 - Introduce a new flag to explicitly permit legacy monitoring (#16586) (3 months ago) <Andrea Selva>
5826c6f90 - Use UBI as base image (#16599) (3 months ago) <kaisecheng>
046ea1f5a - For custom java plugins, set the platform = 'java'. (#16628) (3 months ago) <Nicole Albee>
5847d7733 - skip `allow_superuser` in Windows OS (#16629) (3 months ago) <kaisecheng>
113585d4a - Anchor the `-java` match pattern at the end of the string. (#16626) (3 months ago) <Nicole Albee>
6703aec47 - bump jruby to 9.4.9.0 (#16634) (3 months ago) <João Duarte>
849f43103 - fix Windows java not found log (#16633) (3 months ago) <kaisecheng>
852149be2 - Update JDK to latest in versions.yml (#16627) (3 months ago) <Andrea Selva>
00da72378 - add boostrap to docker build to fix missing jars (#16622) (3 months ago) <kaisecheng>
db59cd0fb - set `allow_superuser` to false as default (#16558) (3 months ago) <kaisecheng>
5d523aa5c - Fix bad reference to a variable (#16615) (3 months ago) <Andrea Selva>
ca19f0029 - make max inflight warning global to all pipelines (#16597) (3 months ago) <João Duarte>
566bdf66f - remove http.* settings (#16552) (4 months ago) <kaisecheng>
467ab3f44 - Enable log.format.json.fix_duplicate_message_fields by default (#16578) (4 months ago) <kaisecheng>
3f0ad12d0 - add http.* deprecation log (#16538) (4 months ago) <kaisecheng>
b6f16c8b8 - Adds a JMH benchmark to test BufferedTokenizerExt class (#16564) (4 months ago) <Andrea Selva>
85493ce86 - Bugfix for BufferedTokenizer to completely consume lines in case of lines bigger then sizeLimit (#16482) (4 months ago) <Andrea Selva>
ab77d36da - ensure minitar 1.x is used instead of 0.x (#16565) (4 months ago) <João Duarte>
63706c1a3 - Marked ArcSight Module as deprecated in documentation. (#16553) (4 months ago) <Andrea Selva>
cb3b7c01d - Remove event_api.tags.illegal for v9 (#16461) (4 months ago) <kaisecheng>
b571e8f3e - remove deprecated modules netflow, fb_apache and azure (#16514) (4 months ago) <kaisecheng>
8cd0fa876 - refactor log for event_api.tags.illegal (#16545) (4 months ago) <kaisecheng>
6064587bc - Keeps global settings aligned across entities used in the test for StatsEventFactory (4 months ago) <Andrea Selva>
a931b2cde - Flow worker utilization probe (#16532) (4 months ago) <Ry Biesemeyer>
065769636 - health: add `logstash.forceApiStatus: green` escape hatch (#16535) (4 months ago) <Ry Biesemeyer>
a4eddb8a2 - add deprecation log for `--event_api.tags.illegal` (#16507) (4 months ago) <kaisecheng>
3480c32b6 - install jdk 11 in agent for snyk 7.17 scanning (#16510) (4 months ago) <João Duarte>
5d4825f00 - Avoid to access Java DeprecatedAlias value other than Ruby's one (#16506) (4 months ago) <Andrea Selva>
e84fb458c - Improve pipeline bootstrap error logs (#16495) (4 months ago) <Edmo Vamerlatti Costa>
07c01f823 - Don't use an older JRuby with oraclelinux-7 (#16499) (4 months ago) <Dimitrios Liappis>
4e49adc6f - Fix jdk21 warnings (#16496) (4 months ago) <Andrea Selva>
b69d993d7 - DLQ-ing events that trigger an conditional evaluation error. (#16423) (4 months ago) <Andrea Selva>
61de60fe2 - [Spacetime] Reimplement config Setting classe in java (#15679) (4 months ago) <Andrea Selva>
8368c0036 - Change LogStash::Util::SubstitutionVariables#replace_placeholders refine argument to optional (#16485) (4 months ago) <Edmo Vamerlatti Costa>
51cca7320 - bump .ruby_version to jruby-9.4.8.0 (#16477) (4 months ago) <João Duarte>
0ef4c7da3 - [ci] fix wrong queue type in benchmark marathon (#16465) (5 months ago) <kaisecheng>
4e82655cd - remove ingest-converter (#16453) (5 months ago) <kaisecheng>
1ec37b7c4 - Drop JDK 11 support (#16443) (5 months ago) <Andrea Selva>
69f0fa54c - use gnu tar compatible minitar to generate tar artifact (#16432) (5 months ago) <João Duarte>
bb7ecc203 - Fix ConditionalEvaluationError to do not include the event that errored in its serialiaxed form, because it's not expected that this class is ever serialized. (#16429) (5 months ago) <Andrea Selva>

---------- GENERATED CONTENT ENDS HERE ------------

==== Plugins

*elastic_integration Filter - 9.0.0*

* 9.0.0 prerelease https://github.com/elastic/logstash-filter-elastic_integration/pull/265[#265]

*Elasticsearch Filter - 4.1.0*

* Added support for custom headers https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/188[#188]

* SSL settings that were marked deprecated in version `3.15.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `ca_file`, which should be replaced by `ssl_certificate_authorities`
* `keystore`, which should be replaced by `ssl_keystore_path`
* `keystore_password`, which should be replaced by `ssl_keystore_password`
* `keystore_type`, which should be replaced by `ssl_keystore_password`
*  `ssl`, which should be replaced by `ssl_enabled`
* https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/183[#183]

*Http Filter - 2.0.0*

* SSL settings that were marked deprecated in version `1.6.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `cacert`, which should be replaced by `ssl_certificate_authorities`
* `client_cert`, which should be replaced by `ssl_certificate`
* `client_key`, which should be replaced by `ssl_key`
* `keystore`, which should be replaced by `ssl_keystore_path`
* `keystore_password`, which should be replaced by `ssl_keystore_password`
* `keystore_type`, which should be replaced by `ssl_keystore_type`
* `truststore`, which should be replaced by `ssl_truststore_path>`
* `truststore_password`, which should be replaced by `ssl_truststore_password`
* `truststore_type`, which should be replaced by `ssl_truststore_type`
* https://github.com/logstash-plugins/logstash-filter-http/pull/54[#54]

*Beats Input - 7.0.1*

* Name netty threads according to their purpose and the plugin id https://github.com/logstash-plugins/logstash-input-beats/pull/511[#511]

* Remove deprecated SSL settings
* SSL settings that were marked deprecated in version `6.6.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `cipher_suites`, replaced by `ssl_cipher_suites`
* `ssl`, replaced by `ssl_enabled`
* `ssl_peer_metadata`, replaced by `enrich`
* `ssl_verify_mode`, replaced by `ssl_client_authentication`
* `tls_max_version`, replaced by `ssl_supported_protocols`
* `tls_min_version`, replaced by `ssl_supported_protocols`
* https://github.com/logstash-plugins/logstash-input-beats/pull/508[#508]

*Elastic_serverless_forwarder Input - 2.0.0*

* SSL settings that were marked deprecated in version `0.1.3` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `ssl`, which should be replaced by `ssl_enabled`
* https://github.com/logstash-plugins/logstash-input-elastic_serverless_forwarder/pull/11[#11]

* Promote from technical preview to GA https://github.com/logstash-plugins/logstash-input-elastic_serverless_forwarder/pull/10[#10]

*Elasticsearch Input - 5.0.0*

* SSL settings that were marked deprecated in version `4.17.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `ssl`, which should bre replaced by `ssl_enabled`
* `ca_file`, which should bre replaced by `ssl_certificate_authorities`
* `ssl_certificate_verification`, which should bre replaced by `ssl_verification_mode`
* https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/213[#213]

*Http Input - 4.1.0*

* add improved proactive rate-limiting, rejecting new requests when queue has been actively blocking for more than 10 seconds https://github.com/logstash-plugins/logstash-input-http/pull/186[#186]
* This is a forward-port of functionality also introduced to the 3.x series in v3.10.0 

* SSL settings that were marked deprecated in version `3.7.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `tls_min_version`, which should be replaced by `ssl_supported_protocols`
* `tls_max_version`, which should be replaced by `ssl_supported_protocols`
* `cipher_suites`, which should bre replaced by `ssl_cipher_suites`
* `ssl`, which should bre replaced by `ssl_enabled`
* `keystore`, which should bre replaced by `ssl_keystore_path`
* `keystore_password`, which should bre replaced by `ssl_keystore_password`
* `ssl_verify_mode`, which should bre replaced by `ssl_client_authentication`
* `verify_mode`, which should bre replaced by `ssl_client_authentication`
* https://github.com/logstash-plugins/logstash-input-http/pull/182[#182]

* add improved proactive rate-limiting, rejecting new requests when queue has been actively blocking for more than 10 seconds https://github.com/logstash-plugins/logstash-input-http/pull/179[#179]

*Http_poller Input - 6.0.0*

* SSL settings that were marked deprecated in version `5.6.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `cacert`, which should be replaced by `ssl_certificate_authorities`
* `client_cert`, which should be replaced by `ssl_certificate`
* `client_key`, which should be replaced by `ssl_key`
* `keystore`, which should be replaced by `ssl_keystore_path`
* `keystore_password`, which should be replaced by `ssl_keystore_password`
* `keystore_type`, which should be replaced by `ssl_keystore_password`
* `truststore`, which should be replaced by `ssl_truststore_path>`
* `truststore_password`, which should be replaced by `ssl_truststore_password`
* `truststore_type`, which should be replaced by `ssl_truststore_type`
* https://github.com/logstash-plugins/logstash-input-http_poller/pull/149[#149]

*Tcp Input - 7.0.0*

* SSL settings that were marked deprecated in version `6.4.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `ssl_cert`, which should be replaced by `ssl_certificate`
* `ssl_enable`, which should be replaced by `ssl_enabled`
* `ssl_verify`, which should be replaced by `ssl_client_authentication` when `mode` is `server` or `ssl_verification_mode`when mode is `client`
* [228](https://github.com/logstash-plugins/logstash-input-tcp/pull/228)

*Elastic_enterprise_search Integration - 3.0.1*

*Kafka Integration - 11.6.0*

* Support additional `oauth` and `sasl` configuration options for configuring kafka client https://github.com/logstash-plugins/logstash-integration-kafka/pull/189[#189]

*Snmp Integration - 4.0.6*

* [DOC] Fix typo in snmptrap migration section https://github.com/logstash-plugins/logstash-integration-snmp/pull/74[#74]

*Elasticsearch Output - 12.0.2*

* Properly handle http code 413 (Payload Too Large) https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1199[#1199]

* Remove irrelevant log warning about elastic stack version https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1200[#1200]

* SSL settings that were marked deprecated in version `11.14.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `cacert`, which should be replaced by `ssl_certificate_authorities`
* `keystore`, which should be replaced by `ssl_keystore_path`
* `keystore_password`, which should be replaced by `ssl_keystore_password`
* `ssl`, which should be replaced by `ssl_enabled`
* `ssl_certificate_verification`, which should be replaced by `ssl_verification_mode`
* `truststore`, which should be replaced by `ssl_truststore_path`
* `truststore_password`, which should be replaced by `ssl_truststore_password`
* https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1197[#1197]

*Http Output - 6.0.0*

* SSL settings that were marked deprecated in version `5.6.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:   
* `cacert`, which should be replaced by `ssl_certificate_authorities`
* `client_cert`, which should be replaced by `ssl_certificate`
* `client_key`, which should be replaced by `ssl_key`
* `keystore`, which should be replaced by `ssl_keystore_path`
* `keystore_password`, which should be replaced by `ssl_keystore_password`
* `keystore_type`, which should be replaced by `ssl_keystore_password`
* `truststore`, which should be replaced by `ssl_truststore_path>`
* `truststore_password`, which should be replaced by `ssl_truststore_password`
* `truststore_type`, which should be replaced by `ssl_truststore_type`
* https://github.com/logstash-plugins/logstash-output-http/pull/147[#147]

*Tcp Output - 7.0.0*

* SSL settings that were marked deprecated in version `6.2.0` are now marked obsolete, and will prevent the plugin from starting.
* These settings are:
* `ssl_cert`, which should be replaced by `ssl_certificate`
* `ssl_cacert`, which should be replaced by `ssl_certificate_authorities`
* `ssl_enable`, which should be replaced by `ssl_enabled`
* `ssl_verify`, which should be replaced by `ssl_client_authentication` when `mode` is `server` or `ssl_verification_mode`when mode is `client`
* [58](https://github.com/logstash-plugins/logstash-output-tcp/pull/58)
