[[releasenotes]]
== Release Notes

This section summarizes the changes in the following releases:

* <<logstash-7-2-0,Logstash 7.2.0>>
* <<logstash-7-1-1,Logstash 7.1.1>>
* <<logstash-7-1-0,Logstash 7.1.0>>
* <<logstash-7-0-1,Logstash 7.0.1>>
* <<logstash-7-0-0,Logstash 7.0.0>>
* <<logstash-7-0-0-rc2,Logstash 7.0.0-rc2>>
* <<logstash-7-0-0-rc1,Logstash 7.0.0-rc1>>
* <<logstash-7-0-0-beta1,Logstash 7.0.0-beta1>>
* <<logstash-7-0-0-alpha2,Logstash 7.0.0-alpha2>>
* <<logstash-7-0-0-alpha1,Logstash 7.0.0-alpha1>>

[[logstash-7-2-0]]
=== Logstash 7.2.0 Release Notes

---------- DELETE FROM HERE ------------
=== Logstash Pull Requests with label v7.2.0

* Native support for Java plugins (GA) https://github.com/elastic/logstash/pull/10620[#10620]
* Clarify behavior of ensure_delivery flag https://github.com/elastic/logstash/pull/10754[#10754]
* Include G1 in JVM heap metrics https://github.com/elastic/logstash/pull/10784[#10784]
* Provide DLQ writer interface to Java plugins https://github.com/elastic/logstash/pull/10790[#10790]
* Default stack trace size for hot threads to 50 and make it configurable https://github.com/elastic/logstash/pull/10793[#10793]
* Expose Metrics API to Java plugins (#10761) https://github.com/elastic/logstash/pull/10802[#10802]
* Document copy semantics of QueueWriter::push method https://github.com/elastic/logstash/pull/10808[#10808]
* LIR support for octal literals in pipeline definitions https://github.com/elastic/logstash/pull/10828[#10828]
* Merge config values in LIR https://github.com/elastic/logstash/pull/10832[#10832]
* Fixes unit test failures on some runs of ConfigCompilerTest::testComplexConfigToPipelineIR https://github.com/elastic/logstash/pull/10837[#10837]
* Fix parsing of boolean options provided to Java plugins https://github.com/elastic/logstash/pull/10848[#10848]

=== Logstash Commits between 7.2 and 7.1.1

Computed with "git log --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit --date=relative v7.1.1..7.2"

7b9877a5f - (HEAD -> 7.2, origin/7.2) Add details about Elastic Search dependency (6 hours ago) <Jeff>
87fdc1710 - fix parsing of boolean options provided to Java plugins (4 days ago) <Dan Hermann>
f960644dd - field_refefence: handle illegal field references in converted maps (5 days ago) <Ry Biesemeyer>
3ffbc0f90 - Remove note about j11 (6 days ago) <Karen Metts>
6d113d110 - Value of start_timestamp must to be quoted (11 days ago) <Florian Kelbert>
87f503034 - Fixes unit test failures on some runs of ConfigCompilerTest::testComplexConfigToPipelineIR (12 days ago) <Dan Hermann>
2cfab287a - Merge config values in LIR (12 days ago) <Dan Hermann>
b334505f0 - allow skipping docker artifacts during artifact:all (13 days ago) <Joao Duarte>
501ea2953 - generate tarballs for docker images (13 days ago) <Joao Duarte>
fe2bfa68d - name rpm/deb oss packages as logstash-oss (13 days ago) <Joao Duarte>
1ba94fb81 - LIR support for octal literals in pipeline definitions (2 weeks ago) <Dan Hermann>
aeb1cc035 - release notes for 7.1.1 (2 weeks ago) <Joao Duarte>
5d7e34452 - Release notes for 7.1.0 (#10796) (2 weeks ago) <Karen Metts>
ccd2d80ad - Release notes for 7.0.1 (#10705) (2 weeks ago) <Logstash Machine>
e995fe595 - fix plugin doc version generation with default plugins (2 weeks ago) <Joao Duarte>
efb607689 - Update doc versions and branch for 7.2 (#10816) (3 weeks ago) <Karen Metts>
91d73a430 - update lock file for 7.2.0 (#10814) (3 weeks ago) <João Duarte>
36b3f16bc - add lock file from 7.1 branch (3 weeks ago) <Joao Duarte>
2d35566ab - Document copy semantics of QueueWriter::push method (3 weeks ago) <Dan Hermann>
9a06b204b - Provide DLQ writer interface to Java plugins (3 weeks ago) <Dan Hermann>
c22edf07f - Add structure for new windows topic (3 weeks ago) <Karen Metts>
822fef044 - (origin/update_lock_1558455155) Default stack trace size to 50 and make it configurable (3 weeks ago) <Dan Hermann>
7c32f0fcf - Expose Metrics API to Java plugins (#10761) (#10802) (3 weeks ago) <Dan Hermann>
5eb569719 - Include G1 in JVM heap metrics (#10728) (#10784) (5 weeks ago) <Dan Hermann>
a0d05b4da - fix JRuby resolv.rb leak (#10741) (5 weeks ago) <Colin Surprenant>
1c64619ac - Bump JrJackson to 0.4.8 (5 weeks ago) <Guy Boertje>
ba4207593 - Remove two other newlines (5 weeks ago) <Nik Everett>
c9846fc9c - Tweaks to callouts (5 weeks ago) <Karen Metts>
f6723e7ca - Remove return before callout defs (5 weeks ago) <Karen Metts>
ec74c231d - Fix asciidoc formatting for conversion to asciidoctor (5 weeks ago) <Karen Metts>
32934e677 - Clarify behavior of ensure_delivery flag (5 weeks ago) <Dan Hermann>
5e1dc1f6a - fix javadoc warning for Codec.java (5 weeks ago) <Joao Duarte>
3fba3af9f - * Adds a java_generator input with jdots codec to facilitate testing, adds float config type (6 weeks ago) <Dan Hermann>
735359c4c - bump to 7.2.0 (6 weeks ago) <Joao Duarte>
0793bf1f5 - [Docs] Asciidoctor support (#10730) (6 weeks ago) <Nik Everett>
5d64a61c2 - Add snapshot field (6 weeks ago) <Mike Place>
27d0ecab9 - hard-code status (6 weeks ago) <Mike Place>
d1c51f7d6 - ephemeral id (6 weeks ago) <Mike Place>
98f067022 - Replicate change from java_pipeline to ruby pipeline (6 weeks ago) <Mike Place>
42bbdd78c - Use pluginmetadata (6 weeks ago) <Mike Place>
dbea95111 - Add options to pipelines/ (6 weeks ago) <Mike Place>
592591bae - Add graph?=true parameter (6 weeks ago) <Mike Place>
8fd6e58e7 - Add cluster UUID (6 weeks ago) <Mike Place>
a8806b1d4 - Fix spec path (6 weeks ago) <Mike Place>
a875d9e52 - Remove commented code (6 weeks ago) <Mike Place>
4e5321a79 - Implement review suggestions (6 weeks ago) <Mike Place>
d4a915be2 - Style change to make code more vertical. (6 weeks ago) <Mike Place>
6bc3ba480 - Remove license and add encoding (6 weeks ago) <Mike Place>
06d50daf3 - Update spec (6 weeks ago) <Mike Place>
9c0dc0fb6 - Remove more commented code (6 weeks ago) <Mike Place>
0da3d0fb1 - Remove commented code (6 weeks ago) <Mike Place>
30adb7a56 - LIR serializer refactor (6 weeks ago) <Mike Place>
2dbe5c1bc - Include node update (6 weeks ago) <Mike Place>
9d5bec9ef - Add graph metrics (6 weeks ago) <Mike Place>
3428383b1 - Fix incorrect hash id (6 weeks ago) <Mike Place>
fbd1908e3 - Add ephemeral id and hash to pipeline stats (6 weeks ago) <Mike Place>
67aa14528 - Correct links to LS Ref Guide (6 weeks ago) <Karen Metts>
e173ceb04 - Note doc file created with plugin generation (7 weeks ago) <Karen Metts>
b83d8a0de - Incorporate review comments (7 weeks ago) <Karen Metts>
92dd9a932 - Add guidelines for writing plugin doc (7 weeks ago) <Karen Metts>
89be09907 - Move plugin cleanup before retry (7 weeks ago) <Rob Bavey>
8d60ab5c4 - Adds cleanup after shutdown of plugin (7 weeks ago) <Rob Bavey>
2e2a00270 - Add methods to clear PluginMetadata repositories (7 weeks ago) <Rob Bavey>
122adbd22 - adds LogStash::PluginMetadata for simple key/value plugin metadata (7 weeks ago) <Ry Biesemeyer>
f9a5876b3 - Clarify that Java codecs work only with Java inputs and outputs (7 weeks ago) <Dan Hermann>
a44cb9ebf - Rename filebeat.prospectors to filebeat.inputs (7 weeks ago) <urso>
14c712270 - Correction on Java execution in docs on command-line arguments (7 weeks ago) <Dan Hermann>
71d7b7c1f - rake task to generate dockerfile (7 weeks ago) <Joao Duarte>
96d2d59ab - Corrects the description of codec behavior in the output stage of Logstash pipelines (7 weeks ago) <Dan Hermann>
db80baf62 - Correct the docs for the settings file to note that Java execution defaults to true (7 weeks ago) <Dan Hermann>
de6ef0c04 - moved to openjdk 11 in docker testing (8 weeks ago) <Joao Duarte>
97704dc35 - properly exclude bundler 1.16.6 (9 weeks ago) <Joao Duarte>
86cae0854 - updated bundler to 1.17.3 (9 weeks ago) <Joao Duarte>
62f8282a3 - bump jruby to 9.2.7.0 (9 weeks ago) <Joao Duarte>
f39e4a944 - download exact version artifact for release build otherwise download snapshot (#10664) (9 weeks ago) <Colin Surprenant>
78ea83ec0 - Inputs expect a NamespacedMetric, not the root metric instance (9 weeks ago) <Jordan Johnson-Doyle>
d332bc33a - Add tests for LogStash::Codec::Delegator (9 weeks ago) <Jordan Johnson-Doyle>
81f7e4219 - Add tests for JavaCodecDelegator (9 weeks ago) <Jordan Johnson-Doyle>
b53e31320 - Collect and expose metrics from Ruby codecs (9 weeks ago) <Jordan Johnson-Doyle>
425155082 - Collect and expose metrics from Java codecs (9 weeks ago) <Jordan Johnson-Doyle>
25158bddd - Correctly sets the default codec to java_line. Fixes buffer handling for events whose encodings do not fit into the buffer. (9 weeks ago) <Dan Hermann>
d1e41f390 - [DOCS] Removes coming tags (9 weeks ago) <lcawl>
f9e2f2369 - Add links to particular breaking changes (9 weeks ago) <Karen Metts>
476e50393 - Added core and plugin headings Combine plugins from alphas, betas, and rcs to make 7.0 release notes (9 weeks ago) <Karen Metts>
685170904 - add 7.0.0 rc1 and rc2 release notes (#10665) (9 weeks ago) <Colin Surprenant>
d4e6236dd - Fix asciidoc formatting for links in release notes (#10665) (9 weeks ago) <Karen Metts>
12133e3a3 - add 7.0.0 alpha1, alpha2 and beta1 release notes (#10665) (9 weeks ago) <Colin Surprenant>
ce7e3107b - Update breaking changes doc for 7.0 (#10632) (9 weeks ago) <Karen Metts>
336ba7dfe - Refine upgrade instructions for 7.0 (9 weeks ago) <Karen Metts>
6e0658fbf - [DOCS] Adds tagged region for notable breaking changes (#10654) (#10661) (9 weeks ago) <Lisa Cawley>
563fa8117 - work around jruby-5642 during package installation on jdk11 (#10658) (10 weeks ago) <João Duarte>
aaac05009 - prevent DeprecatedRemovedSetting from fatally stopping logstash (#10657) (10 weeks ago) <João Duarte>
30dd8243d - Move Gradle wrappers around Ruby operations to a separate file to facilitate sharing of common operations with Java plugins (10 weeks ago) <Dan Hermann>
3ce3b96e3 - Handle duplicate config entries (10 weeks ago) <Dan Hermann>
6ed7b4bc5 - disable docker img generation on artifact:all (10 weeks ago) <Joao Duarte>
a335f2e4b - remove docker-compose symlink (10 weeks ago) <Joao Duarte>
0921798a7 - build docker images from logstash repo (#10603) (10 weeks ago) <João Duarte>
0c4fe62a6 - Log successful shutdowns (10 weeks ago) <Dan Hermann>
9827ba8bb - Add note about issues with Java 11 and Debian or RPM (#10635) (10 weeks ago) <Karen Metts>
6913e62a3 - Call out requirement for Java execution in note (10 weeks ago) <Dan Hermann>
f2b6fa35d - Remove duplicate text (10 weeks ago) <Karen Metts>
3e0ac53e3 - Removed note from earlier upgrade (10 weeks ago) <Karen Metts>
10301b40f - Update instructions for 7.0 upgrade (10 weeks ago) <Karen Metts>
4bb036f68 - eliminate unnecessary add of whitespace (2 months ago) <Colin Surprenant>
4a79246dd - add `DeprecatedSetting` to ease 7.0 transition of xpack config renames (2 months ago) <Ry Biesemeyer>
863a0c44e - Make the sample command easier to follow (2 months ago) <Yi Ou>
07eb8ea00 - Update Kafka version to fix build (3 months ago) <Rob Bavey>
1cda518c1 - Update JRuby and Java prerequisites (3 months ago) <Dan Hermann>
7bda524e2 - Add note that pline-pline also supports files (3 months ago) <Karen Metts>
4d0255228 - Update supported java version and example (3 months ago) <Karen Metts>
67e62a9c0 - Add sample doc files to plugin generator (3 months ago) <Karen Metts>
1f29c7145 - monitoring: bump to system_api_version 7 (3 months ago) <Jake Landis>
9eb2949ab - fix events_count to return total (3 months ago) <Ry Biesemeyer>
254353991 - cleanup many rakelib tasks that aren't used anymore (3 months ago) <Joao Duarte>
8ec1d2276 - correctly handle unexecuted downloadEs task (#10557) (3 months ago) <Colin Surprenant>
f6933dbe9 - move download setup code inside the downloadEs task (#10549) (3 months ago) <Colin Surprenant>
ebad88a35 - make monitoring specs resilient to internal api number changes (3 months ago) <Joao Duarte>
685050962 - Cherrypick to 7.x: Convert instructions for Java plugins to asciidoc (#10550) (3 months ago) <Karen Metts>
2ec00019a - Fix issue setting 'enable_metric => false' on a plugin (3 months ago) <Rob Bavey>
80cf579e5 - prevent concurrent convergence (e.g., SIGHUP during in-flight convergence) (3 months ago) <Ry Biesemeyer>
3c3e769bb - Update monitoring HTTP end point (3 months ago) <Jake Landis>
ecba50c28 - Change internal document type to push "_doc" instead of "doc" (3 months ago) <Rob Bavey>
182639a64 - fix bug with explicitly-specified Java codecs (3 months ago) <Dan Hermann>
439ef7f1c - update to send api version 6 (3 months ago) <Jake Landis>
7ca98d341 - Central management typeless API (3 months ago) <Jake Landis>
59e51127a - Mute CI integration DLQ acceptance test (3 months ago) <Guy Boertje>
ca6ad64c7 - Improve docs about using Filebeat modules with Logstash (#10438) (4 months ago) <DeDe Morton>
1c88792d4 - bump jruby to 9.2.6.0 (4 months ago) <Joao Duarte>
116228213 - remove exclusive lock for Ruby pipeline initialization (#10461) (4 months ago) <Colin Surprenant>
2d5df520b - Mute CLI integration plugin acceptance test (4 months ago) <Rob Bavey>
b941c17da - Mute Failing Test on Windows (4 months ago) <Rob Bavey>
94cb37bed - One more character encoding fix (4 months ago) <Dan Hermann>
41c635411 - Add placeholder for 7.0.0.-beta1 (4 months ago) <Karen Metts>
94bade371 - Incorporate review comments (4 months ago) <Karen Metts>
bf56ff763 - Add prilileges required for ilm (4 months ago) <Karen Metts>
b0bccd865 - fix Stdin tests to work on platforms that do not have UTF-8 as the default character encoding (4 months ago) <Dan Hermann>
ef56ca124 - Fix line codec tests so they work on platforms such as Windows that do not have UTF-8 as the default character encoding (4 months ago) <Dan Hermann>
ff89aa140 - Move field-ref include below xpack content (4 months ago) <Karen Metts>
907d2ba94 - Edits from review comments (4 months ago) <Karen Metts>
257e3ce11 - Expande descriptions (4 months ago) <Karen Metts>
f87da37e1 - Add http and memcached filters to lookup plugins (4 months ago) <Karen Metts>
22648332a - Reorder files in index to unhide lost topics Add comment about placement of include (4 months ago) <Karen Metts>
42c63b75d - factor in OS and architecture when downloading ES (4 months ago) <Joao Duarte>
cfeaa5411 - ast/lir: simplify concurrent use of AST, which is globally stateful (4 months ago) <Ry Biesemeyer>
927791787 - Remove unnecessary option to not require host in SafeURI (4 months ago) <Rob Bavey>
0ebbb3949 - Better handle malformed URIs (4 months ago) <Rob Bavey>
29280c152 - mute metrics_spec line 138 test (4 months ago) <Joao Duarte>
1437cdc20 - pin childprocess to 0.9 (4 months ago) <Joao Duarte>
009e764c1 - keystore: instances of `CharsetEncoder` are stateful and cannot be shared (4 months ago) <Ry Biesemeyer>
0e4ab8a78 - Update :branch: property in 7.x index.asciidoc (#10403) (4 months ago) <João Duarte>
7ef757230 - bump version to 7.1.0 (#10402) (4 months ago) <João Duarte>

=== Logstash Plugin Release Changelogs ===
Computed from "git diff v7.1.1..7.2 *.release"
Changed plugin versions:
logstash-codec-es_bulk: 3.0.7 -> 3.0.8
logstash-filter-dns: 3.0.12 -> 3.0.13
logstash-filter-geoip: 6.0.0 -> 6.0.1
logstash-filter-jdbc_streaming: 1.0.5 -> 1.0.6
logstash-input-azure_event_hubs: 1.1.0 -> 1.1.1
logstash-input-elasticsearch: 4.3.0 -> 4.3.1
logstash-output-elasticsearch: 10.0.2 -> 10.1.0
---------- DELETE UP TO HERE ------------

==== Plugins

*Es_bulk Codec*

* Fixed deeplink to Elasticsearch Reference [#18](https://github.com/logstash-plugins/logstash-codec-es_bulk/pull/18)

*Dns Filter*

* Fixed JRuby resolver bug for versions after to 9.2.0.0 [#51](https://github.com/logstash-plugins/logstash-filter-dns/pull/51)

*Geoip Filter*

* Fixed deeplink to Elasticsearch Reference 
  [#151](https://github.com/logstash-plugins/logstash-filter-geoip/pull/151)

*Jdbc_streaming Filter*

* Fixes connection leak in pipeline reloads by properly disconnecting on plugin close

*Azure_event_hubs Input*

* Updated Azure event hub library dependencies[#36](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/pull/36)

*Elasticsearch Input*

* Fixed deeplink to Elasticsearch Reference  [#103](https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/103)

*Elasticsearch Output*

* Added cluster id tracking through the plugin metadata registry [#857](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/857)


[[logstash-7-1-1]]
=== Logstash 7.1.1 Release Notes

* There are no user facing changes in this release.

[[logstash-7-1-0]]
=== Logstash 7.1.0 Release Notes

* Updates to support changes to licensing of security features.
+
Some Elastic Stack security features, such as encrypted communications, file and native authentication, and 
role-based access control, are now available in more subscription levels. For details, see https://www.elastic.co/subscriptions.

[[logstash-7-0-1]]
=== Logstash 7.0.1 Release Notes

* Fixed default codec and buffer handling in Java stdout output https://github.com/elastic/logstash/pull/10673[#10673]
* Corrected the description of codec behavior in the output stage of Logstash pipelines https://github.com/elastic/logstash/pull/10682[#10682]
* Corrected settings file doc to note that Java execution defaults to true https://github.com/elastic/logstash/pull/10701[#10701]
* Updated JRuby to 9.2.7.0 https://github.com/elastic/logstash/pull/10674[#10674]
* Updated Bundler to 1.17.3 https://github.com/elastic/logstash/pull/10685[#10685]

==== Plugins

*Csv Filter*

* Fixed asciidoc formatting for example https://github.com/logstash-plugins/logstash-filter-csv/pull/73[#73]
* Documented that the `autodetect_column_names` and `skip_header` options work only when the number of Logstash
  pipeline workers is set to `1`.

*Dns Filter*

* Fixed issue where unqualified domains would fail to resolve when running this plugin with Logstash 5.x https://github.com/logstash-plugins/logstash-filter-dns/pull/48[#48]
* Fixed crash that could occur when encountering certain classes of invalid inputs https://github.com/logstash-plugins/logstash-filter-dns/pull/49[#49]

*Kv Filter*

* Fixed asciidoc formatting in documentation https://github.com/logstash-plugins/logstash-filter-kv/pull/81[#81]

* Added a timeout enforcer which prevents inputs that are pathological against the generated parser from blocking
   the pipeline. By default, timeout is a generous 30s, but can be configured or disabled entirely with the new
   `timeout_millis` and `tag_on_timeout` directives (https://github.com/logstash-plugins/logstash-filter-kv/pull/79[#79])
* Made error-handling configurable with `tag_on_failure` directive.

*Xml Filter*

* Fixed creation of empty arrays when xpath failed https://github.com/logstash-plugins/logstash-filter-xml/pull/59[#59]


*Dead_letter_queue Input*

* Fixed asciidoc formatting in documentation https://github.com/logstash-plugins/logstash-input-dead_letter_queue/pull/21[#21]


*File Input*

* Fixed problem in Windows where some paths would fail to return an identifier ("inode"). Make path into a C style String before encoding to UTF-16LE. https://github.com/logstash-plugins/logstash-input-file/issues/232[#232]

*Snmp Input*

* Added support for querying SNMP tables
* Changed three error messages in the base_client to include the target address for clarity in the logs.

*Tcp Input*

* Fixed race condition where data would be accepted before queue was configured
* Added support for multiple certificates per file https://github.com/logstash-plugins/logstash-input-tcp/pull/140[#140]

*Twitter Input*

* Updated http-form_data to `~> 2` and public_suffix to `~> 3`

*Elasticsearch Output*

* Fixed bug where index patterns in custom templates could be erroneously overwritten https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/861[#861]

*Kafka Output*

* Fixed issue with unnecessary sleep after retries exhausted https://github.com/logstash-plugins/logstash-output-kafka/pull/216[#216]

*S3 Output*

* Added configuration information for multiple s3 outputs to documentation https://github.com/logstash-plugins/logstash-output-s3/pull/196[#196]
* Fixed formatting problems and typographical errors https://github.com/logstash-plugins/logstash-output-s3/pull/194[#194], https://github.com/logstash-plugins/logstash-output-s3/pull/201[#201], and https://github.com/logstash-plugins/logstash-output-s3/pull/204[#204]
* Added support for setting mutipart upload threshold https://github.com/logstash-plugins/logstash-output-s3/pull/202[#202]

[[logstash-7-0-0]]
=== Logstash 7.0.0 Release Notes

The list combines release notes from the 7.0.0-alpha1, -alpha2, -beta1, -rc1 and -rc2 releases.

==== Logstash core
* BUGFIX: Correctly count total queued items across multiple pipelines https://github.com/elastic/logstash/pull/10564[#10564]
* BUGFIX: Fix issue setting 'enable_metric => false' https://github.com/elastic/logstash/pull/10538[#10538]
* BUGFIX: Prevent concurrent convergence of pipeline actions https://github.com/elastic/logstash/pull/10537[#10537]
* Monitoring: Change internal document type to push "_doc" instead of "doc" https://github.com/elastic/logstash/pull/10533[#10533]
* BUGFIX: Allow explicitly-specified Java codecs https://github.com/elastic/logstash/pull/10520[#10520]
* Central management typeless API https://github.com/elastic/logstash/pull/10421[#10421]
* Improve docs about using Filebeat modules with Logstash https://github.com/elastic/logstash/pull/10438[#10438]
* Bump JRuby to 9.2.6.0 https://github.com/elastic/logstash/pull/10425[#10425] 
* BUGFIX: Remove exclusive lock for Ruby pipeline initialization https://github.com/elastic/logstash/pull/10462[#10462]
* Update Java dependencies https://github.com/elastic/logstash/pull/10340[#10340]
* Remove pipeline output workers setting https://github.com/elastic/logstash/pull/10358[#10358]
* Cleanup Ruby gems dependencies https://github.com/elastic/logstash/pull/10171[#10171]
* Ensure compatibility of module data with ES and Kibana 7.0 https://github.com/elastic/logstash/pull/10356[#10356]
* Rename x-pack monitoring and management config option .url and .ca to .hosts and .certificate_authority https://github.com/elastic/logstash/pull/10380[#10380]
* BUGFIX: building of deb and rpm artifacts https://github.com/elastic/logstash/pull/10396[#10396]
* Make Java execution the default https://github.com/elastic/logstash/pull/8649[#8649]
* Field-reference parsing is now strict by default https://github.com/elastic/logstash/pull/9543[#9543]
* Improvements to core Javaification
* BUGFIX: Support for Byte, Short and Date type conversions as seen in the rabbitmq input plugin https://github.com/elastic/logstash/pull/9984[#9984]

==== Plugins
Here are the plugin changes.

===== Codec plugins
* logstash-codec-cef
  - Removed obsolete `sev` and `deprecated_v1_fields` fields
  - Fixed minor doc inconsistencies (added reverse_mapping to options table, moved it to alpha order in option descriptions, fixed typo)
    https://github.com/logstash-plugins/logstash-codec-cef/pull/60[#60]
* logstash-codec-es_bulk
  - Add documentation about use with http input
* logstash-codec-netflow
  - Fix sub-second timestamp math
  - BREAKING: Added support for RFC6759 decoding of application_id. This is a breaking change to the way application_id is decoded. The format changes from e.g. 0:40567 to 0..12356..40567
  - Fixed IPFIX options template parsing for Juniper MX240 JunOS 15.1
  - Fixed incorrect parsing of zero-filled Netflow 9 packets from Palo Alto
  - Added support for Netflow v9 devices with VarString fields (H3C Netstream)
  - Reduced complexity of creating, persisting, loading an retrieving template caches
  - Fixed issue where TTL in template registry was not being respected
  - Added Cisco ACI to list of known working Netflow v9 exporters
  - Added support for IXIA Packet Broker IPFIX
  - Fixed issue with Procera float fields

===== Filter plugins
* logstash-filter-aggregate
  - new feature: add ability to dynamically define a custom `timeout` or `inactivity_timeout` in `code` block (fix issues https://github.com/logstash-plugins/logstash-filter-aggregate/issues/91[#91] and https://github.com/logstash-plugins/logstash-filter-aggregate/issues/92[#92])
  - new feature: add meta informations available in `code` block through `map_meta` variable
  - new feature: add Logstash metrics, specific to aggregate plugin: aggregate_maps, pushed_events, task_timeouts, code_errors, timeout_code_errors
  - new feature: validate at startup that `map_action` option equals to 'create', 'update' or 'create_or_update'
* logstash-filter-clone
  - Make 'clones' a required option
  - Added a warning when 'clones' is empty since that results in a no-op https://github.com/logstash-plugins/logstash-filter-clone/issues/14[#14]
* logstash-filter-de_dot
  - fix failure of fieldnames with boolean value "false"
* logstash-filter-dns
  - Fixed issue where unqualified domains would fail to resolve when running this plugin with Logstash 5.x https://github.com/logstash-plugins/logstash-filter-dns/pull/48[#48]
  - Fixed crash that could occur when encountering certain classes of invalid inputs https://github.com/logstash-plugins/logstash-filter-dns/pull/49[#49]
* logstash-filter-elasticsearch
  - Add support for extracting hits total from Elasticsearch 7.x responses
  - Added connection check during register to avoid failures during processing
  - Changed Elasticsearch Client transport to use Manticore
  - Changed amount of logging details during connection failure
* logstash-filter-fingerprint
  - Fixed concurrent SHA fingerprinting by making the instances thread local
* logstash-filter-geoip
  - Removed obsolete lru_cache_size field  
* NEW: logstash-filter-http
  - Beta version of HTTP filter plugin based on @lucashenning's https://github.com/lucashenning/logstash-filter-rest[REST filter].
  - Fixed minor documentation issues https://github.com/logstash-plugins/logstash-filter-http/pull/9[#9]
  - Minor documentation fixes  
* logstash-filter-jdbc_static
  - Added info to documentation to emphasize significance of table order https://github.com/logstash-plugins/logstash-filter-jdbc_static/pull/36[36]      
* logstash-filter-jdbc_streaming
  - Swap out mysql for postgresql for testing https://github.com/logstash-plugins/logstash-filter-jdbc_streaming/pull/11[#11] 
* logstash-filter-json
  - Updated documentation with some clarifications and fixes
* logstash-filter-kv
  - Added a timeout enforcer which prevents inputs that are pathological against the generated parser from blocking
    the pipeline. By default, timeout is a generous 30s, but can be configured or disabled entirely with the new
    `timeout_millis` and `tag_on_timeout` directives https://github.com/logstash-plugins/logstash-filter-kv/pull/79[#79]
  - Made error-handling configurable with `tag_on_failure` directive.
* NEW: logstash-filter-memcached  
  - Updated to 1.0.0
  - The plugin common options (e.g., `add_field`, `add_tag`, etc.) are now correctly only invoked when the plugin successfully gets one or more values from, or sets one or more values to memcached (#4)
  - Fix links to argument types in documentation (#3)
* logstash-filter-metrics
  - Fixed two minor typos in documentation
* logstash-filter-mutate
  - Added ability to directly convert from integer and float to boolean https://github.com/logstash-plugins/logstash-filter-mutate/pull/127[#127]
* logstash-filter-split
  - Fixed numeric values, optimized @target verification, cleanups and specs https://github.com/logstash-plugins/logstash-filter-split/pull/36[#36]
* logstash-filter-xml
  - Fixed creation of empty arrays when xpath failed https://github.com/logstash-plugins/logstash-filter-xml/pull/59[#59]
  - Fixed force_array behavior with nested elements https://github.com/logstash-plugins/logstash-filter-xml/pull/57[#57]

===== Input plugins
*  logstash-input-azure_event_hubs
  - Updated Azure event hub library dependencies https://github.com/logstash-plugins/logstash-input-azure_event_hubs/pull/27[#27]
*  logstash-input-beats 
  - Removed obsolete setting congestion_threshold and target_field_for_codec
  - Changed default value of `add_hostname` to false
  - Loosen jar-dependencies manager gem dependency to allow plugin to work with JRubies that include a later version
  - Updated jar dependencies to reflect newer releases
* logstash-input-elasticsearch
  - Added managed slice scrolling with `slices` option
* logstash-input-file
  - Fixed problem in Windows where some paths would fail to return an identifier ("inode"). Make path into a C style String before encoding to UTF-16LE. https://github.com/logstash-plugins/logstash-input-file/issues/232[#232]
  - Fixed issue where logs were being spammed with needless error messages https://github.com/logstash-plugins/logstash-input-file/pull/224[#224]
  - Fixed problem in tail and read modes where the read loop could get stuck if an IO error occurs in the loop.
      The file appears to be being read but it is not, suspected with file truncation schemes.
      https://github.com/logstash-plugins/logstash-input-file/issues/205[#205]
  - Fixed problem in rotation handling where the target file being rotated was
  subjected to the start_position setting when it must always start from the beginning.
  https://github.com/logstash-plugins/logstash-input-file/issues/214[#214]
* logstash-input-gelf
  - Fixed shutdown handling, robustness in socket closing and restarting, json parsing, code DRYing and cleanups https://github.com/logstash-plugins/logstash-input-gelf/pull/62[#62]
* logstash-input-http
  - Added configurable response code option https://github.com/logstash-plugins/logstash-input-http/pull/103[#103]
  - Added explanation about operation order of codec and additional_codecs https://github.com/logstash-plugins/logstash-input-http/pull/104[#104]
  - Added configurable response code option https://github.com/logstash-plugins/logstash-input-http/pull/103[#103]
  - Added explanation about operation order of codec and additional_codecs https://github.com/logstash-plugins/logstash-input-http/pull/104[#104]
  - Loosen jar-dependencies manager gem dependency to allow plugin to work with JRubies that include a later version.
  - Changed jar dependencies to reflect newer versions
* logstash-input-http_poller
  - Fixed minor doc and doc formatting issues https://github.com/logstash-plugins/logstash-input-http_poller/pull/107[#107]
  - Removed obsolete field `interval`
  - Changed `schedule` entry to show that it is required
    https://github.com/logstash-plugins/logstash-input-http_poller/pull/102[#102]
* logstash-input-kafka
  - Removed obsolete `ssl` option
  - Added support for kafka property ssl.endpoint.identification.algorithm https://github.com/logstash-plugins/logstash-input-kafka/pull/302[#302]
  - Changed Kafka client version to 2.1.0
  - Changed Kafka client version to 2.0.1 https://github.com/logstash-plugins/logstash-input-kafka/pull/295[#295]
* logstash-input-snmp
  - Added no_codec condition to the documentation and bumped version https://github.com/logstash-plugins/logstash-input-snmp/pull/39[#39]
  - Changed docs to improve options layout https://github.com/logstash-plugins/logstash-input-snmp/pull/38[#38]
  - Added support for querying SNMP tables
  - Changed three error messages in the base_client to include the target address for clarity in the logs.
* logstash-input-sqs
  - Added support for multiple events inside same message from SQS https://github.com/logstash-plugins/logstash-input-sqs/pull/48[#48]
* logstash-input-tcp
  - Removed obsolete `data_timeout` and `ssl_cacert` options
  - Fixed race condition where data would be accepted before queue was configured
  - Support multiple certificates per file https://github.com/logstash-plugins/logstash-input-tcp/pull/140[#140]
  
===== Output plugins
* logstash-output-elasticsearch
  - Remove support for parent child (still support join data type) since we don't support multiple document types any more
  - Removed obsolete `flush_size` and `idle_flush_time`
  - Added 'auto' setting for ILM with default of 'auto' https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/838[#838]
  - Fixed sniffing support for 7.x https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/827[#827]
  - Fixed issue with escaping index names which was causing writing aliases for ILM to fail https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/831[#831]
  - Adds support for Index Lifecycle Management for Elasticsearch 6.6.0 and above, running with at least a Basic License(Beta) https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/805[#805]
  - Fixed support for Elasticsearch 7.x https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/812[#812]
  - Tweaked logging statements to reduce verbosity
  - Fixed numerous issues relating to builds on Travis https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/799[#799]
* logstash-output-file
  - Removed JRuby check when using FIFOs https://github.com/logstash-plugins/logstash-output-file/pull/75[#75]
* logstash-output-http
  - Relax dependency on http_client mixin since current major works on both
  - Fixed handling of empty `retryable_codes` https://github.com/logstash-plugins/logstash-output-http/pull/99[#99]
* logstash-output-kafka
  - Fixed issue with unnecessary sleep after retries exhausted https://github.com/logstash-plugins/logstash-output-kafka/pull/216[#216]
  - Removed obsolete `block_on_buffer_full`, `ssl` and `timeout_ms` options
  - Added support for kafka property `ssl.endpoint.identification.algorithm` https://github.com/logstash-plugins/logstash-output-kafka/pull/213[#213]
  - Changed Kafka client to version 2.1.0
  - Changed Kafka client to version 2.0.1 https://github.com/logstash-plugins/logstash-output-kafka/pull/209[#209]
* logstash-output-pagerduty
  - Update _development_ dependency webmock to latest version to prevent conflicts in logstash core's dependency matrix.
* logstash-output-redis
  - Removed obsolete fields `queue` and `name`
  - Changed major version of redis library dependency to 4.x
* logstash-output-s3
  - Add support for setting mutipart upload threshold https://github.com/logstash-plugins/logstash-output-s3/pull/202[#202]
  - Fixed issue where on restart, 0 byte files could erroneously be uploaded to s3 https://github.com/logstash-plugins/logstash-output-s3/issues/195[#195]
* logstash-output-sqs
  - Removed obsolete fields `batch` and `batch_timeout`
  - Removed workaround to JRuby bug https://github.com/jruby/jruby/issues/3645[#3645]
* logstash-output-tcp
  - Removed obsolete field `message_format`
  - Removed requirement to have a certificate/key pair when enabling ssl
    
    
* logstash-mixin-http_client
  - Removed obsolete ssl_certificate_verify option




[[logstash-7-0-0-rc2]]
=== Logstash 7.0.0-rc2 Release Notes

==== Plugins
* logstash-input-snmp
  - Added support for querying SNMP tables
  - Changed three error messages in the base_client to include the target address for clarity in the logs.

[[logstash-7-0-0-rc1]]
=== Logstash 7.0.0-rc1 Release Notes

==== Logstash core
* BUGFIX: Correctly count total queued items across multiple pipelines https://github.com/elastic/logstash/pull/10564[#10564]
* BUGFIX: Fix issue setting 'enable_metric => false' https://github.com/elastic/logstash/pull/10538[#10538]
* BUGFIX: Prevent concurrent convergence of pipeline actions https://github.com/elastic/logstash/pull/10537[#10537]
* Monitoring: Change internal document type to push "_doc" instead of "doc" https://github.com/elastic/logstash/pull/10533[#10533]
* BUGFIX: Allow explicitly-specified Java codecs https://github.com/elastic/logstash/pull/10520[#10520]
* Central management typeless API https://github.com/elastic/logstash/pull/10421[#10421]
* Improve docs about using Filebeat modules with Logstash https://github.com/elastic/logstash/pull/10438[#10438]
* Bump JRuby to 9.2.6.0 https://github.com/elastic/logstash/pull/10425[#10425] 
* BUGFIX: Remove exclusive lock for Ruby pipeline initialization https://github.com/elastic/logstash/pull/10462[#10462]

==== Plugins
* logstash-filter-dns
  - Fixed issue where unqualified domains would fail to resolve when running this plugin with Logstash 5.x https://github.com/logstash-plugins/logstash-filter-dns/pull/48[#48]
  - Fixed crash that could occur when encountering certain classes of invalid inputs https://github.com/logstash-plugins/logstash-filter-dns/pull/49[#49]
* logstash-filter-kv
  - Added a timeout enforcer which prevents inputs that are pathological against the generated parser from blocking
    the pipeline. By default, timeout is a generous 30s, but can be configured or disabled entirely with the new
    `timeout_millis` and `tag_on_timeout` directives https://github.com/logstash-plugins/logstash-filter-kv/pull/79[#79]
  - Made error-handling configurable with `tag_on_failure` directive.
* logstash-filter-xml
  - Fixed creation of empty arrays when xpath failed https://github.com/logstash-plugins/logstash-filter-xml/pull/59[#59]
* logstash-input-file
  - Fixed problem in Windows where some paths would fail to return an identifier ("inode"). Make path into a C style String before encoding to UTF-16LE. https://github.com/logstash-plugins/logstash-input-file/issues/232[#232]
* logstash-input-tcp
  - Fixed race condition where data would be accepted before queue was configured
  - Support multiple certificates per file https://github.com/logstash-plugins/logstash-input-tcp/pull/140[#140]
* logstash-output-kafka
  - Fixed issue with unnecessary sleep after retries exhausted https://github.com/logstash-plugins/logstash-output-kafka/pull/216[#216]
* logstash-output-s3
  - Add support for setting mutipart upload threshold https://github.com/logstash-plugins/logstash-output-s3/pull/202[#202]

[[logstash-7-0-0-beta1]]
=== Logstash 7.0.0-beta1 Release Notes

==== Logstash core
* Update Java dependencies https://github.com/elastic/logstash/pull/10340[#10340]
* Remove pipeline output workers setting https://github.com/elastic/logstash/pull/10358[#10358]
* Cleanup Ruby gems dependencies https://github.com/elastic/logstash/pull/10171[#10171]
* Ensure compatibility of module data with ES and Kibana 7.0 https://github.com/elastic/logstash/pull/10356[#10356]
* Rename x-pack monitoring and management config option .url and .ca to .hosts and .certificate_authority https://github.com/elastic/logstash/pull/10380[#10380]
* BUGFIX: building of deb and rpm artifacts https://github.com/elastic/logstash/pull/10396[#10396]

==== Plugins
* logstash-codec-cef
  - Removed obsolete `sev` and `deprecated_v1_fields` fields
  - Fixed minor doc inconsistencies (added reverse_mapping to options table, moved it to alpha order in option descriptions, fixed typo)
    https://github.com/logstash-plugins/logstash-codec-cef/pull/60[#60]
* logstash-codec-es_bulk
  - Add documentation about use with http input
* logstash-codec-netflow
  - Fix sub-second timestamp math
* logstash-filter-clone
  - Make 'clones' a required option
  - Added a warning when 'clones' is empty since that results in a no-op https://github.com/logstash-plugins/logstash-filter-clone/issues/14[#14]
* logstash-filter-de_dot
  - fix failure of fieldnames with boolean value "false"
* logstash-filter-geoip
  - Removed obsolete lru_cache_size field
* logstash-filter-http
  - Fixed minor documentation issues https://github.com/logstash-plugins/logstash-filter-http/pull/9[#9]
  - Minor documentation fixes
* logstash-filter-jdbc_streaming
  - Swap out mysql for postgresql for testing https://github.com/logstash-plugins/logstash-filter-jdbc_streaming/pull/11[#11] 
* logstash-filter-json
  - Updated documentation with some clarifications and fixes
* logstash-filter-memcached
  - Updated to 1.0.0
  - The plugin common options (e.g., `add_field`, `add_tag`, etc.) are now correctly only invoked when the plugin successfully gets one or more values from, or sets one or more values to memcached (#4)
  - Fix links to argument types in documentation (#3)
* logstash-filter-metrics
  - Fixed two minor typos in documentation
* logstash-filter-mutate
  - Added ability to directly convert from integer and float to boolean https://github.com/logstash-plugins/logstash-filter-mutate/pull/127[#127]
* logstash-filter-split
  - Fixed numeric values, optimized @target verification, cleanups and specs https://github.com/logstash-plugins/logstash-filter-split/pull/36[#36]
*  logstash-input-azure_event_hubs
  - Updated Azure event hub library dependencies https://github.com/logstash-plugins/logstash-input-azure_event_hubs/pull/27[#27]
*  logstash-input-beats 
  - Removed obsolete setting congestion_threshold and target_field_for_codec
  - Changed default value of `add_hostname` to false
* logstash-input-elasticsearch
  - Added managed slice scrolling with `slices` option
* logstash-input-http
  - Added configurable response code option https://github.com/logstash-plugins/logstash-input-http/pull/103[#103]
  - Added explanation about operation order of codec and additional_codecs https://github.com/logstash-plugins/logstash-input-http/pull/104[#104]
* logstash-input-http_poller
  - Fixed minor doc and doc formatting issues https://github.com/logstash-plugins/logstash-input-http_poller/pull/107[#107]
  - Removed obsolete field `interval`
  - Changed `schedule` entry to show that it is required
    https://github.com/logstash-plugins/logstash-input-http_poller/pull/102[#102]
* logstash-input-kafka
  - Removed obsolete `ssl` option
* logstash-input-tcp
  - Removed obsolete `data_timeout` and `ssl_cacert` options
* logstash-mixin-http_client
  - Removed obsolete ssl_certificate_verify option
* logstash-output-elasticsearch
  - Remove support for parent child (still support join data type) since we don't support multiple document types any more
  - Removed obsolete `flush_size` and `idle_flush_time`
  - Added 'auto' setting for ILM with default of 'auto' https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/838[#838]
  - Fixed sniffing support for 7.x https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/827[#827]
  - Fixed issue with escaping index names which was causing writing aliases for ILM to fail https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/831[#831]
* logstash-output-file
  - Removed JRuby check when using FIFOs https://github.com/logstash-plugins/logstash-output-file/pull/75[#75]
* logstash-output-http
  - Relax dependency on http_client mixin since current major works on both
* logstash-output-kafka
  - Removed obsolete `block_on_buffer_full`, `ssl` and `timeout_ms` options
* logstash-output-pagerduty
  - Update _development_ dependency webmock to latest version to prevent conflicts in logstash core's dependency matrix.
* logstash-output-redis
  - Removed obsolete fields `queue` and `name`
  - Changed major version of redis library dependency to 4.x
* logstash-output-sqs
  - Removed obsolete fields `batch` and `batch_timeout`
  - Removed workaround to JRuby bug https://github.com/jruby/jruby/issues/3645[#3645]
* logstash-output-tcp
  - Removed obsolete field `message_format`
  - Removed requirement to have a certificate/key pair when enabling ssl

[[logstash-7-0-0-alpha2]]
=== Logstash 7.0.0-alpha2 Release Notes

==== Plugins
* logstash-filter-elasticsearch
  - Add support for extracting hits total from Elasticsearch 7.x responses
  - Added connection check during register to avoid failures during processing
  - Changed Elasticsearch Client transport to use Manticore
  - Changed amount of logging details during connection failure
* logstash-filter-fingerprint
  - Fixed concurrent SHA fingerprinting by making the instances thread local
* NEW: logstash-filter-http
  - Beta version of HTTP filter plugin based on @lucashenning's https://github.com/lucashenning/logstash-filter-rest[REST filter].
* NEW: logstash-filter-memcached
* logstash-input-beats
  - Loosen jar-dependencies manager gem dependency to allow plugin to work with JRubies that include a later version
  - Updated jar dependencies to reflect newer releases
* logstash-input-file
  - Fixed issue where logs were being spammed with needless error messages https://github.com/logstash-plugins/logstash-input-file/pull/224[#224]
  - Fixed problem in tail and read modes where the read loop could get stuck if an IO error occurs in the loop.
    The file appears to be being read but it is not, suspected with file truncation schemes.
    https://github.com/logstash-plugins/logstash-input-file/issues/205[#205]
* logstash-input-gelf
  - Fixed shutdown handling, robustness in socket closing and restarting, json parsing, code DRYing and cleanups https://github.com/logstash-plugins/logstash-input-gelf/pull/62[#62]
* logstash-input-http
  - Loosen jar-dependencies manager gem dependency to allow plugin to work with JRubies that include a later version.
  - Changed jar dependencies to reflect newer versions
* logstash-input-kafka
  - Added support for kafka property ssl.endpoint.identification.algorithm https://github.com/logstash-plugins/logstash-input-kafka/pull/302[#302]
  - Changed Kafka client version to 2.1.0
  - Changed Kafka client version to 2.0.1 https://github.com/logstash-plugins/logstash-input-kafka/pull/295[#295]
* logstash-output-elasticsearch
  - Adds support for Index Lifecycle Management for Elasticsearch 6.6.0 and above, running with at least a Basic License(Beta) https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/805[#805]
  - Fixed support for Elasticsearch 7.x https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/812[#812]
* logstash-output-http
  - Fixed handling of empty `retryable_codes` https://github.com/logstash-plugins/logstash-output-http/pull/99[#99]
* logstash-output-kafka
  - Added support for kafka property `ssl.endpoint.identification.algorithm` https://github.com/logstash-plugins/logstash-output-kafka/pull/213[#213]
  - Changed Kafka client to version 2.1.0
  - Changed Kafka client to version 2.0.1 https://github.com/logstash-plugins/logstash-output-kafka/pull/209[#209]

[[logstash-7-0-0-alpha1]]
=== Logstash 7.0.0-alpha1 Release Notes

==== Logstash core
* Make Java execution the default https://github.com/elastic/logstash/pull/8649[#8649]
* Field-reference parsing is now strict by default https://github.com/elastic/logstash/pull/9543[#9543]
* Improvements to core Javaification
* BUGFIX: Support for Byte, Short and Date type conversions as seen in the rabbitmq input plugin https://github.com/elastic/logstash/pull/9984[#9984]

==== Plugins
* logstash-codec-netflow
  - BREAKING: Added support for RFC6759 decoding of application_id. This is a breaking change to the way application_id is decoded. The format changes from e.g. 0:40567 to 0..12356..40567
  - Fixed IPFIX options template parsing for Juniper MX240 JunOS 15.1
  - Fixed incorrect parsing of zero-filled Netflow 9 packets from Palo Alto
  - Added support for Netflow v9 devices with VarString fields (H3C Netstream)
  - Reduced complexity of creating, persisting, loading an retrieving template caches
  - Fixed issue where TTL in template registry was not being respected
  - Added Cisco ACI to list of known working Netflow v9 exporters
  - Added support for IXIA Packet Broker IPFIX
  - Fixed issue with Procera float fields
* logstash-filter-aggregate
  - new feature: add ability to dynamically define a custom `timeout` or `inactivity_timeout` in `code` block (fix issues https://github.com/logstash-plugins/logstash-filter-aggregate/issues/91[#91] and https://github.com/logstash-plugins/logstash-filter-aggregate/issues/92[#92])
  - new feature: add meta informations available in `code` block through `map_meta` variable
  - new feature: add Logstash metrics, specific to aggregate plugin: aggregate_maps, pushed_events, task_timeouts, code_errors, timeout_code_errors
  - new feature: validate at startup that `map_action` option equals to 'create', 'update' or 'create_or_update'
* logstash-filter-jdbc_static
 - Added info to documentation to emphasize significance of table order https://github.com/logstash-plugins/logstash-filter-jdbc_static/pull/36[36]
* logstash-filter-xml
  - Fixed creation of empty arrays when xpath failed https://github.com/logstash-plugins/logstash-filter-xml/pull/59[#59]
  - Fixed force_array behavior with nested elements https://github.com/logstash-plugins/logstash-filter-xml/pull/57[#57]
* logstash-input-file
  - Fixed problem in rotation handling where the target file being rotated was
  subjected to the start_position setting when it must always start from the beginning.
  https://github.com/logstash-plugins/logstash-input-file/issues/214[#214]
* logstash-input-snmp
  - Added no_codec condition to the documentation and bumped version https://github.com/logstash-plugins/logstash-input-snmp/pull/39[#39]
  - Changed docs to improve options layout https://github.com/logstash-plugins/logstash-input-snmp/pull/38[#38]
* logstash-input-sqs
  - Added support for multiple events inside same message from SQS https://github.com/logstash-plugins/logstash-input-sqs/pull/48[#48]
* logstash-output-elasticsearch
  - Tweaked logging statements to reduce verbosity
  - Fixed numerous issues relating to builds on Travis https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/799[#799]
* logstash-output-s3
  - Fixed issue where on restart, 0 byte files could erroneously be uploaded to s3 https://github.com/logstash-plugins/logstash-output-s3/issues/195[#195]