[[releasenotes]]
== Logstash 2.2 Release Notes

* Added dynamic config, a new feature to track config file for changes and restart the 
  pipeline (same process) with updated config changes. This feature can be enabled in two 
  ways: Passing a CLI long-form option `--auto-reload` or with short-form `-r`. Another 
  option, `--reload-interval <seconds>` controls how often LS should check the config files 
  for changes. Alternatively, if you don't start with the CLI option, you can send SIGHUP 
  or `kill -1` signal to LS to reload the config file, and restart the pipeline ({lsissue}4513[Issue 4513]).
* Added support to evaluate environment variables inside the Logstash config. You can also specify a 
  default if the variable is not defined. The syntax is `${myVar:default}` ({lsissue}3944[Issue 3944]).
* Improved throughput performance across the board (up by 2x in some configs) by implementing Event 
  representation in Java. Event is the main object that encapsulates data as it flows through 
  Logstash and provides APIs for the plugins to perform processing. This change also enables 
  faster serialization for future persistence work ({lsissue}4191[Issue 4191]).
* Added ability to configure custom garbage collection log file using `$LS_LOG_DIR`.
* Deprecated `bin/plugin` in favor of `bin/logstash-plugin`. In the next major version `bin/plugin` will 
  be removed to prevent `PATH` being polluted when other components of the Elastic stack are installed on 
  the same instance ({lsissue}4891[Issue 4891]).
* Fixed a bug where new pipeline might break plugins by calling the `register` method twice causing 
  undesired behavior ({lsissue}4851[Issue 4851])).
* Made `JAVA_OPTS` and `LS_JAVA_OPTS` work consistently on Windows ({lsissue}4758[Issue 4758]).
* Fixed bug where specifying JMX parameters in `LS_JAVA_OPTS` caused Logstash not to restart properly
  ({lsissue}4319[Issue 4319]).
* Fixed a bug where upgrading plugins with Manticore threw an error and sometimes corrupted installation ({lsissue}4818[Issue 4818]).
* Removed milestone warning that was displayed when the `--pluginpath` option was used to load plugins ({lsissue}4562[Issue 4562]).
* Upgraded to JRuby 1.7.24.

[float]
== Input Plugins

*`Beats`*:

* Enhanced to verify client certificates against CA (https://github.com/logstash-plugins/logstash-input-beats/issues/8[Issue 8]).

*'RabbitMQ`*:

* Breaking Change: Metadata is now disabled by default because it was regressing performance.
* Improved performance by using an internal queue and bulk ACKs.

*`Redis`*:

* Increased the batch_size to 100 by default. This provides a big jump in throughput and 
  reduction in CPU utilization (https://github.com/logstash-plugins/logstash-input-redis/issues/25[Issue 25])

*`JDBC`*:

* Added retry connection feature (https://github.com/logstash-plugins/logstash-input-http/issues/33[Issue 33])

[float]
== Filter Plugins

*`DNS`*:

* Improved performance by adding caches to both successful and failed requests.
* Added support for retrying with the `:max_retries` setting.
* Lowered the default value of timeout from 2 to 0.5 seconds.

[float]
== Output Plugins

*`Elasticsearch`*:

* Bumped minimum manticore version to 0.5.4 which fixes a memory leak when sniffing 
  is used (https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/392[Issue 392]).
* Fixed bug when updating documents with doc_as_upsert and scripting.   
* Made error messages more verbose and easier to parse by humans.
* Retryable failures are now logged at the info level instead of warning.

*`file`*:

* https://github.com/logstash-plugins/logstash-output-file/issues/18[Issue 18] Adds configuration setting to set directory
and file permission.
