[[releasenotes]]
== Release Notes

coming[8.0.0]

This section summarizes the changes in the following releases:

* <<logstash-8-0-0-rc2,Logstash 8.0.0-rc2>>
* <<logstash-8-0-0-rc1,Logstash 8.0.0-rc1>>
* <<logstash-8-0-0-beta1,Logstash 8.0.0-beta1>>
* <<logstash-8-0-0-alpha2,Logstash 8.0.0-alpha2>>
* <<logstash-8-0-0-alpha1,Logstash 8.0.0-alpha1>>

[[logstash-8-0-0-rc2]]
=== Logstash 8.0.0-rc2 Release Notes

==== New features and enhancements
This release is mainly a consolidation of the code base.
It improves the upgrade path reducing deprecation noise in Elastic Upgrade Assistant (#13563).
Fixed long-standing issue with event's count exposed in metrics when the events are dropped from pipelines (#13593).
Mitigates a memory leak that can be caused by using UUIDs or other high-cardinality field names. (#13642)
Some improvements in Logstash bootstrap phase, logging the JVM flags used (#13531) and respecting
LS_JAVA_OPTS environment even when `jvm.option` file missing (#13525).

Fixed an issue with Azure input plugin, that when used in a pipeline made Logstash to crash (#13603).
Consolidation of the test infrastructure: #13628, #13631, #13641, #13661, #13656.

==== Plugin releases
Plugins align with release 7.17.0


[[logstash-8-0-0-rc1]]
=== Logstash 8.0.0-rc1 Release Notes

==== Breaking changes

[[rn-ecs-compatibility]]
===== ECS compatibility 
Many plugins can now be run in a mode that avoids implicit conflict with the Elastic Common Schema (ECS). This mode is controlled individually with each plugin’s ecs_compatibility option, which defaults to the value of the Logstash pipeline.ecs_compatibility setting. In Logstash 8, this compatibility mode will be on-by-default for all pipelines.

If you wish to lock in a pipeline’s behavior from Logstash 7.x before upgrading to Logstash 8, you can set pipeline.ecs_compatibility: disabled to its definition in pipelines.yml (or globally in logstash.yml).

==== New features and enhancements

Logstash Docker images are now based on Ubuntu 20.04.

==== Plugin releases
Plugins align with release 7.16.2


[[logstash-8-0-0-beta1]]
=== Logstash 8.0.0-beta1 Release Notes

==== Breaking changes

[[rn-java-11-minimum]]
===== Java 11 minimum
Starting from Logstash 8.0, the minimum required version of Java to run Logstash is Java 11. By default, Logstash will
run with the bundled JDK, which has been verified to work with each specific version of Logstash, and generally
provides the best performance and reliability.

See <<breaking-changes>> for a preview of additional breaking changes coming your way. 

==== New features and enhancements

[[rn-nanosecond-precision]]
===== Nanosecond precision
As processing times speed up, millisecond granularity is not always enough. Inbound data increasingly has sub-millisecond granularity timestamps.
The pull request https://github.com/elastic/logstash/pull/12797[#12797] allows the internal mechanisms of Logstash that hold moment-in-time data - such as the Logstash Event, the Persistent Queue, the Dead Letter Queue and JSON encoding/decoding - to have nanosecond granularity.

Timestamp precision is limited to the JVM and Platform's available granularity, which in many cases is microseconds.

This change also grants users access to https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns[Java time's improved formatters], which include support fort ISO quarters, week-of-month, and a variety of timezone/offset-related format substitutions. For example:

[source,json]
--------------------------------------------------------------------------------
filter {
  mutate {
    add_field => {"nanos" => "Nanos: %{{n}}" }
  }
}
--------------------------------------------------------------------------------

Results in the following event:

[source,json]
--------------------------------------------------------------------------------
{
    "@timestamp" => 2021-10-31T22:32:34.747968Z,
          "host" => "logstash.lan",
         "nanos" => "Nanos: 747968000",
       "message" => "test",
          "type" => "stdin",
      "@version" => "1"
}
--------------------------------------------------------------------------------

==== Plugin releases
Plugins align with release 7.15.1


[[logstash-8-0-0-alpha2]]
=== Logstash 8.0.0-alpha2 Release Notes

==== Breaking changes

[[java-home-breaking-change]]
===== Removed support for JAVA_HOME
Support for using `JAVA_HOME` to override the path to the JDK that Logstash runs with has been removed for this release.
In the `8.x` release, users should set the value of `LS_JAVA_HOME` to the path of their preferred JDK if they
wish to use a version other than the bundled JDK. The value of `JAVA_HOME` will be ignored.

==== Plugin releases
Plugins align with release 7.15.0

[[logstash-8-0-0-alpha1]]
=== Logstash 8.0.0-alpha1 Release Notes

==== Breaking changes

[[ruby-engine]]
===== Ruby Execution Engine removed
The Java Execution Engine has been the default engine since Logstash 7.0, and works with plugins written in either Ruby or Java.
Removal of the Ruby Execution Engine will not affect the ability to run existing pipelines. https://github.com/elastic/logstash/pull/12517[#12517]

[[utf-16]]
===== Support for UTF-16
We have added support for UTF-16 and other multi-byte-character when reading log files. https://github.com/elastic/logstash/pull/9702[#9702]

[[field-ref-parser]]
===== Field Reference parser removed
The Field Reference parser interprets references to fields in your pipelines and
plugins. It was configurable in 7.x, with the default set to strict to reject
inputs that are ambiguous or illegal. Configurability is removed in 8.0. Now
{ls} rejects ambiguous and illegal inputs as standard behavior. https://github.com/elastic/logstash/pull/12466[#12466]

==== New features and enhancements

**Option to pass custom data to the benchmark CLI**

We have added another flag to the Benchmark CLI to allow passing a data file with previously captured data to the custom test case.
This feature allows users to run the Benchmark CLI in a custom test case with a custom config and a custom dataset. https://github.com/elastic/logstash/pull/12437[#12437]

==== Plugin releases
Plugins align with release 7.14.0