[[releasenotes]]
== Release Notes

coming[8.0.0]
---------- GENERATED CONTENT STARTS HERE ------------
=== Logstash Pull Requests with label v8.0.0

* Remove unused NodeStats#mem_payload https://github.com/elastic/logstash/pull/9051[#9051]
* Central management typeless API https://github.com/elastic/logstash/pull/10421[#10421]
* remove exclusive lock for Ruby pipeline initialization https://github.com/elastic/logstash/pull/10431[#10431]
* cleanup rake tasks and default plugin list https://github.com/elastic/logstash/pull/10509[#10509]
* update to send api version 6 https://github.com/elastic/logstash/pull/10518[#10518]
* Update monitoring HTTP end point https://github.com/elastic/logstash/pull/10528[#10528]
* monitoring: bump to system_api_version 7 https://github.com/elastic/logstash/pull/10535[#10535]
* move download setup code inside the downloadEs task https://github.com/elastic/logstash/pull/10547[#10547]
* make monitoring specs resilient to internal api number changes https://github.com/elastic/logstash/pull/10552[#10552]
* correctly handle unexecuted downloadEs task https://github.com/elastic/logstash/pull/10555[#10555]
* Native support for Java plugins (GA) https://github.com/elastic/logstash/pull/10560[#10560]
* Refactoring of LIR serializer and exposing pipeline metrics https://github.com/elastic/logstash/pull/10561[#10561]
* monitoring: bump to system_api_version 7 https://github.com/elastic/logstash/pull/10562[#10562]
* Enhance GET _node/stats/pipelines API for Metricbeat monitoring https://github.com/elastic/logstash/pull/10576[#10576]
*  Enhance `GET /` API for Metricbeat https://github.com/elastic/logstash/pull/10589[#10589]
* Update JRuby and Java prerequisites https://github.com/elastic/logstash/pull/10604[#10604]
* Collect and expose codec metrics https://github.com/elastic/logstash/pull/10614[#10614]
* Handle duplicate config entries https://github.com/elastic/logstash/pull/10619[#10619]
* Native support for Java plugins (GA) https://github.com/elastic/logstash/pull/10620[#10620]
* Log successful shutdowns https://github.com/elastic/logstash/pull/10628[#10628]
* Refactor Gradle wrappers around Ruby operations https://github.com/elastic/logstash/pull/10642[#10642]
* [DOCS] Adds tagged region for notable breaking changes https://github.com/elastic/logstash/pull/10654[#10654]
* download exact version artifact for release build otherwise download snapshot https://github.com/elastic/logstash/pull/10664[#10664]
* Fix default codec and buffer handling in Java stdout output https://github.com/elastic/logstash/pull/10673[#10673]
* Corrects the description of codec behavior in the output stage of Logstash pipelines https://github.com/elastic/logstash/pull/10682[#10682]
* Correct settings file doc to note that Java execution defaults to true https://github.com/elastic/logstash/pull/10701[#10701]
* Correction on Java execution in docs on command-line arguments https://github.com/elastic/logstash/pull/10710[#10710]
* Clarify that Java codecs work only with Java inputs and outputs https://github.com/elastic/logstash/pull/10716[#10716]
* Include G1 in JVM heap metrics https://github.com/elastic/logstash/pull/10728[#10728]
* JRuby resolv.rb leak https://github.com/elastic/logstash/pull/10734[#10734]

=== Logstash Commits between 8.0 and v8.0.0-alpha2

Computed with "git log --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit --date=relative vv8.0.0-alpha2..8.0"

=== Logstash Plugin Release Changelogs ===
Computed from "git diff vv8.0.0-alpha2..8.0 *.release"
Changed plugin versions:
---------- GENERATED CONTENT ENDS HERE ------------

==== Plugins


* <<logstash-8-0-0,Logstash 8.0.0>>
This section summarizes the changes in the following releases:

* <<logstash-8-0-0-alpha2,Logstash 8.0.0-alpha2>>
* <<logstash-8-0-0-alpha1,Logstash 8.0.0-alpha1>>

[[logstash-8-0-0-alpha2]]
=== Logstash 8.0.0-alpha2 Release Notes

==== Breaking changes

[[java-home-breaking-change]]
===== Removed support for JAVA_HOME
Support for using `JAVA_HOME` to override the path to the JDK that Logstash runs with has been removed for this release.
In the `8.x` release, users should set the value of `LS_JAVA_HOME` to the path of their preferred JDK if they
wish to use a version other than the bundled JDK. The value of `JAVA_HOME` will be ignored.

==== Plugin releases
Plugins align with release 7.15.0

[[logstash-8-0-0-alpha1]]
=== Logstash 8.0.0-alpha1 Release Notes

==== Breaking changes

[[ruby-engine]]
===== Ruby Execution Engine removed
The Java Execution Engine has been the default engine since Logstash 7.0, and works with plugins written in either Ruby or Java.
Removal of the Ruby Execution Engine will not affect the ability to run existing pipelines. https://github.com/elastic/logstash/pull/12517[#12517]

[[utf-16]]
===== Support for UTF-16
We have added support for UTF-16 and other multi-byte-character when reading log files. https://github.com/elastic/logstash/pull/9702[#9702]

[[field-ref-parser]]
===== Field Reference parser removed
The Field Reference parser interprets references to fields in your pipelines and
plugins. It was configurable in 7.x, with the default set to strict to reject
inputs that are ambiguous or illegal. Configurability is removed in 8.0. Now
{ls} rejects ambiguous and illegal inputs as standard behavior. https://github.com/elastic/logstash/pull/12466[#12466]

==== New features and enhancements

**Option to pass custom data to the benchmark CLI**

We have added another flag to the Benchmark CLI to allow passing a data file with previously captured data to the custom test case.
This feature allows users to run the Benchmark CLI in a custom test case with a custom config and a custom dataset. https://github.com/elastic/logstash/pull/12437[#12437]

==== Plugin releases
Plugins align with release 7.14.0