[[releasenotes]]
== Release Notes

This section summarizes the changes in the following releases:

* <<logstash-5-6-6,Logstash 5.6.6>>
* <<logstash-5-6-5,Logstash 5.6.5>>
* <<logstash-5-6-4,Logstash 5.6.4>>
* <<logstash-5-6-3,Logstash 5.6.3>>
* <<logstash-5-6-2,Logstash 5.6.2>>
* <<logstash-5-6-1,Logstash 5.6.1>>
* <<logstash-5-6-0,Logstash 5.6.0>>

[[logstash-5-6-6]]
=== Logstash 5.6.6 Release Notes
* Fixed a bug where cloning a LogStash Timestamp object would result in an empty object
* Changed option validation to occur before checking for deprecation/obsoletion

[[logstash-5-6-5]]
=== Logstash 5.6.5 Release Notes
* Fixed a bug where persistent queue could not be opened when in some states
* Improved shutdown process by ensuring that Logstash terminates on second SIGINT. Prior to this release, there were some situations where executing two SIGNINTs would not kill Logstash.

[[logstash-5-6-4]]
=== Logstash 5.6.4 Release Notes
* Fix bug where setting `log.level=debug` would cause Logstash to crash
* Fix bug where queues configured to use a single page would not be able to process events. This also wound up being a small perf boost. https://github.com/elastic/logstash/pull/8275[#8275]
* Fix bug where a `0` exit status could be emitted when exiting due to an error by the `logstash-plugin.bat` command on windows.

[[logstash-5-6-3]]
=== Logstash 5.6.3 Release Notes

* Known Issue: Running Logstash with log level set to debug will cause the pipeline to crash
* Improved pipeline performance
* Fixed issue where DLQ would crash at startup when a segment file was missing
* Fixed issues with proxy handling when installing plugins

[[logstash-5-6-2]]
=== Logstash 5.6.2 Release Notes

* Fix a regression where `Event.clone` would not clone event metadata
* https://github.com/elastic/logstash/pulls?utf8=%E2%9C%93&q=is%3Apr%20label%3Av5.6.2%20is%3Aclosed%20label%3Abug%20[Various minor bug fixes]

[[logstash-5-6-1]]
=== Logstash 5.6.1 Release Notes

* There are no user-facing changes in this release

[[logstash-5-6-0]]
=== Logstash 5.6.0 Release Notes

* Introduced modules for Netflow and ArcSight data. Modules contain pre-packaged Logstash configuration, Kibana dashboards 
  and other metadata files to ease the set up of the Elastic stack for certain data sources. The goal of these modules are 
  to provide an end-to-end, 5-min getting started experience for a user exploring a data source.
* Added a new setting called `config.support_escapes`. This setting enables the use of escape characters such as `\n` in 
  the Logstash configuration.
* Improved the performance of metrics collection and reporting infrastructure. Overall, in this release, there is lower load 
  average, less GC and higher throughput when running Logstash.
* When processing events from the DLQ, there are added checks now to stop them from being written to the DLQ again.
* Fixed an issue which would crash Logstash when accessing DLQ events using a timestamp range.

[float]
==== Filter Plugins

*`GeoIP`*: The free GeoIPLite2-ASN database from MaxMind is now bundled in Logstash to be able to look up ASN data out 
  of the box.


