[[running-logstash]]
=== Running {ls} as a Service on Debian or RPM

{ls} is not started automatically after installation. Starting and stopping {ls} depends on the
init system of the underlying operating system, which is now systemd.

As systemd is now the de-facto init system, here are some common operating systems and versions that
use it.  This list is intended to be informative, not exhaustive.

|=======================================================================
| Distribution | Service System |
| Ubuntu 16.04 and newer | <<running-logstash-systemd,systemd>> |
| Debian 8 "jessie" and newer | <<running-logstash-systemd,systemd>> |
| CentOS (and RHEL) 7 and newer | <<running-logstash-systemd,systemd>> |
|=======================================================================

[[running-logstash-systemd]]
==== Running {ls} by Using Systemd

Distributions like Debian Jessie, Ubuntu 15.10+, and many of the SUSE derivatives use systemd and the
`systemctl` command to start and stop services. {ls} places the systemd unit files in `/etc/systemd/system` for both deb and rpm. After installing the package, you can start up {ls} with:

[source,sh]
-------------------------------------------
sudo systemctl start logstash.service
-------------------------------------------

