---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - '/'
      - '/.github/actions/*'
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      github-actions:
        patterns:
          - "*"
