AllCops:
  RubyInterpreters:
    - ruby
    - rake
    - jruby
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'build/**/*'
    - 'config/**/*'
  DisplayCopNames: true
  UseCache: false

#################### Lint   ###########################
##### Enabled Cops #####
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/ErbNewArguments:
  Enabled: true
Lint/BigDecimalNew:
  Enabled: true

#################### Layout ###########################
##### Enabled/Disabled Cops #####
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: true
Layout/EmptyLineAfterMultilineCondition:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  EnabLEd: true
Layout/EmptyLines:
  Enabled: true
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/EmptyLinesAroundArguments:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EmptyLinesAroundBeginBody:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true
Layout/EmptyLinesAroundMethodBody:
  Enabled: true
Layout/EmptyLinesAroundModuleBody:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
Layout/SpaceAfterColon:
  Enabled: true
Layout/SpaceAfterComma:
  Enabled: true
Layout/SpaceAfterSemicolon:
  Enabled: true
Layout/SpaceAroundBlockParameters:
  Enabled: true
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
Layout/SpaceAroundKeyword:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: true
Layout/SpaceBeforeBlockBraces:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Layout/SpaceBeforeComma:
  Enabled: true
Layout/SpaceBeforeComment:
  Enabled: true
Layout/SpaceBeforeFirstArg:
  Enabled: true
Layout/SpaceBeforeSemicolon:
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space
Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true # no offenses
Layout/SpaceInsideParens:
  Enabled: true
  EnforcedStyle: no_space
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true
Layout/SpaceInsideRangeLiteral:
  Enabled: true # no offenses
Layout/SpaceInsideReferenceBrackets:
  Enabled: true # no offenses
Layout/SpaceInsideStringInterpolation:
  Enabled: true
  EnforcedStyle: no_space

##### Need review #####
Layout/AccessModifierIndentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: false
Layout/AssignmentIndentation:
  Enabled: false
Layout/BeginEndAlignment:
  Enabled: false
Layout/BlockAlignment:
  Enabled: false
Layout/BlockEndNewline:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/ClassStructure:
  Enabled: false
Layout/ClosingHeredocIndentation:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/ConditionPosition:
  Enabled: false
Layout/DefEndAlignment:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyComment:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/FirstArrayElementLineBreak:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/FirstHashElementLineBreak:
  Enabled: false
Layout/FirstMethodArgumentLineBreak:
  Enabled: false
Layout/FirstMethodParameterLineBreak:
  Enabled: false
Layout/FirstParameterIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/HeredocArgumentClosingParenthesis:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Layout/IndentationStyle:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/InitialIndentation:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/LeadingEmptyLines:
  Enabled: false
Layout/LineContinuationLeadingSpace:
  Enabled: false
Layout/LineContinuationSpacing:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/MultilineArrayBraceLayout:
  Enabled: false
Layout/MultilineArrayLineBreaks:
  Enabled: false
Layout/MultilineAssignmentLayout:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false
Layout/MultilineHashBraceLayout:
  Enabled: false
Layout/MultilineHashKeyLineBreaks:
  Enabled: false
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false
Layout/MultilineMethodParameterLineBreaks:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/RedundantLineBreak:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/SingleLineBlockChain:
  Enabled: false
Layout/SpaceAfterMethodName:
  Enabled: false
Layout/SpaceAfterNot:
  Enabled: false
Layout/SpaceInLambdaLiteral:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
