Style/Encoding:
  Enabled: false

AllCops:
  Include:
    - 'lib/**/*'
    - 'rakelib/**/*'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'acceptance_spec/**/*'
    - 'bin/**/*'
    - 'bot/**/*'
