---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: logstash
  description: Logstash is a server-side data processing pipeline that ingests data from a multitude of sources simultaneously, transforms it, and then sends it to your favorite "stash."
  links:
    - title: Logstash
      url: https://elastic.co/logstash
spec:
  type: tool
  owner: group:ingest-fp
  system: platform-ingest

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-logstash-serverless-integration-testing
  description: Buildkite pipeline for the Serverless Integration Test
spec:
  type: buildkite-pipeline
  owner: group:ingest-fp
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: logstash-serverless-integration-testing
    spec:
      repository: elastic/logstash
      pipeline_file: ".buildkite/serverless_integration_pipeline.yml"
      provider_settings:
        trigger_mode: none # don't trigger jobs from github activity
      env:
        ELASTIC_SLACK_NOTIFICATIONS_ENABLED: 'true'
        SLACK_NOTIFICATIONS_CHANNEL: '#logstash-build'
        SLACK_NOTIFICATIONS_ON_SUCCESS: 'false'
      teams:
        ingest-fp:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      schedules:
        Daily serverless test on core_serverless_test branch:
          branch: core_serverless_test
          cronline: "@daily"
          message: "Run the serverless integration test every day."
