# *************************************************************
# Declare Backstage Component that represents the Logstash tool
# *************************************************************
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: logstash
  description: Logstash is a server-side data processing pipeline that ingests data from a multitude of sources simultaneously, transforms it, and then sends it to your favorite "stash."
  annotations:
    backstage.io/source-location: url:https://github.com/elastic/logstash/
    github.com/project-slug: elastic/logstash
    github.com/team-slug: elastic/logstash
    buildkite.com/project-slug: elastic/logstash
  tags:
    - logstash
    - dra
  links:
    - title: Logstash
      url: https://elastic.co/logstash
spec:
  type: tool
  owner: group:ingest-fp
  system: platform-ingest
  dependsOn:
    - resource:buildkite-logstash-serverless-integration-testing
    - resource:logstash-snyk-report
    - logstash-dra-snapshot-pipeline
    - logstash-dra-staging-pipeline

# ***********************************
# Declare serverless IT pipeline
# ***********************************
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-logstash-serverless-integration-testing
  description: Buildkite pipeline for the Serverless Integration Test
spec:
  type: buildkite-pipeline
  owner: group:ingest-fp
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: logstash-serverless-integration-testing
    spec:
      repository: elastic/logstash
      pipeline_file: ".buildkite/serverless_integration_pipeline.yml"
      provider_settings:
        trigger_mode: none # don't trigger jobs from github activity
      env:
        ELASTIC_SLACK_NOTIFICATIONS_ENABLED: 'true'
        SLACK_NOTIFICATIONS_CHANNEL: '#logstash-build'
        SLACK_NOTIFICATIONS_ON_SUCCESS: 'false'
      teams:
        ingest-fp:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      schedules:
        Daily serverless test on core_serverless_test branch:
          branch: main
          cronline: "@daily"
          message: "Run the serverless integration test every day."


# ***********************************
# Declare snyk-repo pipeline
# ***********************************
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: logstash-snyk-report
  description: 'The logstash-snyk-report pipeline.'
spec:
  type: buildkite-pipeline
  owner: group:ingest-fp
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: logstash-snyk-report-ci
      description: ':logstash: The logstash-snyk-report :pipeline:'
    spec:
      repository: elastic/logstash
      pipeline_file: ".buildkite/snyk_report_pipeline.yml"
      provider_settings:
        trigger_mode: none # don't trigger jobs
      env:
        ELASTIC_SLACK_NOTIFICATIONS_ENABLED: 'true'
        SLACK_NOTIFICATIONS_CHANNEL: '#logstash-build'
        SLACK_NOTIFICATIONS_ON_SUCCESS: 'false'
      teams:
        ingest-fp:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      schedules:
        Daily Snyk scan:
          branch: main
          cronline: "@daily"
          message: "Run the Logstash Snyk report every day."

# ***********************************
# SECTION START: DRA pipelines
# ***********************************

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: logstash-dra-snapshot-pipeline
  description: 'Logstash DRA SNAPSHOT (Daily, Auto) pipeline'
  links:
    - title: 'Logstash DRA SNAPSHOT (Daily, Auto) pipeline'
      url: https://buildkite.com/elastic/logstash-dra-snapshot-pipeline
spec:
  type: buildkite-pipeline
  owner: group:logstash
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: logstash-dra-snapshot-pipeline
      description: ':logstash: The DRA SNAPSHOT (Daily, Auto) pipeline'
    spec:
      repository: elastic/logstash
      pipeline_file: ".buildkite/dra_pipeline.yml"
      # TODO: uncomment out the schedule after testing + disabling Jenkins Job
      # schedules:
      #   Daily 7_17:
      #     branch: '7.17'
      #     cronline: 30 01 * * *
      #     message: Daily SNAPSHOT build for 7.17 
      #   Daily 8_10:
      #     branch: '8.10'
      #     cronline: 30 01 * * *
      #     message: Daily SNAPSHOT build for 8.10 
      #   Daily main:
      #     branch: main
      #     cronline: 30 01 * * *
      #     message: Daily SNAPSHOT build for main
      skip_intermediate_builds: true
      provider_settings:
        trigger_mode: none
      env:
        WORKFLOW_TYPE: 'snapshot'
        ELASTIC_SLACK_NOTIFICATIONS_ENABLED: 'false' # don't alert during development
        SLACK_NOTIFICATIONS_CHANNEL: '#logstash-build'
        SLACK_NOTIFICATIONS_ON_SUCCESS: 'false'
      teams:
        ingest-fp:
          access_level: MANAGE_BUILD_AND_READ
        logstash:
          access_level: MANAGE_BUILD_AND_READ
        ingest-eng-prod:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: logstash-dra-staging-pipeline
  description: 'Logstash DRA RELEASE (Staging) pipeline'
  links:
    - title: 'Logstash DRA RELEASE (Staging) pipeline'
      url: https://buildkite.com/elastic/logstash-dra-staging-pipeline
spec:
  type: buildkite-pipeline
  owner: group:logstash
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: logstash-dra-staging-pipeline
      description: ':logstash: The DRA RELEASE (Staging) pipeline'
    spec:
      repository: elastic/logstash
      pipeline_file: ".buildkite/dra_pipeline.yml"
      skip_intermediate_builds: true
      provider_settings:
        trigger_mode: none
      env:
        WORKFLOW_TYPE: 'staging'
        ELASTIC_SLACK_NOTIFICATIONS_ENABLED: 'false' # don't alert during development
        SLACK_NOTIFICATIONS_CHANNEL: '#logstash-build'
        SLACK_NOTIFICATIONS_ON_SUCCESS: 'false'
      teams:
        ingest-fp:
          access_level: MANAGE_BUILD_AND_READ
        logstash:
          access_level: MANAGE_BUILD_AND_READ
        ingest-eng-prod:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

# ***********************************
# SECTION END: DRA pipelines
# ***********************************

# ********************************************
# Declare supported plugin tests pipeline
# ********************************************
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: 'Logstash supported plugins test pipeline'
  description: "Execute spec tests af all supported tier1 and tier2 plugins using the current branch's Logstash"
  links:
    - title: 'Logstash supported plugins test pipeline'
      url: https://buildkite.com/elastic/logstash-supported-plugins-test-pipeline
spec:
  type: buildkite-pipeline
  owner: group:logstash
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: 'Logstash supported plugins test pipeline'
      description: ':logstash: Supported plugins test pipeline'
    spec:
      repository: elastic/logstash
      pipeline_file: ".buildkite/supported_plugins_test_pipeline.yml"
      skip_intermediate_builds: true
      provider_settings:
        trigger_mode: none
      teams:
        ingest-fp:
          access_level: MANAGE_BUILD_AND_READ
        logstash:
          access_level: MANAGE_BUILD_AND_READ
        ingest-eng-prod:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY