---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-logstash
  description: Buildkite Pipeline for logstash
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/logstash

spec:
  type: buildkite-pipeline
  owner: group:logstash
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: logstash
    spec:
      repository: elastic/logstash
      pipeline_file: ".buildkite/serverless_integration_pipeline.yml"
      teams:
        logstash:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
        schedules:
          Daily Benchmark on main Branch:
            cronline: "@hourly"
            message: "Run the quick benchmark every day."
