---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: logstash
  description: Logstash is a server-side data processing pipeline that ingests data from a multitude of sources simultaneously, transforms it, and then sends it to your favorite "stash."
  links:
    - title: Logstash
      url: https://elastic.co/logstash
spec:
  type: tool
  owner: group:ingest-fp
  system: platform-ingest

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: buildkite.elastic.dev/v1
kind: Pipeline
metadata:
  name: logstash-serverless-integration-testing
spec:
  repository: elastic/logstash
  pipeline_file: ".buildkite/serverless_integration_pipeline.yml"
  teams:
    ingest-fp:
      access_level: MANAGE_BUILD_AND_READ
    everyone:
      access_level: READ_ONLY
    schedules:
      Daily Benchmark on main Branch:
        cronline: "@hourly"
        message: "Run the quick benchmark every day."
