# This is a Logstash generated Gemfile.
# If you modify this file manually all comments and formatting will be lost.

source "https://rubygems.org"
gem "logstash-core", :path => "./logstash-core"
gem "logstash-core-plugin-api", :path => "./logstash-core-plugin-api"
gem "paquet", "~> 0.2"
gem "pleaserun", "~>0.0.28", :require => false
gem "rake", "~> 13", :require => false
gem "ruby-progressbar", "~> 1", :require => false
gem "logstash-output-elasticsearch", ">= 11.14.0"
gem "polyglot", :require => false
gem "treetop", :require => false
gem "faraday", "~> 1", :require => false
gem "childprocess", "~> 4", :group => :build
gem "fpm", "~> 1", ">= 1.14.1", :group => :build
gem "gems", "~> 1", :group => :build
gem "octokit", "~> 4.25", :group => :build
gem "rubyzip", "~> 1", :group => :build
gem "stud", "~> 0.0.22", :group => :build
gem "rubocop", :group => :development
gem "belzebuth", :group => :development
gem "benchmark-ips", :group => :development
gem "ci_reporter_rspec", "~> 1", :group => :development
gem "flores", "~> 0.0.8", :group => :development
gem "json-schema", "~> 2", :group => :development
gem "logstash-devutils", "~> 2", :group => :development
gem "rack-test", :require => "rack/test", :group => :development
gem "rspec", "~> 3.5", :group => :development
gem "webmock", "~> 3", :group => :development
gem "jar-dependencies", "~> 0.3"
gem "murmurhash3", "= 0.1.6"
gem "thwait"
gem "bigdecimal", "~> 3.1"
gem "logstash-codec-avro"
gem "logstash-codec-cef"
gem "logstash-codec-collectd"
gem "logstash-codec-dots"
gem "logstash-codec-edn"
gem "logstash-codec-edn_lines"
gem "logstash-codec-es_bulk"
gem "logstash-codec-fluent"
gem "logstash-codec-graphite"
gem "logstash-codec-json", "3.1.1", :path => "vendor/local_gems/a067c17e/logstash-codec-json-3.1.1"
gem "logstash-codec-json_lines"
gem "logstash-codec-line", ">= 2.1.0"
gem "logstash-codec-msgpack"
gem "logstash-codec-multiline"
gem "logstash-codec-netflow"
gem "logstash-codec-plain"
gem "logstash-codec-rubydebug"
gem "logstash-filter-aggregate"
gem "logstash-filter-anonymize"
gem "logstash-filter-cidr"
gem "logstash-filter-clone"
gem "logstash-filter-csv"
gem "logstash-filter-date"
gem "logstash-filter-de_dot"
gem "logstash-filter-dissect"
gem "logstash-filter-dns"
gem "logstash-filter-drop"
gem "logstash-filter-elasticsearch"
gem "logstash-filter-fingerprint"
gem "logstash-filter-geoip"
gem "logstash-filter-grok"
gem "logstash-filter-http"
gem "logstash-filter-json"
gem "logstash-filter-kv"
gem "logstash-filter-memcached"
gem "logstash-filter-metrics"
gem "logstash-filter-mutate"
gem "logstash-filter-prune"
gem "logstash-filter-ruby"
gem "logstash-filter-sleep"
gem "logstash-filter-split"
gem "logstash-filter-syslog_pri"
gem "logstash-filter-throttle"
gem "logstash-filter-translate"
gem "logstash-filter-truncate"
gem "logstash-filter-urldecode"
gem "logstash-filter-useragent"
gem "logstash-filter-uuid"
gem "logstash-filter-xml"
gem "logstash-input-azure_event_hubs", "1.4.5", :path => "vendor/local_gems/4d23c53d/logstash-input-azure_event_hubs-1.4.5"
gem "logstash-input-beats"
gem "logstash-input-couchdb_changes"
gem "logstash-input-dead_letter_queue"
gem "logstash-input-elasticsearch"
gem "logstash-input-exec"
gem "logstash-input-file", "4.4.5", :path => "vendor/local_gems/900566b3/logstash-input-file-4.4.5"
gem "logstash-input-ganglia"
gem "logstash-input-gelf"
gem "logstash-input-generator"
gem "logstash-input-graphite"
gem "logstash-input-heartbeat"
gem "logstash-input-http"
gem "logstash-input-http_poller"
gem "logstash-input-imap"
gem "logstash-input-jms"
gem "logstash-input-pipe"
gem "logstash-input-redis"
gem "logstash-input-snmp"
gem "logstash-input-snmptrap"
gem "logstash-input-stdin"
gem "logstash-input-syslog"
gem "logstash-input-tcp"
gem "logstash-input-twitter"
gem "logstash-input-udp", "3.5.0", :path => "vendor/local_gems/0988d561/logstash-input-udp-3.5.0"
gem "logstash-input-unix"
gem "logstash-integration-elastic_enterprise_search"
gem "logstash-input-elastic_serverless_forwarder"
gem "logstash-integration-jdbc"
gem "logstash-integration-kafka"
gem "logstash-integration-logstash"
gem "logstash-integration-rabbitmq"
gem "logstash-integration-aws"
gem "logstash-output-csv"
gem "logstash-output-email"
gem "logstash-output-file"
gem "logstash-output-graphite"
gem "logstash-output-http"
gem "logstash-output-lumberjack"
gem "logstash-output-nagios"
gem "logstash-output-null"
gem "logstash-output-pipe"
gem "logstash-output-redis"
gem "logstash-output-stdout"
gem "logstash-output-tcp"
gem "logstash-output-udp"
gem "logstash-output-webhdfs"
gem "insist", ">= 0"
gem "cabin", "~> 0.6"
gem "webrick", ">= 0"
gem "logstash-patterns-core", ">= 0"
gem "rspec-sequencing", ">= 0"
gem "rspec-wait", ">= 0"
gem "pry", ">= 0"
gem "ftw", "~> 0.0.42"
gem "timecop", ">= 0"
gem "rufus-scheduler", "~> 3.0.9"
gem "gmetric", ">= 0"
gem "gelf", "= 3.0.0"
gem "manticore", ">= 0"
gem "jdbc-derby", ">= 0"
gem "digest-crc", "~> 0.5.1"
gem "ruby-kafka", ">= 0"
gem "snappy", ">= 0"
gem "rspec-collection_matchers", ">= 0"
gem "random-port", ">= 0"
gem "elasticsearch", ">= 0"
gem "rumbster", ">= 0"
gem "gserver", ">= 0"
gem "sinatra", ">= 0"
