# This is a Logstash generated Gemfile.
# If you modify this file manually all comments and formatting will be lost.

source "https://rubygems.org"
gem "logstash-core", :path => "./logstash-core"
gem "logstash-core-event-java", :path => "./logstash-core-event-java"
gem "logstash-core-plugin-api", :path => "./logstash-core-plugin-api"
gem "file-dependencies", "0.1.6"
gem "ci_reporter_rspec", "1.0.0", :group => :development
gem "simplecov", :group => :development
gem "coveralls", :group => :development
gem "tins", "1.6", :group => :development
gem "rspec", "~> 3.1.0", :group => :development
gem "logstash-devutils", :group => :development
gem "benchmark-ips", :group => :development
gem "octokit", "3.8.0", :group => :build
gem "stud", "~> 0.0.22", :group => :build
gem "fpm", "~> 1.3.3", :group => :build
gem "rubyzip", "~> 1.1.7", :group => :build
gem "gems", "~> 0.8.3", :group => :build
gem "rack-test", :require => "rack/test", :group => :development
gem "flores", "~> 0.0.6", :group => :development
gem "pleaserun"
gem "logstash-codec-collectd", "~> 3"
gem "logstash-codec-dots", "~> 3"
gem "logstash-codec-edn", "~> 3"
gem "logstash-codec-edn_lines", "~> 3"
gem "logstash-codec-es_bulk", "~> 3"
gem "logstash-codec-fluent", "~> 3"
gem "logstash-codec-graphite", "~> 3"
gem "logstash-codec-json", "~> 3"
gem "logstash-codec-json_lines", "~> 3"
gem "logstash-codec-line", "~> 3"
gem "logstash-codec-msgpack", "~> 3"
gem "logstash-codec-multiline", "~> 3"
gem "logstash-codec-netflow", "~> 3"
gem "logstash-codec-plain", "~> 3"
gem "logstash-codec-rubydebug", "~> 3"
gem "logstash-filter-clone", "~> 3"
gem "logstash-filter-csv", "~> 3"
gem "logstash-filter-date", "~> 3"
gem "logstash-filter-dns", "~> 3"
gem "logstash-filter-drop", "~> 3"
gem "logstash-filter-fingerprint", "~> 3"
gem "logstash-filter-geoip", "~> 4"
gem "logstash-filter-grok", "~> 3"
gem "logstash-filter-json", "~> 3"
gem "logstash-filter-kv", "~> 3"
gem "logstash-filter-metrics", "~> 4"
gem "logstash-filter-mutate", "~> 3"
gem "logstash-filter-ruby", "~> 3"
gem "logstash-filter-sleep", "~> 3"
gem "logstash-filter-split", "~> 3"
gem "logstash-filter-syslog_pri", "~> 3"
gem "logstash-filter-throttle", "~> 3"
gem "logstash-filter-urldecode", "~> 3"
gem "logstash-filter-useragent", "~> 3"
gem "logstash-filter-uuid", "~> 3"
gem "logstash-filter-xml", "~> 4"
gem "logstash-input-beats", "~> 3"
gem "logstash-input-couchdb_changes", "~> 3"
gem "logstash-input-elasticsearch", "~> 3"
gem "logstash-input-exec", "~> 3"
gem "logstash-input-file", "~> 3"
gem "logstash-input-ganglia", "~> 3"
gem "logstash-input-gelf", "~> 3"
gem "logstash-input-generator", "~> 3"
gem "logstash-input-graphite", "~> 3"
gem "logstash-input-heartbeat", "~> 3"
gem "logstash-input-http", "~> 3"
gem "logstash-input-http_poller", "~> 3"
gem "logstash-input-imap", "~> 3"
gem "logstash-input-irc", "~> 3"
gem "logstash-input-jdbc", "~> 4"
gem "logstash-input-kafka", "~> 4"
gem "logstash-input-log4j", "~> 3"
gem "logstash-input-lumberjack", "~> 3"
gem "logstash-input-pipe", "~> 3"
gem "logstash-input-rabbitmq", "~> 5"
gem "logstash-input-redis", "~> 3"
gem "logstash-input-s3", "~> 3"
gem "logstash-input-snmptrap", "~> 3"
gem "logstash-input-sqs", "~> 3"
gem "logstash-input-stdin", "~> 3"
gem "logstash-input-syslog", "~> 3"
gem "logstash-input-tcp", "~> 4"
gem "logstash-input-twitter", "~> 3"
gem "logstash-input-udp", "~> 3"
gem "logstash-input-unix", "~> 3"
gem "logstash-input-xmpp", "~> 3"
gem "logstash-output-cloudwatch", "~> 3"
gem "logstash-output-csv", "~> 3"
gem "logstash-output-elasticsearch", "~> 4"
gem "logstash-output-file", "~> 3"
gem "logstash-output-graphite", "~> 3"
gem "logstash-output-http", "~> 3"
gem "logstash-output-irc", "~> 3"
gem "logstash-output-kafka", "~> 4"
gem "logstash-output-nagios", "~> 3"
gem "logstash-output-null", "~> 3"
gem "logstash-output-pagerduty", "~> 3"
gem "logstash-output-pipe", "~> 3"
gem "logstash-output-rabbitmq", "~> 4"
gem "logstash-output-redis", "~> 3"
gem "logstash-output-s3", "~> 3"
gem "logstash-output-sns", "~> 4"
gem "logstash-output-sqs", "~> 3"
gem "logstash-output-statsd", "~> 3"
gem "logstash-output-stdout", "~> 3"
gem "logstash-output-tcp", "~> 3"
gem "logstash-output-udp", "~> 3"
gem "logstash-output-webhdfs", "~> 3"
gem "logstash-output-xmpp", "~> 3"
gem "logstash-patterns-core", "~> 4"
