# This is a Logstash generated Gemfile.
# If you modify this file manually all comments and formatting will be lost.

source "https://rubygems.org"
gem "logstash-core", "2.4.0"
gem "logstash-core-event", "2.4.0"
gem "logstash-core-plugin-api", "1.60.4"
gem "file-dependencies", "0.1.6"
gem "ci_reporter_rspec", "1.0.0", :group => :development
gem "simplecov", :group => :development
gem "coveralls", :group => :development
gem "tins", "1.6", :group => :development
gem "rspec", "~> 3.1.0", :group => :development
gem "logstash-devutils", "~> 0.0.15", :group => :development
gem "benchmark-ips", :group => :development
gem "octokit", "3.8.0", :group => :build
gem "stud", "~> 0.0.21", :group => :build
gem "fpm", "~> 1.3.3", :group => :build
gem "rubyzip", "~> 1.1.7", :group => :build
gem "gems", "~> 0.8.3", :group => :build
gem "flores", "~> 0.0.6", :group => :development
gem "logstash-input-heartbeat", "<3.0.0"
gem "logstash-output-zeromq", "<3.0.0"
gem "logstash-codec-collectd", "<3.0.0"
gem "logstash-output-xmpp", "<3.0.0"
gem "logstash-codec-dots", "<3.0.0"
gem "logstash-codec-edn", "<3.0.0"
gem "logstash-codec-edn_lines", "<3.0.0"
gem "logstash-codec-fluent", "<3.0.0"
gem "logstash-codec-es_bulk", "<3.0.0"
gem "logstash-codec-graphite", "<3.0.0"
gem "logstash-codec-json", "<3.0.0"
gem "logstash-codec-json_lines", "<3.0.0"
gem "logstash-codec-line", "<3.0.0"
gem "logstash-codec-msgpack", "<3.0.0"
gem "logstash-codec-multiline", "<3.0.0"
gem "logstash-codec-netflow", "<3.0.0"
gem "logstash-codec-oldlogstashjson", "<3.0.0"
gem "logstash-codec-plain", "<3.0.0"
gem "logstash-codec-rubydebug", "<3.0.0"
gem "logstash-filter-anonymize", "<3.0.0"
gem "logstash-filter-checksum", "<3.0.0"
gem "logstash-filter-clone", "<3.0.0"
gem "logstash-filter-csv", "<3.0.0"
gem "logstash-filter-date", "<3.0.0"
gem "logstash-filter-dns", "<3.0.0"
gem "logstash-filter-drop", "<3.0.0"
gem "logstash-filter-fingerprint", "<3.0.0"
gem "logstash-filter-geoip", "<3.0.0"
gem "logstash-filter-grok", "<3.0.0"
gem "logstash-filter-json", "<3.0.0"
gem "logstash-filter-kv", "<3.0.0"
gem "logstash-filter-metrics", "<4.0.0"
gem "logstash-filter-multiline", "<3.0.0"
gem "logstash-filter-mutate", "<3.0.0"
gem "logstash-filter-ruby", "<3.0.0"
gem "logstash-filter-sleep", "<3.0.0"
gem "logstash-filter-split", "<3.0.0"
gem "logstash-filter-syslog_pri", "<3.0.0"
gem "logstash-filter-throttle", "<3.0.0"
gem "logstash-filter-urldecode", "<3.0.0"
gem "logstash-filter-useragent", "<3.0.0"
gem "logstash-filter-uuid", "<3.0.0"
gem "logstash-filter-xml", "<3.0.0"
gem "logstash-input-couchdb_changes", "<3.0.0"
gem "logstash-input-elasticsearch", "<3.0.0"
gem "logstash-input-eventlog", "<4.0.0"
gem "logstash-input-exec", "<3.0.0"
gem "logstash-input-file", "<3.0.0"
gem "logstash-input-ganglia", "<3.0.0"
gem "logstash-input-gelf", "<3.0.0"
gem "logstash-input-generator", "<3.0.0"
gem "logstash-input-graphite", "<3.0.0"
gem "logstash-input-http", "<3.0.0"
gem "logstash-input-imap", "<3.0.0"
gem "logstash-input-irc", "<3.0.0"
gem "logstash-input-jdbc", "<4.0.0"
gem "logstash-input-log4j", "<3.0.0"
gem "logstash-input-lumberjack", "<3.0.0"
gem "logstash-input-pipe", "<3.0.0"
gem "logstash-input-rabbitmq", "<5.0.0"
gem "logstash-input-redis", "<3.0.0"
gem "logstash-input-s3", "<3.0.0"
gem "logstash-input-snmptrap", "<3.0.0"
gem "logstash-input-sqs", "<3.0.0"
gem "logstash-input-stdin", "<3.0.0"
gem "logstash-input-syslog", "<3.0.0"
gem "logstash-input-tcp", "<4.0.0"
gem "logstash-input-twitter", "<3.0.0"
gem "logstash-input-udp", "<3.0.0"
gem "logstash-input-unix", "<3.0.0"
gem "logstash-input-xmpp", "<3.0.0"
gem "logstash-input-zeromq", "<3.0.0"
gem "logstash-input-kafka", "<3.0.0"
gem "logstash-input-beats", "~> 3.1.0"
gem "logstash-output-cloudwatch", "<3.0.0"
gem "logstash-output-csv", "<3.0.0"
gem "logstash-output-elasticsearch", "<3.0.0"
gem "logstash-output-email", "<4.0.0"
gem "logstash-output-exec", "<3.0.0"
gem "logstash-output-file", "<3.0.0"
gem "logstash-output-ganglia", "<3.0.0"
gem "logstash-output-gelf", "<3.0.0"
gem "logstash-output-graphite", "<3.0.0"
gem "logstash-output-hipchat", "<4.0.0"
gem "logstash-output-http", "<3.0.0"
gem "logstash-output-irc", "<3.0.0"
gem "logstash-output-juggernaut", "<3.0.0"
gem "logstash-output-lumberjack", "<3.0.0"
gem "logstash-output-nagios", "<3.0.0"
gem "logstash-output-nagios_nsca", "<3.0.0"
gem "logstash-output-null", "<3.0.0"
gem "logstash-output-opentsdb", "<3.0.0"
gem "logstash-output-pagerduty", "<3.0.0"
gem "logstash-output-pipe", "<3.0.0"
gem "logstash-output-rabbitmq", "<4.0.0"
gem "logstash-output-redis", "<3.0.0"
gem "logstash-output-s3", "<3.0.0"
gem "logstash-output-sns", "<4.0.0"
gem "logstash-output-sqs", "<3.0.0"
gem "logstash-output-statsd", "<3.0.0"
gem "logstash-output-stdout", "<3.0.0"
gem "logstash-output-tcp", "<3.0.0"
gem "logstash-output-udp", "<3.0.0"
gem "logstash-output-kafka", "<3.0.0"
gem "logstash-input-http_poller", "<3.0.0"
gem "logstash-patterns-core", "<3.0.0"
