# This file is generated by Gradle as part of the build process. It extracts the build.gradle
# runtime dependencies to generate this gemspec dependencies file to be eval'ed by the gemspec
# for the jar-dependencies requirements.

gem.requirements << "jar org.apache.logging.log4j:log4j-api, 2.6.2"
gem.requirements << "jar org.apache.logging.log4j:log4j-core, 2.6.2"
gem.requirements << "jar com.fasterxml.jackson.core:jackson-core, 2.7.4"
gem.requirements << "jar com.fasterxml.jackson.core:jackson-databind, 2.7.4"
gem.requirements << "jar com.fasterxml.jackson.module:jackson-module-afterburner, 2.7.4"
gem.requirements << "jar com.fasterxml.jackson.dataformat:jackson-dataformat-cbor, 2.7.4"
