require 'rake'
require 'rspec'
require 'rspec/core/rake_task'
require 'acceptance_spec/spec_helper'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  targets = []
  Dir.glob('./serverspec_spec/*').each do |dir|
    next unless File.directory?(dir)
    target = File.basename(dir)
    target = "_#{target}" if target == "default"
    targets << target
  end

  task :all     => targets
  task :default => :all

  targets.each do |target|
    original_target = target == "_default" ? target[1..-1] : target
    desc "Run serverspec tests to #{original_target}"
    RSpec::Core::RakeTask.new(target.to_sym) do |t|
      ENV['TARGET_HOST'] = original_target
      t.pattern = "serverspec_spec/#{original_target}/*_spec.rb"
    end
  end
end


namespace :test do
  desc "Run acceptance test"
  task :acceptance, :port do |t, args|
    require "rspec/core/runner"
    require "rspec"
    port  = args[:port] || 2222
    puts "[Acceptance specs] running on port = #{port}"
    IntegrationSpecHelper.configure do |config|
      config.username = "vagrant"
      config.password = "vagrant"
      config.host     = "127.0.0.1"
      config.port     = port
    end
    exit(RSpec::Core::Runner.run([Rake::FileList["acceptance_spec/**/*_spec.rb"]]))
  end
end
