[[ls-k8s-common-problems]]
=== Common problems

Following are some suggested resolutions to problems that you may encounter when running Logstash in a Kubernetes environment.

* <<problem-keep-restart>>
* <<problem-oom>>

[float]
[[problem-keep-restart]]
=== Logstash keeps restarting
When you check the running Kubernetes pods status, {ls} shows continual restarts. 

```
NAMESPACE     NAME                                  READY   STATUS    RESTARTS      AGE
default       logstash-f7768c66d-grzbj              0/1     Running   3 (55s ago)   6m32s
```

This can be caused by a few issues.

* Unable to access health check endpoint 
* Insufficient CPU or memory to start Logstash
* Logstash startup process takes longer than `initialDelaySeconds`

To resolve the problem

* Set `api.http.host: 0.0.0.0` in `logstash.yml` to enable connection access to endpoint
* Review CPU and memory usage `kubectl top pods`
* Review the time constraint of `readinessProbe` and `livenessProbe`

[float]
[[problem-oom]]
=== Logstash stops with an OOM errors
The status of {ls} shows `Ready` but the pod continues to stop running.

This can be caused by insufficient memory. If the memory of Logstash use more than the declared resource, kubernetes kill the pod immediately and the log of Logstash does not show any shutdown related message.

Run `kubectl get event --watch` or `kubectl describe pod` to check kubernetes event if the status shows `OOMKilled`.

To resolve the problem, set a higher limit of memory.
