# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

agents:
  provider: aws
  imagePrefix: platform-ingest-logstash-ubuntu-2204-aarch64
  instanceType: "m6g.4xlarge"
  diskSizeGb: 200

steps:
  - group: "Testing Phase"
    key: "testing-phase"
    steps:
      - label: ":rspec: Ruby unit tests"
        key: "ruby-unit-tests"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          ci/unit_tests.sh ruby
        retry:
          automatic:
            - limit: 3

      - label: ":java: Java unit tests"
        key: "java-unit-tests"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          ci/unit_tests.sh java
        retry:
          automatic:
            - limit: 3

      - label: ":lab_coat: Integration Tests / part 1-of-3"
        key: "integration-tests-part-1-of-3"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          ci/integration_tests.sh split 0 3
        retry:
          automatic:
            - limit: 3

      - label: ":lab_coat: Integration Tests / part 2-of-3"
        key: "integration-tests-part-2-of-3"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          ci/integration_tests.sh split 1 3
        retry:
          automatic:
            - limit: 3

      - label: ":lab_coat: Integration Tests / part 3-of-3"
        key: "integration-tests-part-3-of-3"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          ci/integration_tests.sh split 2 3
        retry:
          automatic:
            - limit: 3

      - label: ":lab_coat: IT Persistent Queues / part 1-of-3"
        key: "integration-tests-qa-part-1-of-3"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          export FEATURE_FLAG=persistent_queues
          ci/integration_tests.sh split 0 3
        retry:
          automatic:
            - limit: 3

      - label: ":lab_coat: IT Persistent Queues / part 2-of-3"
        key: "integration-tests-qa-part-2-of-3"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          export FEATURE_FLAG=persistent_queues
          ci/integration_tests.sh split 1 3
        retry:
          automatic:
            - limit: 3

      - label: ":lab_coat: IT Persistent Queues / part 3-of-3"
        key: "integration-tests-qa-part-3-of-3"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          export FEATURE_FLAG=persistent_queues
          ci/integration_tests.sh split 2 3
        retry:
          automatic:
            - limit: 3

      - label: ":lab_coat: x-pack unit tests"
        key: "x-pack-unit-tests"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          x-pack/ci/unit_tests.sh
        retry:
          automatic:
            - limit: 3

      - label: ":lab_coat: x-pack integration"
        key: "integration-tests-x-pack"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          x-pack/ci/integration_tests.sh
        retry:
          automatic:
            - limit: 3

  - group: "Acceptance Phase"
    key: "acceptance-phase"
    steps:
      - label: "Docker [{{matrix}}] flavor acceptance"
        command: |
          set -euo pipefail

          source .buildkite/scripts/common/vm-agent.sh
          export ARCH="aarch64"
          ci/docker_acceptance_tests.sh {{matrix}}
        retry:
          automatic:
            - limit: 3
        matrix:
          - "full"
          - "oss"

      # *** TODO: enable after clarifying if acceptance tests really need vagrant on aarch64
      # - label: "Acceptance tests on {{matrix.distribution}}"
      #   agents:
      #     provider: aws
      #     imagePrefix: platform-ingest-logstash-{{matrix.distribution}}-aarch64
      #     instanceType: "m6g.4xlarge"
      #     diskSizeGb: 200
      #   command:
      #     set -euo pipefail
          
      #     source .buildkite/scripts/common/vm-agent.sh && ci/acceptance_tests.sh {{matrix.suite}}
      #   matrix:
      #     setup:
      #       suite:
      #         - "debian"
      #       distribution:
      #         - "ubuntu-2204"

  - group: "Exhaustive Acceptance Tests (Built from source)"
    key: "exhaustive-acceptance-built"
    steps:
      - label: ":package: Build & test ARM64 deb package"
        key: "build-and-test-arm64-deb"
        command: |
          set -euo pipefail
          source .buildkite/scripts/common/vm-agent.sh

          echo "--- Building ARM64 deb package"
          export ARCH="aarch64"
          ./gradlew clean bootstrap artifactDeb

          echo "--- Running acceptance tests"
          export LS_ARTIFACTS_PATH="$PWD/build"
          ./gradlew runAcceptanceTests
        retry:
          automatic:
            - limit: 3

  - group: "Exhaustive Acceptance Tests (Released 9.3.0)"
    key: "exhaustive-acceptance-released"
    steps:
      - label: ":arrow_down: Download & test released 9.3.0 ARM64 deb"
        key: "download-and-test-released-deb"
        command: |
          set -euo pipefail
          source .buildkite/scripts/common/vm-agent.sh

          echo "--- Getting current source version"
          LS_VERSION=$(grep '^logstash:' versions.yml | awk '{print $2}')
          echo "Source version: $LS_VERSION"

          echo "--- Downloading Logstash 9.3.0 ARM64 deb"
          mkdir -p build
          curl -fsSL -o build/logstash-9.3.0-arm64.deb \
            "https://artifacts.elastic.co/downloads/logstash/logstash-9.3.0-arm64.deb"

          echo "--- Renaming to match expected artifact name"
          mv build/logstash-9.3.0-arm64.deb "build/logstash-${LS_VERSION}-SNAPSHOT-arm64.deb"
          ls -la build/

          echo "--- Running acceptance tests"
          export LS_ARTIFACTS_PATH="$PWD/build"
          ./gradlew clean bootstrap
          ./gradlew runAcceptanceTests
        retry:
          automatic:
            - limit: 3
