# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  # - input: "Build parameters"
  #   fields:
  #   - select: "DRA Workflow Type"
  #     key: "WORKFLOW_TYPE"
  #     required: "true"
  #     options:
  #       - label: "snapshot"
  #         value: "snapshot"
  #       - label: "staging"
  #         value: "staging"

  - group: ":Build Artifacts"
    key: "package"
    steps:
      - label: ":package: DRA x86_64 artifact build"
        key: logstash_x86_64_dra
        agents:
          image: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-logstash-ci:0.1"
          cpu: "4"
          memory: "8Gi"
          ephemeralStorage: "100Gi"
        command: |
          export WORKFLOW_TYPE=snapshot
          export PATH="/usr/local/rbenv/bin:$PATH"
          eval "$(rbenv init -)"
          .buildkite/scripts/dra_x86_64.sh
        artifact_paths:
          - "build/logstash*"
          - "build/distributions/**/*"
      # - label: "DRA docker x86_64 docker artifact build"
      #   key: logstash_x86_64_docker_dra
      #   command: bash .buildkite/scripts/dra_x86_64.sh
      #   agents:
      #     provider: "gcp"
      #     imageProject: elastic-images-qa
      #     image: family/platform-ingest-logstash-ubuntu-2204

  - label: ":elastic-stack: Publishing to DRA"
    key: dra-public
    depends_on: package
    agents:
      provider: gcp
      imageProject: elastic-images-qa
      image: family/platform-ingest-logstash-ubuntu-2204
      machineType: "n2-standard-16"
    command: |
        echo "+++ Restoring Artifacts"
        buildkite-agent artifact download "build/logstash*" .
        buildkite-agent artifact download "build/distributions/**/*" .
        echo "+++ Changing permissions for the release manager"
        sudo chown -R :1000 build
        echo "+++ Running DRA publish step"
        ls -laRt build
