# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

## TODO rename this file to dra_pipeline_snapshot (and change the respective definition in .pipelines.yaml)
steps:
  - input: "Build parameters"
    if: build.source != "schedule"
    fields:
      - text: "VERSION_QUALIFIER_OPT"
        key: "VERSION_QUALIFIER_OPT"
        default: ""
        required: false
        hint: "Optional version qualifier for built artifacts e.g.: alpha1,beta1"

  - wait
  - label: ":pipeline: Generate steps"
    command: |
      set -eo pipefail

      local vq=$(buildkite-agent meta-data get VERSION_QUALIFIER_OPT --default "")
      if [[ ! -z $vq ]]; then
        echo "--- Detected extra version qualifier opt"
        echo "VERSION_QUALIFIER_OPT=$VERSION_QUALIFIER_OPT"
        export VERSION_QUALIFIER_OPT=$vq
      fi
      export WORKFLOW_TYPE="snapshot"
      python3 -m pip install pyyaml
      echo "Generating dynamic pipeline steps:"
      python3 .buildkite/scripts/dra/generatesteps.py
      
      python3 .buildkite/scripts/dra/generatesteps.py | buildkite-agent pipeline upload
