# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  # - input: "Build parameters"
  #   fields:
  #   - select: "DRA Workflow Type"
  #     key: "WORKFLOW_TYPE"
  #     required: "true"
  #     options:
  #       - label: "snapshot"
  #         value: "snapshot"
  #       - label: "staging"
  #         value: "staging"

  - group: ":Build Artifacts"
    key: "package"
    steps:
      - label: ":package: DRA x86_64 artifact build"
        key: logstash_x86_64_dra
        agents:
          images: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-logstash-ci"
          cpu: "4"
          memory: "8Gi"
          ephemeralStorage: "20Gi"
        command: |
          export WORKFLOW_TYPE=snapshot
          .buildkite/scripts/dra_x86_64.sh
      
      # - label: "DRA docker x86_64 docker artifact build"
      #   key: logstash_x86_64_docker_dra
      #   command: bash .buildkite/scripts/dra_x86_64.sh
      #   agents:
      #     provider: "gcp"
      #     image: family/platform-ingest-logstash-ubuntu-2204-1694606629
