# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

agents:
  image: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-logstash-ci"
  cpu: "2"
  memory: "4Gi"
  ephemeralStorage: "64Gi"

steps:
  # todo: add a step for 8.latest when Health Report MVP is landed
  - label: ":logstash: Health Report Integration tests on main branch."
    command: |
      source .buildkite/scripts/common/vm-agent.sh
      ./.buildkite/scripts/health-report-tests/main.sh
    retry:
      automatic:
        - limit: 3
