steps:
  - input: "Test Parameters"
    if: build.source != "schedule"
    fields:
      - select: "Operating System"
        key: "matrix-os"
        hint: "The operating system variant(s) to run on:"
        required: true
        multiple: true
        default: "ubuntu-2204"
        options:
          - label: "Ubuntu 22.04"
            value: "ubuntu-2204"
          - label: "Ubuntu 20.04"
            value: "ubuntu-2004"
          - label: "Ubuntu 18.04"
            value: "ubuntu-1804"
          - label: "Debian 11"
            value: "debian-11"
          - label: "Debian 10"
            value: "debian-10"
          - label: "RHEL 9"
            value: "rhel-9"
          - label: "RHEL 8"
            value: "rhel-8"
          - label: "CentOS 8"
            value: "centos-8"
          - label: "CentOS 7"
            value: "centos-7"
          - label: "Oracle Linux 8"
            value: "oraclelinux-8"
          - label: "Oracle Linux 7"
            value: "oraclelinux-7"
          - label: "Rocky Linux 8"
            value: "rocky-8"
          - label: "Amazon Linux"
            value: "amazonlinux-2023"
          - label: "OpenSUSE Leap 15"
            value: "opensuse-leap-15"

      - select: "Java"
        key: "matrix-jdk"
        hint: "The JDK to test with:"
        required: true
        multiple: true
        default: "adoptiumjdk_17"
        options:
          - label: "Adoptium JDK 17 (Eclipse Temurin)"
            value: "adoptiumjdk_17"
          - label: "Adopt OpenJDK 11"
            value: "adoptopenjdk_11"
          - label: "OpenJDK 17"
            value: "openjdk_17"
          - label: "OpenJDK 11"
            value: "openjdk_11"
          - label: "Zulu 17"
            value: "zulu_17"
          - label: "Zulu 11"
            value: "zulu_11"

  - wait: ~
    if: build.source != "schedule"

  - command: |
      set -euo pipefail

      curl -L https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -o ./yq
      chmod +x ./yq

      which buildkite-agent
      echo "--- Emitting generated dynamic steps"
      python3 -m pip install pyyaml

      python3 .buildkite/scripts/jdk-matrix-tests/generate-steps.py

      echo "--- Uploading steps to buildkite"
      python3 .buildkite/scripts/jdk-matrix-tests/generate-steps.py | buildkite-agent pipeline upload
