# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - label: ":passport_control: License check"
    key: "license-check"
    agents:
      provider: gcp
      imageProject: elastic-images-prod
      image: family/platform-ingest-logstash-ubuntu-2204
      machineType: "n2-standard-8"
      diskSizeGb: 200
    command: |
      set -euo pipefail

      if [[ -f ci/docker_license_check.sh ]]; then ci/docker_license_check.sh; else echo "No license check on this branch"; fi

  - label: ":rspec: Ruby unit tests"
    key: "ruby-unit-tests"
    agents:
      image: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-logstash-ci"
      cpu: "4"
      memory: "8Gi"
      ephemeralStorage: "100Gi"
    command: |
      set -euo pipefail

      source .buildkite/scripts/common/container-agent.sh
      ci/unit_tests.sh ruby
