# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - label: ":passport_control: License check"
    key: "license-check"
    agents:
      image: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-logstash-ci"
      cpu: "4"
      memory: "6Gi"
      ephemeralStorage: "100Gi"
    command: |
      set -euo pipefail

      source .buildkite/scripts/common/container-agent.sh
      export JRUBY_OPTS="-J-Xmx1g"
      export GRADLE_OPTS="-Xmx2g -Dorg.gradle.daemon=false -Dorg.gradle.logging.level=info"
      ci/license_check.sh -m 4G

  - label: ":rspec: Ruby unit tests"
    key: "ruby-unit-tests"
    agents:
      image: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-logstash-ci"
      cpu: "4"
      memory: "8Gi"
      ephemeralStorage: "100Gi"
    command: |
      set -euo pipefail

      source .buildkite/scripts/common/container-agent.sh
      ci/unit_tests.sh ruby

  - label: ":java: Java unit tests"
    key: "java-unit-tests"
    agents:
      image: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-logstash-ci"
      cpu: "8"
      memory: "16Gi"
      ephemeralStorage: "100Gi"
    command: |
      set -euo pipefail

      source .buildkite/scripts/common/container-agent.sh
      source .buildkite/scripts/pull-requests/sonar-env.sh
      echo "--- Debug"
      echo "SOURCE_BRANCH=$$SOURCE_BRANCH"
      echo "TARGET_BRANCH=$$TARGET_BRANCH"
      echo "PULL_ID=$$PULL_ID"
      echo "COMMIT_SHA=$$COMMIT_SHA"
      echo "--- Run unit tests"
      ci/unit_tests.sh java
