steps:
  - label: "Trigger logstash-exhaustive-tests-pipeline for PRs with qa/acceptance/ changes"
    if: build.pull_request.id != null
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          interpolation: false
          watch:
            - path:
                - ^qa/acceptance/
                - ^ci/acceptance_tests.sh
                - .buildkite/smart_exhaustive_tests_pipeline.yml
              config:
                trigger: "logstash-exhaustive-tests-pipeline"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST="${BUILDKITE_PULL_REQUEST}"
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH="${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
                    - GITHUB_PR_LABELS="${GITHUB_PR_LABELS}"
                    - ELASTIC_SLACK_NOTIFICATIONS_ENABLE="false"

  - label: "Trigger logstash-exhaustive-tests-pipeline for GitHub comments"
    if: build.env("GITHUB_PR_TRIGGER_COMMENT") != ""
    trigger: "logstash-exhaustive-tests-pipeline"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        - BUILDKITE_PULL_REQUEST="${BUILDKITE_PULL_REQUEST}"
        - BUILDKITE_PULL_REQUEST_BASE_BRANCH="${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        - GITHUB_PR_LABELS="${GITHUB_PR_LABELS}"
        - ELASTIC_SLACK_NOTIFICATIONS_ENABLE="false"
