agents:
  provider: "gcp"
  machineType: "n1-standard-4"
  image: family/core-ubuntu-2204

steps:
  # reports main, previous (ex: 7.latest) and current (ex: 8.latest) release branches to Snyk
  - label: ":hammer: Report to Snyk"
    command:
      - .buildkite/scripts/snyk/report.sh