agents:
  image: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-logstash-ci-no-root"
  cpu: "4"
  memory: "16Gi"
  ephemeralStorage: "128Gi"
  # Run as non root (logstash) user. UID is hardcoded in image.
  imageUID: "1002"

steps:
  # reports main, previous (ex: 7.latest) and current (ex: 8.latest) release branches to Snyk
  - label: ":hammer: Report to Snyk"
    command:
      - .buildkite/scripts/snyk/report.sh