notify:
  - slack:
      channels:
        - "#test-channel-for-plugin"
    if: (build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9x]+\$/) && (build.state == 'passed' || build.state == 'failed')
  - slack:
      channels:
        - "#test-channel-for-plugin"
      message: |
        🚦 Pipeline waiting for approval 🚦
        Repo: `${REPO}`

        Ready to fetch DRA artifacts - please unblock when ready.
        New version: `${NEW_VERSION}`
        Branch: `${BRANCH}`
        Workflow: `${WORKFLOW}`
        ${BUILDKITE_BUILD_URL}
    if: build.state == "blocked"

steps:
  # TODO: replace this block step by real version bump logic
  - block: "Ready to fetch for DRA artifacts?"
    prompt: |
      Unblock when your team is ready to proceed.

      Trigger parameters:
      - NEW_VERSION: ${NEW_VERSION}
      - BRANCH: ${BRANCH}
      - WORKFLOW: ${WORKFLOW}
    key: block-get-dra-artifacts
    blocked_state: running

  - label: "Fetch DRA Artifacts"
    key: fetch-dra-artifacts
    depends_on: block-get-dra-artifacts
    agents:
      image: docker.elastic.co/release-eng/ubuntu-build-essential-release-eng:latest
      cpu: 2
      memory: 4G
      ephemeralStorage: 10G
    command:
      - echo "Starting DRA artifacts retrieval..."
    timeout_in_minutes: 240
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
      manual:
        permit_on_passed: true

    plugins:
      - elastic/json-watcher#v1.0.0:
          url: "https://artifacts-staging.elastic.co/logstash/latest/${BRANCH}.json"
          field: ".version"
          expected_value: "${NEW_VERSION}"
          polling_interval: "30"
      - elastic/json-watcher#v1.0.0:
          url: "https://storage.googleapis.com/elastic-artifacts-snapshot/logstash/latest/${BRANCH}.json"
          field: ".version"
          expected_value: "${NEW_VERSION}-SNAPSHOT"
          polling_interval: "30"
