notify:
  - slack:
      channels:
        - "#test-channel-for-plugin"
    if: (build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9x]+\$/) && (build.state == 'passed' || build.state == 'failed')
  - slack:
      channels:
        - "#test-channel-for-plugin"
      message: "🚦 Pipeline waiting for approval 🚦\n*Ready to fetch DRA artifacts - Please unblock when ready.*"
    if: build.state == "blocked"

steps:
  - block: "Ready to fetch for DRA artifacts?"
    prompt: "Unblock when your team is ready to proceed."
    key: block-get-dra-artifacts
    blocked_state: running

  - label: "Fetch DRA Artifacts"
    key: fetch-dra-artifacts
    depends_on: block-get-dra-artifacts
    agents:
      image: docker.elastic.co/release-eng/ubuntu-build-essential-release-eng:latest
      cpu: 2
      memory: 4G
      ephemeralStorage: 10G
    command:
      - echo "Starting DRA artifacts retrieval..."
    timeout_in_minutes: 240
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
      manual:
        permit_on_passed: true

    plugins:
      - elastic/json-watcher#v1.0.0:
          url: "${STAGING_URL}"
          field: "${FIELD}"
          expected_value: "${EXPECTED_VALUE}"
          polling_interval: "${POLLING_INTERVAL}"
      - elastic/json-watcher#v1.0.0:
          url: "${SNAPSHOT_URL}"
          field: "${FIELD}"
          expected_value: "${EXPECTED_VALUE}-SNAPSHOT"
          polling_interval: "${POLLING_INTERVAL}"
