# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  DEFAULT_MATRIX_OS: "windows-2022"
  DEFAULT_MATRIX_JDK: "adoptiumjdk_17"

steps:
  - input: "Test Parameters"
    if: build.source != "schedule" && build.source != "trigger_job"
    fields:
      - select: "Operating System"
        key: "matrix-os"
        hint: "The operating system variant(s) to run on:"
        required: true
        multiple: true
        default: "${DEFAULT_MATRIX_OS}"
        options:
          - label: "Windows 2022"
            value: "windows-2022"
          - label: "Windows 2019"
            value: "windows-2019"
          - label: "Windows 2016"
            value: "windows-2016"

      - select: "Java"
        key: "matrix-jdk"
        hint: "The JDK to test with:"
        required: true
        multiple: true
        default: "${DEFAULT_MATRIX_JDK}"
        options:
          - label: "Adoptium JDK 21 (Eclipse Temurin)"
            value: "adoptiumjdk_21"
          - label: "Adoptium JDK 17 (Eclipse Temurin)"
            value: "adoptiumjdk_17"
          - label: "Adoptium JDK 11 (Eclipse Temurin)"
            value: "adoptiumjdk_11"
          - label: "OpenJDK 21"
            value: "openjdk_21"
          - label: "OpenJDK 17"
            value: "openjdk_17"
          - label: "OpenJDK 11"
            value: "openjdk_11"
          - label: "Zulu 21"
            value: "zulu_21"
          - label: "Zulu 17"
            value: "zulu_17"
          - label: "Zulu 11"
            value: "zulu_11"

  - wait: ~
    if: build.source != "schedule" && build.source != "trigger_job"

  - command: |
      set -euo pipefail

      echo "--- Downloading prerequisites"
      python3 -m pip install ruamel.yaml

      echo "--- Printing generated dynamic steps"
      export MATRIX_OSES="$(buildkite-agent meta-data get matrix-os --default=${DEFAULT_MATRIX_OS})"
      export MATRIX_JDKS="$(buildkite-agent meta-data get matrix-jdk --default=${DEFAULT_MATRIX_JDK})"
      set +eo pipefail
      python3 .buildkite/scripts/jdk-matrix-tests/generate-steps.py >pipeline_steps.yml
      if [[ $$? -ne 0 ]]; then
        echo "^^^ +++"
        echo "There was a problem rendering the pipeline steps."
        cat pipeline_steps.yml
        echo "Exiting now."
        exit 1
      else
        set -eo pipefail
        cat pipeline_steps.yml
      fi

      echo "--- Uploading steps to buildkite"
      cat pipeline_steps.yml | buildkite-agent pipeline upload
