source "https://rubygems.org"
gem "logstash-core", :path => "../../logstash-core"
gem "logstash-core-plugin-api", :path => "../../logstash-core-plugin-api"
gemspec

gem 'puma', github: 'kares/puma', ref: 'jruby-ssl-all_with-jar'
