:plugin: java_stdout
:type: output
:default_codec: java_line

///////////////////////////////////////////
REPLACES GENERATED VARIABLES
///////////////////////////////////////////
:include_path: ../../../../../logstash/docs/include
///////////////////////////////////////////
END - REPLACES GENERATED VARIABLES
///////////////////////////////////////////

[id="plugins-{type}s-{plugin}"]

=== Java_stdout output plugin

include::{include_path}/plugin_header-core.asciidoc[]

==== Description

Prints events to the STDOUT of the shell running Logstash. This output is convenient for debugging
plugin configurations by providing instant access to event data after it has passed through the inputs and filters.

For example, the following output configuration in conjunction with the Logstash `-e` command-line flag, will
allow you to see the results of your event pipeline for quick iteration.
[source,ruby]
    output {
      java_stdout {}
    }

Useful codecs include:

`java_line`: outputs event data in JSON format followed by an end-of-line character. This is the default codec for
java_stdout.

[source,ruby]
    output {
      stdout { }
    }

[id="plugins-{type}s-{plugin}-options"]
==== Java_stdout Output Configuration Options

There are no special configuration options for this plugin,
but it does support the <<plugins-{type}s-{plugin}-common-options>>.

[id="plugins-{type}s-{plugin}-common-options"]
include::{include_path}/{type}.asciidoc[]

:default_codec!: