[role="xpack"]
[[configuring-logstash]]
== Monitoring {ls} (legacy)

Use the {stack} {monitor-features} to gain insight into the health of
{ls} instances running in your environment.
For an introduction to monitoring your Elastic stack, see
{ref}/monitor-elasticsearch-cluster.html[Monitoring a cluster] in the
{ref}[Elasticsearch Reference].
Then, make sure that monitoring is enabled on your {es} cluster. 

These options for collecting {ls} metrics for stack monitoring have been available for a while:

* <<monitoring-with-metricbeat, {metricbeat} collection>>. Metricbeat collects
monitoring data from your {ls} instance and sends it directly to your monitoring
cluster. The benefit of Metricbeat collection is that the monitoring
agent remains active even if the {ls} instance does not.

* <<monitoring-internal-collection-legacy,Legacy collection (deprecated)>>. 
Legacy collectors send monitoring data to your production cluster.


For more features, dependability, and easier management, consider using: 

* <<monitoring-with-elastic-agent, {agent} collection for Stack Monitoring>>. {agent} collects
monitoring data from your {ls} instance and sends it directly to your monitoring
cluster, and shows the data in {ls} Dashboards.
The benefit of {agent} collection is that the monitoring agent remains
active even if the {ls} instance does not, you can manage all your
monitoring agents from a central location in {fleet}. 

include::monitoring-mb.asciidoc[]
include::monitoring-internal-legacy.asciidoc[]
include::monitoring-ui.asciidoc[]
include::pipeline-viewer.asciidoc[]
include::troubleshooting.asciidoc[]
