---
version: '3.0'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.0.0
    volumes:
      - ./examples/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elastic-stack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:8.0.0
    networks:
      - elastic-stack

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports: [ '5601:5601' ]
    networks:
      - elastic-stack

networks:
  elastic-stack:
