==== Common Options

// Contributors: You must conditionally code all internal links and IDs in this
// file to make the common files work in both the LS Reference and the versioned
// plugin docs

The following configuration options are supported by all output plugins:

ifeval::["{versioned_docs}"!="true"]
[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
ifndef::no_codec[]
| <<plugins-{type}s-{plugin}-codec>> |{logstash-ref}/configuration-file-structure.html#codec[codec]|No
endif::no_codec[]
| <<plugins-{type}s-{plugin}-enable_metric>> |{logstash-ref}/configuration-file-structure.html#boolean[boolean]|No
| <<plugins-{type}s-{plugin}-id>> |{logstash-ref}/configuration-file-structure.html#string[string]|No
|=======================================================================
endif::[]
ifeval::["{versioned_docs}"=="true"]
[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
ifndef::no_codec[]
| <<{version}-plugins-{type}s-{plugin}-codec>> |{logstash-ref}/configuration-file-structure.html#codec[codec]|No
endif::no_codec[]
| <<{version}-plugins-{type}s-{plugin}-enable_metric>> |{logstash-ref}/configuration-file-structure.html#boolean[boolean]|No
| <<{version}-plugins-{type}s-{plugin}-id>> |{logstash-ref}/configuration-file-structure.html#string[string]|No
|=======================================================================
endif::[]

ifndef::no_codec[]
ifeval::["{versioned_docs}"!="true"]
[id="plugins-{type}s-{plugin}-codec"]
endif::[]
ifeval::["{versioned_docs}"=="true"]
[id="{version}-plugins-{type}s-{plugin}-codec"]
endif::[]
===== `codec`

  * Value type is {logstash-ref}/configuration-file-structure.html#codec[codec]
ifdef::default_codec[]
  * Default value is +"{default_codec}"+
endif::[]
ifndef::default_codec[]
  * Default value is `"plain"`
endif::[]

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output without needing a separate filter in your Logstash pipeline.
endif::no_codec[]

ifeval::["{versioned_docs}"!="true"]
[id="plugins-{type}s-{plugin}-enable_metric"]
endif::[]
ifeval::["{versioned_docs}"=="true"]
[id="{version}-plugins-{type}s-{plugin}-enable_metric"]
endif::[]
===== `enable_metric`

  * Value type is {logstash-ref}/configuration-file-structure.html#boolean[boolean]
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance.
By default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

ifeval::["{versioned_docs}"!="true"]
[id="plugins-{type}s-{plugin}-id"]
endif::[]
ifeval::["{versioned_docs}"=="true"]
[id="{version}-plugins-{type}s-{plugin}-id"]
endif::[]
===== `id`

  * Value type is {logstash-ref}/configuration-file-structure.html#string[string]
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one.
It is strongly recommended to set this ID in your configuration. This is particularly useful
when you have two or more plugins of the same type. For example, if you have 2 {plugin} outputs.
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

["source","json",subs="attributes"]
---------------------------------------------------------------------------------------------------
output {
  {plugin} {
    id => "my_plugin_id"
  }
}
---------------------------------------------------------------------------------------------------

NOTE: Variable substitution in the `id` field only supports environment variables
      and does not support the use of values from the secret store.

