[subs="attributes"]
++++
<titleabbrev>{plugin}</titleabbrev>
++++

* Plugin version: {version}
* Released on: {release_date}
* {changelog_url}[Changelog]

ifeval::["{support_level}"=="t1"]
* Level of support = https://www.elastic.co/support/matrix#logstash_plugins[Elastic Tier 1]
endif::[]

ifeval::["{support_level}"=="t2"]
* Level of support = https://www.elastic.co/support/matrix#logstash_plugins[Elastic Tier 2]
endif::[]

ifeval::["{support_level}"=="comm"]
* Level of support = Community plugin
endif::[]

ifeval::["{support_level}"=="partner"]
* Level of support = Partner plugin
endif::[]

For other versions, see the
{lsplugindocs}/{type}-{plugin}-index.html[Versioned plugin docs].

ifeval::["{default_plugin}"=="0"]

==== Installation

For plugins not bundled by default, it is easy to install by running +bin/logstash-plugin install logstash-{type}-{plugin}+. See {logstash-ref}/working-with-plugins.html[Working with plugins] for more details.

endif::[]

==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/logstash-plugins/logstash-{type}-{plugin}[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#logstash_plugins[Elastic Support Matrix].

