ifeval::["{versioned_docs}"!="true"]
++++
<titleabbrev>{plugin}</titleabbrev>
++++
endif::[]
ifeval::["{versioned_docs}"=="true"]
++++
<titleabbrev>{version}</titleabbrev>
++++
endif::[]

* Plugin version: {version}
* Released on: {release_date}
* {changelog_url}[Changelog]

ifeval::["{versioned_docs}"!="true"]

For other versions, see the
{lsplugindocs}/{type}-{plugin}-index.html[Versioned plugin docs].

endif::[]

ifeval::["{versioned_docs}"=="true"]

For other versions, see the <<{type}-{plugin}-index,overview list>>.

To learn more about Logstash, see the {logstash-ref}/index.html[Logstash Reference].

endif::[]

ifeval::[("{default_plugin}"=="0") and ("{versioned_docs}"!="true")]

==== Installation

For plugins not bundled by default, it is easy to install by running +bin/logstash-plugin install logstash-{type}-{plugin}+. See {logstash-ref}/working-with-plugins.html[Working with plugins] for more details.

endif::[]

==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/logstash-plugins/logstash-{type}-{plugin}[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#matrix_logstash_plugins[Elastic Support Matrix].

