plugins:
  - logstash-filter-date:
    logstash_branch: 'main'
  - logstash-filter-dissect:
    logstash_branch: 'main'
  - logstash-filter-geoip:
    logstash_branch: 'main'
  - logstash-filter-useragent
  - logstash-input-azure_event_hubs
  - logstash-input-dead_letter_queue:
    logstash_branch: 'main'
  - logstash-input-file
  - logstash-integration-jdbc
  - logstash-integration-kafka:
    branches: [main, 11.x]
  - logstash-integration-snmp
  - logstash-integration-aws
  - logstash-input-http:
    branches: [main, 3.x]
  - logstash-input-tcp:
    branches: [main, 6.x]
  - logstash-input-beats:
    branches: [main, 6.x]
  - logstash-filter-elastic_integration:
    branches: [main, 'use-release-branches']
    ignore_branches: [7.x]
    logstash_branch: 'match-with-plugin-branches'