[[ls-security]]
== Security
[subs="attributes"]
++++
<titleabbrev>Security</titleabbrev>
++++

The Logstash {es} {logstash-ref}/plugins-outputs-elasticsearch.html[output],
{logstash-ref}/plugins-inputs-elasticsearch.html[input], and
{logstash-ref}/plugins-filters-elasticsearch.html[filter] plugins,  as well as
{logstash-ref}/monitoring-logstash.html[monitoring] and central management,
support authentication and encryption over HTTPS.

To use Logstash with a secured cluster, you need to configure authentication
credentials for Logstash. Logstash throws an exception and the processing
pipeline is halted if authentication fails.

If encryption is enabled on the cluster, you also need to enable TLS/SSL in the
Logstash configuration.

In addition to configuring authentication credentials for Logstash, you need
to grant authorized users permission to access the Logstash indices.

include::es-security.asciidoc[]
include::basic-auth.asciidoc[]
include::grant-access.asciidoc[]
include::pki-auth.asciidoc[]
include::tls-encryption.asciidoc[]
include::ls-monitoring.asciidoc[]
include::pipeline-mgmt.asciidoc[]
include::api-keys.asciidoc[]
