[[ls-security]]
== Secure your connection to {es} 
[subs="attributes"]
++++
<titleabbrev>Secure your connection</titleabbrev>
++++

The {ls} {es} {logstash-ref}/plugins-outputs-elasticsearch.html[output],
{logstash-ref}/plugins-inputs-elasticsearch.html[input], and
{logstash-ref}/plugins-filters-elasticsearch.html[filter] plugins,  as well as
{logstash-ref}/monitoring-logstash.html[monitoring] and central management,
support authentication and encryption over HTTPS.

{es} clusters are secured by default (starting in 8.0). 
You need to configure authentication credentials for {ls} in order to
establish communication.
{ls} throws an exception and the processing pipeline is halted if authentication fails.

In addition to configuring authentication credentials for {ls}, you need
to grant authorized users permission to access the {ls} indices.

Security is enabled by default on the {es} cluster (starting in 8.0).
You must enable TLS/SSL in the {es} output section of the {ls} configuration in order to allow {ls} to communicate with the {es} cluster.

include::es-security.asciidoc[]
include::basic-auth.asciidoc[]
include::grant-access.asciidoc[]
include::tls-encryption.asciidoc[]
include::pki-auth.asciidoc[]
include::ls-monitoring.asciidoc[]
include::pipeline-mgmt.asciidoc[]
include::api-keys.asciidoc[]
