[role="xpack"]
[[ls-security]]
== Secure Logstash
[subs="attributes"]
++++
<titleabbrev>Secure {ls}</titleabbrev>
++++

////
// ToDo: This section is a collection of random security statements. Needs rework and rearchitecture.
////

The Logstash {es} {logstash-ref}/plugins-outputs-elasticsearch.html[output],
{logstash-ref}/plugins-inputs-elasticsearch.html[input], and
{logstash-ref}/plugins-filters-elasticsearch.html[filter] plugins,
{logstash-ref}/monitoring-logstash.html[monitoring], and central management
support authentication and encryption over HTTP.

To use Logstash with a secured cluster, you need to configure authentication
credentials for Logstash. Logstash throws an exception and the processing
pipeline is halted if authentication fails.
If encryption is enabled on the cluster, you also need to enable TLS/SSL in the
Logstash configuration.

In addition to configuring authentication credentials for Logstash, you need
to grant authorized users permission to access the Logstash indices.
