#! /bin/sh
#
# Logstash Start/Stop logstash
#
# chkconfig: 345 99 99
# description: Logstash
# processname: logstash

logstash_bin="/usr/bin/logstash"
logstash_conf="/etc/logstash/logstash.yaml"
logstash_log="/var/log/logstash/logstash.log"
NICE_LEVEL="19"

case $1 in
start)
        LOG_DIR=`dirname ${logstash_log}`
        if [ ! -d $LOG_DIR ]; then
          echo "Log dir ${LOG_DIR} doesn't exist. Creating"
          mkdir $LOG_DIR
        fi
        nice -n ${NICE_LEVEL} ${logstash_bin} -d -f ${logstash_conf} -l ${logstash_log}
        ;;
stop)
        pkill -u root logstash
        exit 0
        ;;
reload)
        stop
        start
        ;;
restart)
        stop
        start
        ;;
status)
        pgrep logstash  >&/dev/null
        exit $?
        ;;
*)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        RETVAL=1
esac
exit 0
