#!/bin/bash -x

IMAGE_NAME=lsinteg

if [[ -z "$PROJECT" ]]; then 
  PROJECT="ls_integ"
fi

echo "Using docker-compose project '$PROJECT'"

RUN_PREFIX=docker
LOGSTASH_VERSION=$(cat versions.yml  | egrep '^logstash:' | cut -d' ' -f 2)

function startdev {
  # If container exists, start it
  docker ps -a | awk '{print $NF}' | grep lsdev
  if [[ $? -eq 0 ]]; then
    docker start lsdev
  else # Otherwise run it
    #-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n
    docker run \
      -v "$PWD:/mnt/host:delegated" \
      -e 'LS_JAVA_OPTS=-Xmx1500M -Xms1500M' \
      -e 'INTEGRATION=true' \
      -e "JRUBY_OPTS=-Xcompile.invokedynamic=false" \
      -d \
      --name lsdev \
      $IMAGE_NAME \
      bash -c ' tail -f /dev/null'
  fi
  # Speeds up gem install etc.
  docker exec lsdev rsync /mnt/host/vendor /opt/logstash/vendor
}

function rsyncdev {
  docker exec lsdev rsync --delete --exclude .git --exclude logs --exclude build --exclude .gradle --exclude vendor -r /mnt/host/ /opt/logstash/ 
}

function build {
  docker build -t $IMAGE_NAME .
}


case "$1" in
  "build") 
    docker stop lsdev
    docker rm lsdev
    build
  ;;
  "ci_integration")
    echo "Rebuilding images just in case"
    build
    time $RUN_PREFIX run -it --rm $IMAGE_NAME bash -ic "ci/integration_run.sh ${@:2}"
  ;;
  "ci_parallel_integration")
    build
    num_specs=find qa/integration/ -name "*_spec.rb" | wc -l
  ;;
  "ci_cli")
    build
    $RUN_PREFIX run -it --rm $IMAGE_NAME bash -l
  ;;
  "dev_integration")
    startdev
    rsyncdev
    time $RUN_PREFIX exec -it lsdev bash -c "ln -sf /opt/logstash build/$LOGSTASH_VERSION && bash -i -c \"$INTEGRATION_SETUP && ci/travis_integration_run.sh ${@:2}\""
  ;;
  "dev_stop")
    $RUN_PREFIX stop lsdev
   ;; 
  "dev_cli")
    startdev
    echo "Don't forget to rsync"
    #TODO: This should search for running containers and connect to them, starting a new one only if needed
    time $RUN_PREFIX exec -it lsdev bash -c "$INTEGRATION_SETUP && mkdir -p build && ln -sf /opt/logstash build/logstash-$LOGSTASH_VERSION-SNAPSHOT && bash -l"
  ;;
  "dev_rsync")
    rsyncdev
  ;;
  "dev_cleanup")
    docker stop lsdev
    docker rm $(docker ps -aq)
    build
  ;;
  *)
    echo "Examples command: "
    echo "# Run integration test as it would be run on CI server"
    echo "ci/docker_tool ci_integration"
    echo "# Start a CLI prompt with the container setup as it would be for ci_integration"
    echo "ci/docker_run ci_cli"
    echo "# Start a container named '$DEV_CONTAINER_NAME' that sticks around for experimenting with tests"
    echo "ci/docker_run ci_cli"
    echo "# Rsync the folder contents to the dev container. Must be done to synchronize any local changes"
    echo "ci/docker_run rsync"
    echo "# Destroy the dev container to achieve a clean state"
    echo "ci/docker_run dev_cleanup"
  ;;
esac