# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

agents:
  cpu: "2"
  memory: "4Gi"
  ephemeralStorage: "20Gi"

steps:
  - label: ":wave: Greetings"
    command: "echo 'TODO: run DRA Logstash'"
    # TODO once https://github.com/elastic/ci-agent-images/pull/356 has been merged
    # agents:
    #   image: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-logstash-ci:0.1"
