[role="xpack"]
[[configuring-centralized-pipelines]]
=== Configuring Centralized Pipeline Management
++++
<titleabbrev>Centralized Pipeline Management</titleabbrev>
++++

To configure
{logstash-ref}/logstash-centralized-pipeline-management.html[centralized pipeline management]:

. Verify that you are using a license that includes the pipeline management 
feature.
+
--
For more information, see https://www.elastic.co/subscriptions and 
{xpack-ref}/license-management.html[License Management].
--

. Specify 
<<configuration-management-settings,configuration management settings>> in the
`logstash.yml` file. At a
minimum, set:
+
* `xpack.management.enabled: true` to enable centralized configuration
management.
* `xpack.management.elasticsearch.url` to specify the Elasticsearch
instance that will store the Logstash pipeline configurations and metadata.
* `xpack.management.pipeline.id` to register the pipelines that you want to
centrally manage.

. Restart Logstash.

. If your Elasticsearch cluster is protected with basic authentication, assign
the `logstash_admin` role to any users who will use centralized pipeline
management. See <<ls-security>>.

NOTE: Centralized management is disabled until you configure and enable
{security}.

IMPORTANT: After you've configured Logstash to use centralized pipeline
management, you can no longer specify local pipeline configurations. This means
that the `pipelines.yml` file and settings like `path.config` and
`config.string` are inactive when this feature is enabled.

include::{log-repo-dir}/static/settings/configuration-management-settings.asciidoc[]
