source "https://rubygems.org"
gemspec :path => File.expand_path(File.join(File.dirname(__FILE__), "..")), :name => "logstash", :development_group => :development

# in development if a local, unpublished gems is required, you must add it first in the gemspec without the :path option
# and also add it here with the :path option.