source "https://rubygems.org"
gemspec :path => File.expand_path(File.join(File.dirname(__FILE__), "..")), :name => "logstash", :development_group => :development

# in development if a local, unpublished gems is required, you must add it first in the gemspec without the :path option
# and also add it here with the :path option.

# local dev setup
# gem "jruby-mmap", :path => File.expand_path("../../../jruby-mmap", __FILE__)
# gem "jruby-mmap-queues", :path => File.expand_path("../../../jruby-mmap-queues", __FILE__)

# tmp PR WIP setup
gem "jruby-mmap", ">= 0.1.1", :github => "colinsurprenant/jruby-mmap", :ref => "master"
gem "jruby-mmap-queues", ">= 0.1.1", :github => "colinsurprenant/jruby-mmap-queues", :ref => "master"
