[[logstash-reference]]
= Logstash Reference

:branch:                5.4
:major-version:         5.4
:logstash_version:      5.4.0
:elasticsearch_version: 5.4.0
:docker-image:          docker.elastic.co/logstash/logstash:{logstash_version}

//////////
release-state can be: released | prerelease | unreleased
//////////
:release-state:  released

:jdk:                   1.8.0
:guide:                 https://www.elastic.co/guide/en/elasticsearch/guide/current/
:ref:                   https://www.elastic.co/guide/en/elasticsearch/reference/{branch}/
:xpack:                 https://www.elastic.co/guide/en/x-pack/{branch}/
:logstash:              https://www.elastic.co/guide/en/logstash/{branch}/
:filebeat:              https://www.elastic.co/guide/en/beats/filebeat/{branch}/
:lsissue:               https://github.com/elastic/logstash/issues/
:security:              X-Pack Security

[[introduction]]
== Logstash Introduction

Logstash is an open source data collection engine with real-time pipelining capabilities. Logstash can dynamically
unify data from disparate sources and normalize the data into destinations of your choice. Cleanse and democratize all
your data for diverse advanced downstream analytics and visualization use cases.

While Logstash originally drove innovation in log collection, its capabilities extend well beyond that use case. Any
type of event can be enriched and transformed with a broad array of input, filter, and output plugins, with many
native codecs further simplifying the ingestion process. Logstash accelerates your insights by harnessing a greater
volume and variety of data.

include::static/introduction.asciidoc[]

include::static/getting-started-with-logstash.asciidoc[]