# This file is generated by Gradle as part of the build process. It extracts the build.gradle
# runtime dependencies to generate this gemspec dependencies file to be eval'ed by the gemspec
# for the jar-dependencies requirements.

