name: Attach labels
on:
  issues:
    types: ['opened']
  pull_request:
    types: ['opened']
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: KeisukeYamashita/attach-labels@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs-triage
