name: mergify backport labels copier

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read

jobs:
  mergify-backport-labels-copier:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'mergify/bp/')
    permissions:
      # Add GH labels
      pull-requests: write
      # See https://github.com/cli/cli/issues/6274
      repository-projects: read
    steps:
      - uses: elastic/oblt-actions/mergify/labels-copier@v1
        with:
          excluded-labels-regex: "^backport-*"
