name: openapi-publish
on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
    paths:
      - 'docs/static/spec/openapi/**'
permissions:
  contents: read
  id-token: write # required for OIDC to AWS in openapi/upload
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: elastic/docs-actions/openapi/lint@v1
        with:
          spec-path: docs/static/spec/openapi/logstash-api.yaml
      - uses: elastic/docs-actions/openapi/upload@v1
        with:
          spec-path: docs/static/spec/openapi/logstash-api.yaml
          spec-name: logstash
