name: PR Helper

on: [pull_request, pull_request_review, issue_comment]

jobs:
  prhelper_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run PR Helper
      id: runprhelper
      uses: Matticusau/pr-helper@v1.2.6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        prlabel-default: needs-triage
        prlabel-ready: needs-triage
        prlabel-onhold: needs-triage
        prlabel-reviewrequired: needs-triage
