# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative "./platform_config.rb"

Vagrant.configure(2) do |config|
  platforms = PlatformConfig.new

  platforms.each do |platform|
    config.vm.define platform.name do |machine|
      machine.vm.box = platform.box
      machine.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
      end
      machine.vm.synced_folder "../build", "/logstash-build", create: true

      machine.vm.provision :shell do |sh|
        sh.path = platform.bootstrap.privileged
        sh.privileged = true
      end

      machine.vm.provision :shell do |sh|
        sh.path = platform.bootstrap.non_privileged
        sh.privileged = false
      end
    end
  end
end
